from yardim_59_63 import Q, kur, yaz

E4 = "Eşya → 4’lü pozisyon"
OT = "Olumsuz teşhis"
FA = "Farklı/aynı pozisyon veya fasıl"
FN = "Fasıl notu · Tanım/Eşik"
GY = "Genel Yorum Kuralı"
EB = "Eşleştirme / Boşluk doldurma"
CC = "Çoktan-çoğa (I–IV)"
SN = "Senaryo"

sorular = [
    Q(E4,
      "Tarife Cetveline göre, otomobil lastiği üretiminde kullanılan, çözgü iplikleri yüksek mukavemetli poliester filament iplikten oluşan, atkı iplikleri yalnızca çözgüleri yerinde tutan ve kauçuğa daldırılarak kaplanmış kord bezi hangi pozisyonda sınıflandırılır?",
      "59.02", ["59.06", "59.03", "59.11", "59.10"],
      "59.02, naylon veya diğer poliamidlerden, poliesterlerden veya viskoz ipeğinden elde edilen yüksek mukavemetli iplikten nakil vasıtası lastikleri için kord bezini kapsar; plastik veya kauçuk emdirilmiş ya da bunlara batırılarak kaplanmış olması sonucu değiştirmez. 59.03 ve 59.06 metinleri 59.02’dekileri açıkça hariç tutar. Tuzak, kauçuk kaplamayı görüp doğrudan kauçuklu mensucata gitmektir.",
      "59.02 pozisyon metni ve Açıklama Notu; Bölüm XI Not 6."),
    Q(E4,
      "Tarife Cetveline göre, duvar ve tavan tezyinatına uygun, eni 53 cm olan rulolar halinde bulunan ve dokunmuş mensucattan yüzü kağıt bir mesnet üzerine tespit edilmiş kaplama hangi pozisyonda sınıflandırılır?",
      "59.05", ["48.14", "59.07", "39.18", "59.04"],
      "Fasıl 59 Not 4’e göre eni 45 cm’den az olmayan rulolar halinde, dokumaya elverişli yüzü bir mesnede tespit edilmiş duvar kaplamaları 59.05’tedir. 48.14, kağıt üzerine doğrudan tespit edilmiş mensucat kırpıntısı veya tozundan kaplamalar içindir; burada yüz dokunmuş mensucattır. 39.18 plastikten duvar kaplaması, 59.04 yer kaplaması pozisyonudur.",
      "Fasıl 59 Not 4; 59.05 Açıklama Notu."),
    Q(E4,
      "Tarife Cetveline göre, gaz lambalarında kullanılmak üzere pamuktan dokunmuş, yerleştirmeyi kolaylaştırmak için belirli boyda kesilmiş yassı fitil hangi pozisyonda sınıflandırılır?",
      "59.08", ["34.06", "36.03", "56.07", "70.19"],
      "59.08, lamba, ocak, çakmak ve mum için dokunmuş veya örülmüş fitilleri kapsar; kesilmiş olmaları veya metal teferruatla donatılmaları sonucu değiştirmez. Mumlu fitiller 34.06’ya, emniyet ve infilak fitilleri 36.03’e, sicim ve iplerin basitçe bükülmesiyle elde edilen fitiller 56.07’ye, cam liflerinden fitiller 70.19’a gider.",
      "59.08 Açıklama Notu (A) ve hariç tutmalar."),
    Q(E4,
      "Tarife Cetveline göre, un eleme işlerinde kullanılan, gözleri muntazam geometrik şekil ve boyutta olup kullanımla bozulmayan, sentetik filament iplikten dokunmuş, top halindeki eleklik mensucat hangi pozisyonda sınıflandırılır?",
      "59.11", ["56.08", "58.04", "96.04", "59.07"],
      "Fasıl 59 Not 8(a)(ii) uyarınca uzunlamasına veya sadece kare/dikdörtgen kesilmiş parça halindeki eleklik gaz ve bezler 59.11’dedir. Eleklik mensucat ağ, file veya tül sayılmaz; 56.08 ve 58.04 bu nedenle elenir. El kalburları ve el elekleri ise 96.04’tedir.",
      "Fasıl 59 Not 8(a)(ii); 59.11 Açıklama Notu (A)."),
    Q(E4,
      "Tarife Cetveline göre, tiyatro sahnesinde dekor olarak kullanılmak üzere üzerine bir oda iç mekânı boyanmış ve ahşap bir çerçeveye gerilmiş bez hangi pozisyonda sınıflandırılır?",
      "59.07", ["59.01", "63.03", "63.04", "59.05"],
      "59.07, emdirilmiş, sıvanmış veya kaplanmış diğer mensucatın yanında tiyatro dekorları, atölye fonları ve benzeri işler için boyanmış bezleri de kapsar; bunlar top halinde, kesilmiş veya çerçeveye gerilmiş olabilir. 59.01’deki hazır tuval resim yapmaya hazırlanmış sıvanmış tuvaldir; 63.03 tiyatro sahnesi perdelerinin yeridir. Boyanarak desen verilmiş mensucatın 59.07 dışında kalması kuralının istisnası budur.",
      "59.07 pozisyon metni ve Açıklama Notu (II); Fasıl 59 Not 6(b)."),

    Q(OT,
      "Aşağıdakilerden hangisi 59.03 pozisyonunda <b>sınıflandırılmaz</b>?",
      "Su geçirmezlik kazandırmak için emdirilmiş, emdirmesi çıplak gözle görülmeyen poliester gabardin",
      ["Deriyi taklit edecek şekilde kabartılmış, tek yüzü görülür biçimde PVC ile kaplanmış pamuklu mensucat",
       "Metrekare ağırlığı yüksek olmakla birlikte 7 mm çaplı silindire kırılmadan sarılabilen plastik sıvalı mensucat",
       "Termoplastik maddenin görünür parçacıkları püskürtülerek ısı ve basınçla yapışır hale getirilmiş mensucat",
       "56.04’teki plastikle kaplanmış şeritlerden dokunmuş mensucat"],
      "Emdirme, sıvama veya kaplamanın çıplak gözle görülmediği mensucat 59.03 dışındadır ve genellikle 50–55, 58 veya 60. fasıllarda kalır; su geçirmez gabardin ve poplinler açıklama notunda örnek olarak sayılmıştır. 59.03’te metrekare ağırlığı önemsizdir; termoplastik parçacık püskürtülmüş mensucat ve 56.04 türü kaplı şeritten mensucat açıkça bu pozisyondadır.",
      "Fasıl 59 Not 2(a)(1) ve 2(b); 59.03 Açıklama Notu."),
    Q(OT,
      "Aşağıdakilerden hangisi Tarife Cetvelinin 59. faslında <b>yer almaz</b>?",
      "Kauçukla sıvanmış dokunmuş mensucattan transmisyon kayışı",
      ["Sentetik liflerden dokunmuş yangın söndürme hortumu",
       "Kağıt imal makinelerinde kullanılan nihayetsiz keçe",
       "Beyaz alevli lambalar için gömlek",
       "Jüt zemin üzerine bezir esaslı hamur sıvanmış linoleum"],
      "Fasıl 59 Not 7(b) uyarınca kauçuk emdirilmiş, sıvanmış, kaplanmış veya lamine mensucattan transmisyon ve taşıyıcı kolanlar 59.10’a değil 40.10’a girer. Yangın hortumu 59.09, kağıt makinesi keçesi 59.11, lamba gömleği 59.08, linoleum 59.04’tedir.",
      "Fasıl 59 Not 7(b); 59.10 Açıklama Notu (b)."),
    Q(OT,
      "Aşağıdakilerden hangisi 59.07 pozisyonunda <b>yer almaz</b>?",
      "Nişasta esaslı normal apre ile finisaj görmüş organdi",
      ["Tente imalinde kullanılan, katranla sıvanmış mensucat",
       "Yanmaz hale getirilmek için silikatla sıvanmış perdelik mensucat",
       "Sinema perdesi için cam kürecikleriyle kaplanmış mensucat",
       "Taklit kadife üretimi için tutkal üzerine kırpıntı tozu kaplanmış mensucat"],
      "Fasıl 59 Not 6(d) uyarınca esası nişastalı ve benzeri maddeler olan normal aprelerle finisaj görmüş mensucat 59.07’ye girmez; organdi ve müslin açıklama notunda örnektir. Katran, silikat ve cam kürecik kaplamalar 59.07’de sayılmıştır; kırpıntı tozuyla desen oluşturma hariç tutulsa da taklit kadife ve peluş özellikle bu pozisyonda bırakılmıştır.",
      "Fasıl 59 Not 6(c)–(d); 59.07 Açıklama Notu (I)."),
    Q(OT,
      "Fasıl 59 Not 8 ve 59.11 Açıklama Notuna göre aşağıdakilerden hangisi 59.11 pozisyonunda <b>sınıflandırılmaz</b>?",
      "Motorlu taşıtlar için dokumaya elverişli maddelerden emniyet kemeri",
      ["Yağ preslerinde kullanılan, insan saçından filtre torbası",
       "Elektrik süpürgelerine mahsus toz torbası",
       "Pompa ve motorlar için dokumaya elverişli maddelerden conta (84.84’tekiler hariç)",
       "Sanayide yağlama veya ambalaj eşyası olarak kullanılan, grafit emdirilmiş ip"],
      "59.11 Açıklama Notu, dokumaya elverişli maddelerden emniyet kemerlerinin Bölüm XVII’de (87.08) kaldığını ve 59.11’e girmediğini açıkça belirtir. İnsan saçından filtre torbası Bölüm XI Not 1(b) ve Fasıl 59 Not 8(a)(iii) gereği 59.11’dedir; toz torbası, conta ve yağlama/ambalaj ipi de açıklama notunda sayılmıştır.",
      "Fasıl 59 Not 8; 59.11 Açıklama Notu; Bölüm XI Not 1(b)."),

    Q(FA,
      "Aşağıdakilerden hangisi diğerlerinden farklı bir pozisyonda sınıflandırılır?",
      "Kitap ciltlerinde kullanılan, plastikle sıvanmış deri taklidi mensucat",
      ["Kitap ciltlerinde kullanılan, nişastalı maddeyle kalınca sıvanmış pamuklu bez",
       "Teknik ressamların kopya işlerinde kullandığı mühendis muşambası",
       "Şapka kasnakları imalinde kullanılan bukran",
       "Bir yüzü bezir ve çinko oksit karışımıyla sıvanıp çerçeveye gerilmiş hazır tuval"],
      "Zamk veya nişastalı maddelerle sıvanmış cilt bezi, mühendis muşambası, hazır tuval ve bukran 59.01’dedir. Aynı amaçla kullanılsa bile plastik emdirilmiş veya sıvanmış mensucat (deri taklidi gibi) 59.01’den hariç tutulmuş ve 59.03’e gönderilmiştir. Tuzak, kullanım amacının pozisyonu belirlediğini sanmaktır; belirleyici olan sıvama maddesidir.",
      "59.01 Açıklama Notu; 59.03 Açıklama Notu."),
    Q(FA,
      "Aşağıdaki eşya çiftlerinden hangisinde her iki eşya da <b>aynı</b> pozisyonda sınıflandırılır?",
      "Mensucat zeminli kauçuk yapışkanlı yalıtım bandı – 1.200 g/metrekare kauçuk kaplı mensucat",
      ["Linoleum – plastikten duvar kaplaması",
       "Yüksek mukavemetli naylon iplikten kord bezi – plastikle kaplanmış dokunmuş mensucat",
       "Sentetik liften yangın hortumu – içi yalnızca mensucatla takviyeli vulkanize kauçuk hortum",
       "Kapitoneli mensucat – kauçukla lamine edilmiş mensucat"],
      "Mensucattan ve yapıştırıcı kauçuktan yapılmış bantlar (elektrik yalıtım şeritleri dahil) ile metrekare ağırlığı 1.500 g’ı geçmeyen kauçuklu mensucat 59.06’dadır. Diğer çiftlerde pozisyonlar ayrılır: linoleum 59.04 – plastik duvar kaplaması 39.18; kord bezi 59.02 – plastik kaplı mensucat 59.03; tekstil hortum 59.09 – kauçuk hortum 40.09; kapitoneli mensucat 58.11 – kauçuklu mensucat 59.06.",
      "Fasıl 59 Not 5; 59.05, 59.06 ve 59.09 Açıklama Notları."),
    Q(FA,
      "Aşağıdakilerden hangisi diğerlerinden farklı bir fasılda sınıflandırılır?",
      "İki yüzü tamamen ve görülür biçimde plastikle kaplanmış mensucat",
      ["Tek yüzü PVC ile kaplanmış, esnekliğini koruyan örme mensucat",
       "Tek yüzü kauçukla kaplanmış, metrekare ağırlığı 900 g olan mensucat",
       "Tabakaları bir plastik filmle birbirine bağlanarak lamine edilmiş mensucat",
       "Mumlu maddelerle sıvanmış dokunmuş mensucat"],
      "Fasıl 59 Not 2(a)(3) uyarınca her iki yüzü tamamen plastikle sıvanmış veya kaplanmış mensucat 59.03’e girmez, Fasıl 39’a gider. Tek yüzü PVC kaplı örme mensucat ve plastikle lamine mensucat 59.03’te, kauçukla kaplı 900 g’lık mensucat 59.06’da, mumlu mensucat 59.07’de, yani hepsi Fasıl 59’dadır.",
      "Fasıl 59 Not 1, 2(a)(3), 3 ve 5; 59.07 Açıklama Notu."),
    Q(FA,
      "Tarife Cetveline göre, mensucatla birleştirilmiş aşağıdaki ürünlerden hangisi diğerlerinden farklı bir fasılda yer alır?",
      "Tutkal üzerine ince bir mika tozu tabakası kaplanmış mensucat",
      ["Mesnedi dokumaya elverişli mensucat olan, tabii veya suni aşındırıcı tozla kaplı ürün",
       "Mesnedi dokumaya elverişli mensucat olan aglomere mika",
       "Alt tabakası mensucat olan, bir yüzü asfaltla kaplanmış çatı malzemesi",
       "Karbon liflerinden dokunmuş mensucat"],
      "Mika tozuyla kaplanmış mensucat 59.07 Açıklama Notunun (G) bendinde sayılmıştır ve Fasıl 59’dadır. Mensucat mesnetli aglomere mika 68.14’e, aşındırıcı kaplı ürün 68.05’e, asfalt kaplı çatı malzemesi 68.07’ye, karbon liflerinden eşya 68.15’e, yani Fasıl 68’e gider. Tuzak, “mika” kelimesinin iki seçenekte farklı fasıllara götürmesidir.",
      "Fasıl 59 Not 6(f)–(g); 59.07 Açıklama Notu; Bölüm XI Not 1(q)."),

    Q(FN,
      "Fasıl 59 Not 2’ye göre plastikle kaplanmış bir mensucatın 59.03’te kalabilmesi için uygulanan bükme testinin koşulları hangisinde doğru verilmiştir?",
      "15–30 °C arasındaki ısıda, çapı 7 mm olan silindir etrafında kırılmadan elle bükülebilmesi",
      ["20–30 °C arasındaki ısıda, çapı 7 mm olan silindir etrafında kırılmadan elle bükülebilmesi",
       "15–30 °C arasındaki ısıda, çapı 10 mm olan silindir etrafında kırılmadan elle bükülebilmesi",
       "15–25 °C arasındaki ısıda, çapı 5 mm olan silindir etrafında kırılmadan elle bükülebilmesi",
       "10–20 °C arasındaki ısıda, çapı 7 mm olan silindir etrafında kırılmadan makineyle bükülebilmesi"],
      "Not 2(a)(2), 15 ile 30 santigrat derece arasındaki ısıda çapı 7 mm olan bir silindir etrafında kırılmadan elle bükülemeyen ürünleri 59.03’ten çıkarır (genellikle Fasıl 39). Sıcaklık aralığı ve çap birlikte ezberlenmelidir; metrekare ağırlığı ise plastik kaplamada ölçüt değildir.",
      "Fasıl 59 Not 2(a)(2); 59.03 Açıklama Notu."),
    Q(FN,
      "Fasıl 59 Not 5’e göre aşağıdakilerden hangisi 59.06 anlamında “kauçuklu mensucat” <b>değildir</b>?",
      "1.700 g/metrekare ağırlığında, ağırlıkça %45 dokumaya elverişli madde içeren kauçuk kaplı mensucat",
      ["1.400 g/metrekare ağırlığında, kauçukla kaplanmış dokunmuş mensucat",
       "1.700 g/metrekare ağırlığında, ağırlıkça %55 dokumaya elverişli madde içeren kauçukla lamine mensucat",
       "Ağırlığı ne olursa olsun, kauçukla aglomere edilmiş paralel ipliklerden oluşan mensucat",
       "56.04’teki kauçuk emdirilmiş ipliklerden yapılmış mensucat"],
      "Metrekare ağırlığı 1.500 g’ı geçen kauçuklu mensucat ancak ağırlıkça %50’den fazla dokumaya elverişli madde içeriyorsa 59.06’dadır; %45 bu şartı sağlamaz ve ürün Fasıl 40’a (40.05 veya 40.08) gider. 1.500 g’ı geçmeyenlerde oran aranmaz; aglomere paralel ipliklerde ağırlık önemsizdir; 56.04 ipliğinden mensucat Not 5(b) ile dahildir.",
      "Fasıl 59 Not 5; 59.06 Açıklama Notu (b)."),
    Q(FN,
      "Fasıl 59 Not 4’e göre rulolar halindeki bir ürünün 59.05’te “dokumaya elverişli maddelerden duvar kaplaması” sayılabilmesi için eninin en az kaç cm olması gerekir?",
      "45 cm", ["30 cm", "40 cm", "50 cm", "60 cm"],
      "Not 4, duvar ve tavan tezyinatına uygun olup eni 45 cm’den az olmayan rulolar halindeki ürünleri duvar kaplaması sayar. 30 cm Fasıl 60’taki dar örme mensucat sınırı, 60 cm ise Fasıl 62’deki mendil sınırıdır; bu sayıların karıştırılması tipik bir tuzaktır.",
      "Fasıl 59 Not 4."),
    Q(FN,
      "Bölüm XI Not 6’ya göre 59.02’deki kord bezinde kullanılan naylon veya diğer poliamidlerden <b>tek kat</b> ipliğin “yüksek mukavemetli” sayılması için mukavemeti hangi değerden fazla olmalıdır?",
      "60 cN/tex", ["53 cN/tex", "27 cN/tex", "45 cN/tex", "70 cN/tex"],
      "Bölüm XI Not 6’ya göre naylon, diğer poliamid veya poliesterden tek kat iplikte sınır 60 cN/tex’tir. 53 cN/tex aynı maddelerin çok katlı (rötor) veya katlı (kable) iplikleri, 27 cN/tex ise viskoz ipeği iplikleri için geçerlidir. Bu şartı sağlamayan iplikten lastik kordu 59.02’ye girmez.",
      "Bölüm XI Not 6; 59.02 Açıklama Notu."),

    Q(GY,
      "Tarife Cetveline göre; sentetik liflerden dokunmuş, içi plastikle kaplanmış, helezon şeklinde metal telle takviye edilmiş ve uçlarına metal rakorlar takılmış yangın söndürme hortumu hangi kurala göre ve hangi pozisyonda sınıflandırılır?",
      "GYK 1 – 59.09", ["GYK 3(b) – 39.17", "GYK 3(b) – 59.09", "GYK 2(b) – 40.09", "GYK 3(c) – 59.03"],
      "59.09’un pozisyon metni hortumları “diğer maddelerden astarı, teçhizatı veya aksesuarı olsun olmasın” kapsar; açıklama notu da plastik iç kaplamalı, metal spiralli ve rakorlu hortumları sayar. Pozisyon metni meseleyi çözdüğünden GYK 1 yeterlidir; esas karakter analizine (GYK 3(b)) gerek yoktur. 40.09 yalnız mensucatla takviyeli vulkanize kauçuk hortumlar içindir.",
      "GYK 1; 59.09 pozisyon metni ve Açıklama Notu."),
    Q(GY,
      "Metrekare ağırlığı 1.800 g olan ve ağırlıkça %40 dokumaya elverişli madde içeren kauçukla kaplanmış bir mensucatın 59.06’da değil Fasıl 40’ta sınıflandırılması hangi kurala dayanır?",
      "GYK 1 – Fasıl 59 Not 5’teki “kauçuklu mensucat” tanımı",
      ["GYK 3(b) – kauçuğun ürüne esas karakterini vermesi",
       "GYK 3(c) – numara sırasına göre en son pozisyonun seçilmesi",
       "GYK 2(b) – karışım ve bileşik maddelere yapılan atıf",
       "GYK 4 – eşyaya en çok benzeyen eşyanın pozisyonu"],
      "Fasıl notları GYK 1 kapsamında bağlayıcıdır: Not 5(a)(ii), 1.500 g’ı geçen kauçuklu mensucatı ancak ağırlıkça %50’den fazla dokumaya elverişli madde içeriyorsa kauçuklu mensucat sayar; şart sağlanmadığından ürün 59.06’ya giremez. GYK 3(c) uygulansaydı numara sırasına göre sonraki 59.06 seçilirdi; bu da sonucun esas karakterle veya sırayla değil, notla belirlendiğini gösterir.",
      "GYK 1; Fasıl 59 Not 5; 59.06 Açıklama Notu (b)."),

    Q(EB,
      "Aşağıdaki eşya – pozisyon eşleştirmelerinden hangisi <b>yanlıştır</b>?",
      "Tıbbi, perakende ambalajlı yapışkan bant – 59.06",
      ["Linoleum – 59.04",
       "Hazır tuval – 59.01",
       "Beyaz alevli lamba gömleği – 59.08",
       "Kauçukla aglomere edilmiş paralel ipliklerden atkısız mensucat – 59.06"],
      "Tıpta, cerrahide, dişçilikte veya veterinerlikte kullanılan, eczacılık ürünleriyle emdirilmiş veya perakende satılacak şekilde hazırlanmış yapışkan bantlar 59.06’dan hariç tutulmuş ve 30.05’e gönderilmiştir. Diğer eşleştirmeler doğrudur; kauçukla aglomere edilmiş paralel ipliklerden mensucat, metrekare ağırlığına bakılmaksızın Not 5(c) ile 59.06’dadır.",
      "59.06 Açıklama Notu (a); Fasıl 59 Not 5(c)."),
    Q(EB,
      "Fasıl 59 Not 2’ye göre emdirme, sıvama veya kaplamanın çıplak gözle görülmediği mensucat genellikle ________ fasıllarda yer alır; bu hükmün uygulanmasında söz konusu işlemler sonucunda ortaya çıkan ________ dikkate alınmaz. Boşluklara sırasıyla hangisi gelmelidir?",
      "50–55, 58 veya 60. / renk değişikliği",
      ["39 veya 40. / renk değişikliği",
       "50–55, 58 veya 60. / ağırlık artışı",
       "56 veya 63. / parlaklık değişimi",
       "39. / kalınlık artışı"],
      "Not 2(a)(1) ve Not 6(a), işlemi çıplak gözle görülmeyen mensucatı “genellikle 50 ila 55, 58 veya 60. fasıllar”a bırakır ve işlem sonucu oluşan renk değişikliğinin dikkate alınmayacağını belirtir. Fasıl 39 ise bükme testini geçemeyen veya iki yüzü tamamen kaplı ürünlerin yeridir.",
      "Fasıl 59 Not 2(a)(1) ve Not 6(a)."),

    Q(CC,
      "Fasıl 59’a göre aşağıdaki ifadelerden hangileri doğrudur? I. 59.03’te mensucatın metrekare ağırlığı ve plastiğin kompakt veya gözenekli oluşu önemsizdir. II. Kauçuk emdirilmiş mensucattan transmisyon kolanları 59.10’da sınıflandırılır. III. Plastik bir yapışkanla basitçe üst üste yapıştırılmış mensucat, 59.03’teki lamine mensucat sayılmaz. IV. İçi yalnızca dokumaya elverişli maddeyle takviye edilmiş vulkanize kauçuk hortum 59.09’dadır.",
      "I ve III", ["I ve II", "II ve IV", "I, III ve IV", "Yalnız III"],
      "I, Not 2(a) metnidir; III, 59.03 Açıklama Notunda açıkça belirtilir (bu mensucat genellikle 50–55. fasıllardadır). II yanlıştır: kauçuklu mensucattan kolanlar Not 7(b) ile 40.10’a gider. IV yanlıştır: mensucat yalnız takviye ise hortum 40.09’dadır.",
      "Fasıl 59 Not 2(a) ve 7(b); 59.03 ve 59.09 Açıklama Notları."),
    Q(CC,
      "Aşağıdakilerden hangileri 59.11 pozisyonunda sınıflandırılır? I. Parça halinde eleklik gaz ve bezler II. Metalle takviye edilmiş keçeler III. Kard garnitürü imalinde kullanılan, kauçukla kaplanmış mensucat IV. Jakard tezgâhlarında kullanılmak üzere belirli uzunlukta kesilmiş, uçları düğümlü veya bağ delikli sicimler",
      "I, III ve IV", ["I ve III", "I, II ve III", "II ve IV", "III ve IV"],
      "Eleklik gazlar ve kard garnitürü mensucatı Not 8(a)’da, jakard tezgâhları için kesilip düğümlenmiş sicimler 59.11 Açıklama Notunun (B) kısmında sayılmıştır. Metalle takviye edilmiş keçeler ise açıklama notunda 59.11’den hariç tutulmuş ve 56.02’ye gönderilmiştir.",
      "Fasıl 59 Not 8; 59.11 Açıklama Notu."),

    Q(SN,
      "Bir firma; poliester dokunmuş mensucatın tek yüzüne, çıplak gözle açıkça görülen ve deriyi taklit edecek şekilde kabartılmış bir poliüretan tabaka uygulatmıştır. Ürün 20 °C’de 7 mm çaplı bir silindir etrafında kırılmadan elle bükülebilmekte, arka yüzü kaplanmamış olup 140 cm eninde top halinde sunulmaktadır. Tarife Cetveline göre bu ürün hangi pozisyonda sınıflandırılır?",
      "59.03", ["39.21", "41.15", "59.07", "59.06"],
      "Kaplama görünür, ürün bükme testini geçiyor ve mensucatın yalnız bir yüzü kaplı; Not 2’deki hariç tutmaların hiçbiri uygulanmadığından ürün plastikle kaplanmış mensucat olarak 59.03’tedir. 59.03 Açıklama Notu deri taklidi kumaşı bu pozisyonun tipik ürünü olarak gösterir. 39.21 plastik levhalar, 41.15 terkip yoluyla elde edilen deri içindir; kaplama plastik olduğundan kauçuklu mensucat (59.06) da söz konusu değildir.",
      "Fasıl 59 Not 2(a); 59.03 Açıklama Notu."),
    Q(SN,
      "Bir ithalatçı; sentetik liflerden dokunmuş, plastikle sıvanmış, belirli uzunlukta kesilip uçları birbirine birleştirilerek nihayetsiz hale getirilmiş, kalınlığı 2 mm olan bir taşıyıcı kolan getirmiştir. Kolan, kullanılacağı makineden ayrı olarak sunulmuştur. Tarife Cetveline göre bu eşya hangi pozisyonda sınıflandırılır?",
      "59.10", ["40.10", "58.06", "59.03", "59.11"],
      "59.10 pozisyon metni plastikle sıvanmış veya kaplanmış kolanları da kapsar. Not 7(a) 3 mm’den ince kolanları hariç tutsa da açıklama notu, belirli uzunlukta kesilip uçları birleştirilmiş veya bağlayıcı unsurlarla donatılmış kolanların kalınlıkları dikkate alınmaksızın 59.10’da sınıflandırılacağını belirtir. Kauçuklu olsaydı 40.10’a, makinesiyle birlikte sunulsaydı makinenin pozisyonuna giderdi.",
      "59.10 pozisyon metni ve Açıklama Notu; Fasıl 59 Not 7."),
]

d = {
    "tur": "fasil",
    "fasil": 59,
    "baslik": "Emdirilmiş, sıvanmış, kaplanmış veya lamine edilmiş dokumaya elverişli maddelerden mensucat, dokumaya elverişli maddelerden teknik eşya",
    "bolum": "XI",
    "oz": {
        "vurgu": "Fasıl 59 iki aileyi toplar: yüzeyi bir maddeyle emdirilmiş, sıvanmış, kaplanmış veya lamine edilmiş mensucat (59.01–59.07) ve teknik işlerde kullanılan dokumaya elverişli eşya (59.08–59.11). Kaplamalı mensucatta üç soru sorulur: kaplayan madde nedir (plastik 59.03, kauçuk 59.06, diğer 59.07), işlem çıplak gözle görülüyor mu ve ürün hâlâ mensucat karakterinde mi, yoksa Fasıl 39 veya 40 malzemesi mi?",
        "maddeler": [
            "Fasıl 59’da “dokumaya elverişli mensucat”: 50–55. fasıllar ile 58.03 ve 58.06’daki dokunmuş mensucat, 58.08’deki parça halinde kordon ve süs eşyası, 60.02–60.06’daki örme mensucat (Not 1).",
            "Plastikle işlem görmüş mensucat 59.03’tür; işlem görünmüyorsa 50–55, 58 veya 60. fasıllarda kalır, 7 mm silindir testini geçemiyorsa ya da plastiğe tamamen gömülmüşse Fasıl 39’a gider.",
            "Kauçuklu mensucat 59.06’dır; metrekare ağırlığı 1.500 g’ı aşan ve ağırlıkça %50 veya daha az dokumaya elverişli madde içeren ürün Fasıl 40’a gider.",
            "Teknik eşya: fitil ve lamba gömleği 59.08, hortum 59.09, kolan 59.10, Not 8’de sayılan teknik ürün ve eşya 59.11.",
            "Kaplanmış mensucattan giysi, çadır gibi hazır eşya Fasıl 59’dan çıkar (Bölüm XI Not 8); hortum, kolan ve 59.11 eşyası ise hazır halde de buradadır.",
        ],
    },
    "karar_tablosu": {
        "aciklama": "Soruları yukarıdan aşağıya sırayla sorun; ilk “evet” cevabı pozisyonu verir.",
        "satirlar": [
            ["1", "Kaplanmış mensucattan giysi, çadır, perde gibi hazır eşya mı? (hortum, kolan, teknik eşya hariç)", "Fasıl <b>61</b> / <b>62</b> / <b>63</b>"],
            ["2", "Yüksek mukavemetli naylon, poliamid, poliester veya viskoz iplikten lastik kord bezi mi?", "<b>59.02</b> (plastik veya kauçuk emdirilmiş olsa bile)"],
            ["3", "Zamk/nişasta sıvalı cilt bezi, mühendis muşambası, hazır tuval veya bukran mı?", "<b>59.01</b> (plastikle sıvanmışsa <b>59.03</b>)"],
            ["4", "Linoleum veya dokumaya elverişli mesnede sıvama yapılarak elde edilmiş yer kaplaması mı?", "<b>59.04</b>"],
            ["5", "Eni en az 45 cm, rulo halinde duvar/tavan kaplaması mı?", "<b>59.05</b> (kağıda tespitli kırpıntı/toz ise <b>48.14</b>)"],
            ["6", "Plastikle emdirilmiş, sıvanmış, kaplanmış veya lamine mi?*", "<b>59.03</b> · görünmüyorsa Fasıl 50–55 / 58 / 60 · testi geçemiyorsa Fasıl <b>39</b>"],
            ["7", "Kauçukla emdirilmiş, sıvanmış, kaplanmış veya lamine mi?", "<b>59.06</b> · 1.500 g/metrekare üstü ve dokuma ≤ %50 ise Fasıl <b>40</b>"],
            ["8", "Katran, mum, yağ, silikat, boya, kırpıntı tozu, mika vb. ile görünür kaplama mı; tiyatro dekoru bezi mi?", "<b>59.07</b>"],
            ["9", "Fitil veya beyaz alevli lamba gömleği mi?", "<b>59.08</b>"],
            ["10", "Tulumba ve benzeri hortum mu?", "<b>59.09</b>"],
            ["11", "Taşıyıcı veya transmisyon kolanı mı?", "<b>59.10</b> (kauçuklu ise <b>40.10</b>)"],
            ["12", "Not 8’de sayılan teknik işlere mahsus ürün veya eşya mı?", "<b>59.11</b>"],
        ],
        "dipnot": "* 59.03 testleri: işlem çıplak gözle görülmeli (renk değişikliği sayılmaz); ürün 15–30 °C’de 7 mm çaplı silindir etrafında kırılmadan elle bükülebilmeli; mensucat plastiğe tamamen batırılmamış ve iki yüzü tamamen sıvanmamış/kaplanmamış olmalı. Plastikle kısmen sıvanıp desen oluşturulmuş mensucat da 59.03 dışıdır.",
    },
    "pozisyon_haritasi": [
        ["59.01", "Zamk/nişasta sıvalı cilt bezi; mühendis muşambası; hazır tuval; bukran", "Zamk veya nişastalı madde; plastikle sıvanmışsa 59.03", "Kitap cilt bezi, ressam tuvali, şapka bukranı"],
        ["59.02", "Lastik kord bezi", "Yüksek mukavemetli naylon, poliamid, poliester veya viskoz iplik", "Otomobil lastiği kord bezi"],
        ["59.03", "Plastikle emdirilmiş, sıvanmış, kaplanmış, lamine mensucat", "Görünür işlem; 7 mm testi; ağırlık önemsiz", "PVC kaplı kumaş, deri taklidi kumaş"],
        ["59.04", "Linoleum; mesnetli yer kaplamaları", "Dokumaya elverişli mesnet + sıvama; kesilmiş olsa da", "Linoleum, mantarlı halı"],
        ["59.05", "Dokumaya elverişli maddelerden duvar kaplamaları", "Rulo, eni ≥ 45 cm; mesnetli veya arkası işlenmiş", "Kumaş yüzlü duvar kaplaması"],
        ["59.06", "Kauçuklu mensucat", "≤ 1.500 g/metrekare; üstündeyse dokuma %50’den fazla", "Kauçuklu yağmurluk kumaşı, yalıtım bandı"],
        ["59.07", "Diğer kaplanmış mensucat; tiyatro dekoru bezleri", "Katran, mum, yağ, silikat, boya, kırpıntı, mika", "Muşamba, mumlu tafta, tiyatro dekoru"],
        ["59.08", "Fitiller; beyaz alevli lamba gömlekleri", "Dokunmuş/örülmüş; mumlu fitil 34.06", "Gaz lambası fitili, lamba gömleği"],
        ["59.09", "Tulumba ve benzeri hortumlar", "Astar, teçhizat, rakor olsa da", "Yangın hortumu"],
        ["59.10", "Taşıyıcı ve transmisyon kolanları", "Kauçuklu ise 40.10; ince parça halinde 50–55/58", "Konveyör kolanı"],
        ["59.11", "Teknik işlerde kullanılan ürün ve eşya (Not 8)", "XI. Bölümde başka yerde yer almama", "Elek bezi, filtre torbası, kağıt makinesi keçesi, conta"],
    ],
    "notlar": [
        ["Bölüm XI Not 1 (h)–(ij)", "Bölüm XI dışı: plastik veya kauçukla emdirilmiş, sıvanmış, kaplanmış veya lamine edilmiş mensucat ve bunlardan eşyanın Fasıl 39’a veya Fasıl 40’a ait olanları. Sınırı Fasıl 59 Not 2 (plastik) ve Not 5 (kauçuk) çizer."],
        ["Bölüm XI Not 6", "“Yüksek mukavemetli iplik”: mukavemeti naylon/diğer poliamid veya poliesterden tek kat iplikte 60 cN/tex’i, bunların çok katlı (rötor) veya katlı (kable) ipliklerinde 53 cN/tex’i, viskoz ipeğinden ipliklerde 27 cN/tex’i aşan iplik. 59.02 kord bezi bu iplikten olmalıdır."],
        ["Bölüm XI Not 7–8", "Hazır eşya: şekilli kesilmiş, bitmiş halde üretilmiş, kenarı bastırılmış veya saçaklı, dikilerek birleştirilmiş, örülerek şekil verilmiş eşya. 56–59. fasıllar, metinde aksi belirtilmedikçe hazır eşyaya uygulanmaz; 50–55 ve 60. fasıllar da 56–59 eşyasına uygulanmaz."],
        ["Fasıl 59 Not 1", "“Dokumaya elverişli mensucat”: 50–55. fasıllar ile 58.03 ve 58.06’daki dokunmuş mensucat, 58.08’deki parça halinde kordonlar ve süs eşyası ve 60.02–60.06’daki örme mensucat."],
        ["Fasıl 59 Not 2 (a)", "59.03’e, metrekare ağırlığı ve plastiğin yapısı (kompakt veya gözenekli) ne olursa olsun plastikle emdirilmiş, sıvanmış, kaplanmış veya lamine mensucat girer. Hariç: (1) işlemin çıplak gözle görülmediği mensucat (renk değişikliği dikkate alınmaz) → genellikle 50–55, 58, 60; (2) 15–30 °C’de 7 mm çaplı silindir etrafında kırılmadan elle bükülemeyenler → genellikle 39; (3) plastiğe tamamen batırılmış veya iki yüzü tamamen sıvanmış/kaplanmış olanlar → 39; (4) kısmen sıvanıp desen oluşturulmuş mensucat → 50–55, 58, 60; (5) mensucatın yalnız mesnet olduğu gözenekli plastik levha, yaprak, şerit → 39; (6) 58.11 ürünleri."],
        ["Fasıl 59 Not 2 (b)", "56.04’teki plastikle emdirilmiş, sıvanmış veya kaplanmış iplik, şerit vb.den yapılmış mensucat da 59.03’tedir."],
        ["Fasıl 59 Not 3", "“Plastikle lamine edilmiş mensucat”: bir veya daha fazla mensucat tabakasının, tabakaları birbirine bağlayan herhangi bir prosesle bir veya daha fazla plastik yaprak veya filmle birleştirilmesi; plastik yaprak enine kesitte çıplak gözle görülsün görülmesin."],
        ["Fasıl 59 Not 4", "59.05 duvar kaplaması: duvar ve tavan tezyinatına uygun, eni 45 cm’den az olmayan rulolar; dokumaya elverişli yüz bir mesnede tespit edilmiş ya da mesnetsizse arka yüzü yapışma için emdirilmiş veya sıvanmış. Kağıda doğrudan tespit edilmiş mensucat kırpıntısı veya tozu → 48.14; mensucat mesnet üzerine → genellikle 59.07."],
        ["Fasıl 59 Not 5", "“Kauçuklu mensucat”: (a) kauçukla emdirilmiş, sıvanmış, kaplanmış veya lamine mensucattan metrekare ağırlığı 1.500 g’ı geçmeyenler veya geçip ağırlıkça %50’den fazla dokumaya elverişli madde içerenler; (b) 56.04’teki kauçuklu iplik vb.den mensucat; (c) ağırlığı ne olursa olsun kauçukla aglomere edilmiş paralel ipliklerden mensucat. Hariç: 58.11 ürünleri ve mensucatın yalnız mesnet olduğu gözenekli kauçuk levha/şerit (Fasıl 40)."],
        ["Fasıl 59 Not 6", "59.07’ye girmez: işlemi görünmeyen mensucat; boyanarak desen verilmiş mensucat (tiyatro dekoru, atölye fonu bezleri hariç); kırpıntı, toz, mantar tozu ile kısmen kaplanıp desenlenmiş mensucat (taklit kadife ve peluş hariç); nişastalı normal apreli mensucat; mensucat mesnetli kaplamalık ağaç (44.08), aşındırıcı (68.05), aglomere mika (68.14), metal varak (Bölüm XIV/XV)."],
        ["Fasıl 59 Not 7", "59.10’a girmez: kalınlığı 3 mm’den az kolanlar; kauçuklu mensucattan veya kauçuklu iplikten mensucattan transmisyon ve taşıyıcı kolanlar (40.10)."],
        ["Fasıl 59 Not 8", "59.11 yalnız XI. Bölümde başka yerde yer almayan şu eşyaya uygulanır: (a) uzunlamasına veya sadece kare/dikdörtgen kesilmiş parça halinde: kard garnitürü mensucatı, eleklik gaz ve bezler, yağ presi filtre/tasir torbaları (insan saçından olanlar dahil), çok katlı atkı-çözgülü teknik düz mensucat, metalle takviyeli teknik mensucat, sanayide yağlama veya ambalaj için ip ve kordonlar; (b) teknik işlerde kullanılan eşya (kağıt makinesi mensucat ve keçeleri, contalar, cila diskleri vb.)."],
        ["59.03 Açıklama Notu", "Yalnız buruşmazlık, güve yemezlik, çekmezlik veya su geçirmezlik için emdirilmiş mensucat (su geçirmez gabardin, poplin) 59.03 dışıdır. Plastik bir yapışkanla basitçe üst üste yapıştırılmış mensucat lamine sayılmaz (genellikle 50–55)."],
        ["59.06 Açıklama Notu", "Katları yalnızca kauçuklu zamkla yapıştırılmış çok katlı mensucat (karoseri, ayakkabı yapımı) 59.06 değil, genellikle 50–55’tir. Mensucat ve yapıştırıcı kauçuktan bantlar (yalıtım şeritleri dahil) 59.06’da; tıbbi, perakende yapışkan bantlar 30.05’te."],
        ["59.09–59.10 Açıklama Notları", "Hortum; plastik/kauçuk iç kaplaması, metal spiral takviyesi veya rakoru olsa da 59.09’dadır; mensucat yalnız takviye olan vulkanize kauçuk hortum 40.09. Belirli uzunlukta kesilip uçları birleştirilmiş veya bağlayıcıyla donatılmış kolanlar kalınlığa bakılmaksızın 59.10’dadır; makinesiyle birlikte sunulan kolan makineyle sınıflandırılır."],
        ["59.11 Açıklama Notu", "Bölüm XVII’ye ait emniyet kemerleri, taşıt gövdeleri için şekil verilmiş kaplama ve izolasyon panelleri (87.08) ile motorlu taşıt halıları (Fasıl 57) 59.11’e girmez. Metalle takviyeli keçeler 56.02’dedir."],
    ],
    "sinir_komsulari": [
        ["Kaplaması görünmeyen su geçirmez gabardin, poplin", "Fasıl 50–55", "Not 2(a)(1), Not 6(a); renk değişikliği sayılmaz"],
        ["İki yüzü tamamen plastikle kaplı veya plastiğe gömülmüş mensucat", "Fasıl 39", "Not 2(a)(3)"],
        ["Mensucatın yalnız mesnet olduğu gözenekli plastik levha", "Fasıl 39", "Not 2(a)(5)"],
        ["1.500 g/metrekare üstü, dokuma oranı %50 veya daha az kauçuklu mensucat", "40.05 / 40.08", "Not 5(a)(ii) şartı sağlanmıyor"],
        ["Kauçuklu mensucattan transmisyon kayışı", "40.10", "Not 7(b)"],
        ["İçi yalnız mensucatla takviyeli vulkanize kauçuk hortum", "40.09", "59.09 Açıklama Notu"],
        ["Kapitoneli mensucat", "58.11", "Not 2(a)(6) ve Not 5"],
        ["Kağıda tespitli kırpıntı/tozla süslenmiş duvar kaplaması", "48.14", "Not 4"],
        ["Plastikten duvar kaplaması", "39.18", "59.05 Açıklama Notu"],
        ["Mumlu fitil; emniyet ve infilak fitili; cam lifinden fitil", "34.06 / 36.03 / 70.19", "59.08 Açıklama Notu"],
        ["Aşındırıcı kaplı mensucat; mensucat mesnetli aglomere mika", "68.05 / 68.14", "Not 6(f)–(g)"],
        ["Alt tabakası mensucat, asfaltla kaplı çatı malzemesi", "68.07", "59.07 Açıklama Notu"],
        ["Metalle takviyeli keçe", "56.02", "59.11 Açıklama Notu"],
        ["Taşıt emniyet kemeri; motorlu taşıt halısı", "87.08 / Fasıl 57", "59.11 Açıklama Notu"],
        ["Plastik kaplı mensucattan yağmurluk", "61.13 / 62.10", "Hazır eşya; Bölüm XI Not 8"],
    ],
    "tuzaklar": [
        "<b>Görünmeyen kaplama 59’a sokmaz.</b> Buruşmazlık, güve yemezlik veya su geçirmezlik için emdirilmiş gabardin ve poplinler, işlem çıplak gözle görülmüyorsa Fasıl 50–55, 58 veya 60’ta kalır; işlemden doğan renk değişikliği “görünürlük” sayılmaz.",
        "<b>7 mm silindir testi.</b> 15–30 °C’de 7 mm çaplı silindir etrafında kırılmadan elle bükülemeyen plastik kaplı ürün 59.03 değil, genellikle Fasıl 39’dur.",
        "<b>Ağırlık plastikte önemsiz, kauçukta önemli.</b> 59.03’te metrekare ağırlığı ve plastiğin kompakt/gözenekli oluşu önemsizdir; 59.06’da 1.500 g ve %50 dokuma eşiği vardır.",
        "<b>Yapıştırmak laminasyon değildir.</b> Plastik yapışkanla basitçe üst üste yapıştırılmış mensucat 59.03 sayılmaz; katları yalnız kauçuklu zamkla yapıştırılmış çok katlı mensucat da 59.06 değildir (ikisi de genellikle 50–55).",
        "<b>Kord bezi önce gelir.</b> Yüksek mukavemetli naylon, poliester veya viskoz iplikten lastik kord bezi plastik veya kauçuk emdirilmiş olsa bile 59.02’dedir; mukavemet şartını taşımayan kord bezi 54. fasıl, 59.03 veya 59.06’ya gider.",
        "<b>Hortumun teçhizatı pozisyonu değiştirmez.</b> İçi kauçuk veya plastik kaplı, metal spiralli, rakorlu tekstil hortum 59.09; mensucat yalnız takviye olan vulkanize kauçuk hortum 40.09.",
        "<b>Kolan: 3 mm ve kauçuk.</b> 3 mm’den ince kolanlık mensucat 59.10 dışıdır (58.06 kordela, 58.08 kordon vb.); ama uçları birleştirilmiş veya bağlayıcıyla donatılmış kolanlarda kalınlık aranmaz. Kauçuklu mensucattan kolan her durumda 40.10.",
        "<b>Mika iki yere gider.</b> Mika tozuyla kaplanmış mensucat 59.07; mensucat mesnetli aglomere mika 68.14.",
        "<b>Tiyatro dekoru 59.07, hazır tuval 59.01.</b> Boyanarak desen verilmiş mensucat 59.07’ye girmez; tiyatro dekoru ve atölye fonu bezleri bu kuralın istisnasıdır.",
        "<b>Hazır eşya fasıldan çıkar, teknik eşya çıkmaz.</b> Kaplanmış mensucattan giysi 61.13 / 62.10, çadır 63.06; buna karşılık hortum, kolan ve 59.11 teknik eşyası hazır halde de Fasıl 59’dadır.",
    ],
    "hafiza": {
        "kanca": "KİTAP – KORD – PLASTİK – LİNO – DUVAR – KAUÇUK – DİĞER  /  FİTİL – HORTUM – KOLAN – TEKNİK",
        "aciklama": "İlk yedi pozisyon yüzey işlemidir (59.01–59.07), son dördü teknik eşyadır (59.08–59.11). Cümleyle: “<b>Kitabı kord</b>la bağladım, <b>plastik lino</b>leumu <b>duvar</b>a <b>kauçuk</b>la yapıştırdım, <b>diğer</b>lerini boyadım; sonra <b>fitil</b>i yaktım, <b>hortum</b>u <b>kolan</b>a bağladım, kalanını <b>teknik</b> servise verdim.”",
    },
    "sinav_odagi": [
        "Bu fasıl çıkmış sorularda daha çok seçeneklerde ve çeldirici olarak yer almıştır; doğrudan Fasıl 59’u soran soru sayısı azdır.",
        "Sentetik liften yangın hortumunun 59.09’da olduğu sorulmuş; çeldiriciler 39.17 (plastik hortum), 58.11 (kapitoneli mensucat) ve 63.06 (çadır, tente) olmuştur.",
        "“Hangisi 84.83’te değildir?” kalıbında transmisyon kolanı doğru cevap olarak kullanılmıştır: dokumaya elverişli kolan 59.10’da, kauçuklu mensucattan kolan 40.10’dadır.",
        "Terkip yoluyla elde edilen deri sorusunda 59.03 çeldirici olarak verilmiştir: plastikle kaplanmış deri taklidi kumaş 59.03, terkip deri 41.15.",
        "“Gezici hayvan sergileriyle aynı fasılda olan eşya” sorusunda tiyatro dekoru yanlış seçenek olmuştur; tiyatro dekoru bezleri 59.07’dedir.",
        "Ortak kalıp: malzeme fasılları (39, 40, 68) ile Fasıl 59 arasındaki sınır ve tekstil kökenli teknik eşyanın makine aksamıyla karıştırılması.",
    ],
    "cikmis_ornekler": [
        {
            "soru": "Dokumaya elverişli maddelerden; sentetik liflerden yangın hortumları Tarife Cetvelinde hangi tarife pozisyonunda sınıflandırılır?",
            "secenekler": ["58.11", "39.17", "63.06", "59.09"],
            "cevap": "D",
            "aciklama": "59.09, dokumaya elverişli maddelerden tulumba ve benzeri hortumları astarı, teçhizatı veya aksesuarı olsun olmasın kapsar; açıklama notu yangın söndürme hortumlarını örnek verir. 39.17 plastikten hortum, 58.11 kapitoneli mensucat, 63.06 çadır ve tente pozisyonudur.",
        },
        {
            "soru": "Aşağıdakilerden hangisi 84.83 tarife pozisyonunda sınıflandırılan eşyalardan değildir?",
            "secenekler": ["Krank mili", "Kavrama", "Transmisyon kolanı", "Yatak kovanı", "Kaplin"],
            "cevap": "C",
            "aciklama": "Dokumaya elverişli maddelerden taşıyıcı ve transmisyon kolanları 59.10’da, kauçuklu mensucattan olanlar 40.10’da sınıflandırılır (Fasıl 59 Not 7). Kolan bu nedenle makine aksamı pozisyonuna girmez.",
        },
    ],
    "ozet": [
        "Fasıl 59 = kaplanmış mensucat (59.01–59.07) + teknik tekstil eşyası (59.08–59.11).",
        "Plastik: görünür işlem + 7 mm testi + iki yüz tamamen kaplı değil → 59.03; aksi halde 50–55 / 58 / 60 veya Fasıl 39.",
        "Kauçuk: 1.500 g/metrekare ve %50 dokuma eşiği → 59.06 ya da Fasıl 40.",
        "Kord bezi yüksek mukavemetli iplikten → 59.02; plastik veya kauçuk emdirilmiş olsa da.",
        "Hortum 59.09 (rakor, astar fark etmez); kolan 59.10 (kauçuklu ise 40.10).",
        "59.11 bir artık pozisyon değil, Not 8’de sayılan teknik eşyanın pozisyonudur.",
        "Kaplanmış mensucattan hazır eşya (giysi, çadır) Fasıl 61–63’e gider.",
    ],
    "sorular": kur(sorular, 5901),
}

yaz(d, 59)
