from yardim_59_63 import Q, kur, yaz

E4 = "Eşya → 4’lü pozisyon"
OT = "Olumsuz teşhis"
FA = "Farklı/aynı pozisyon veya fasıl"
FN = "Fasıl notu · Tanım/Eşik"
GY = "Genel Yorum Kuralı"
EB = "Eşleştirme / Boşluk doldurma"
CC = "Çoktan-çoğa (I–IV)"
SN = "Senaryo"

sorular = [
    Q(E4,
      "Tarife Cetveline göre, örülmemiş ipek mensucattan, kare şeklinde, kenarları 70 cm olan, kenarları kıvrılarak bastırılmış ve boyna sarılarak kullanılan fular hangi pozisyonda sınıflandırılır?",
      "62.14", ["62.13", "62.17", "61.17", "62.15"],
      "Fasıl 62 Not 8’e göre fular ve fular tipi eşya ancak kare veya karemsi olup hiçbir kenarı 60 cm’yi aşmıyorsa 62.13’te mendil sayılır. Kenarları 70 cm olduğundan 62.13 dışında kalır ve şal, eşarp ve fularların pozisyonu olan 62.14’e girer. Örme olsaydı 61.17 söz konusu olurdu.",
      "Fasıl 62 Not 8; 62.13 ve 62.14 Açıklama Notları."),
    Q(E4,
      "Tarife Cetveline göre, sentetik liflerden dokunmamış mensucattan (56.03) dikilerek hazırlanmış, cerrahların ameliyat sırasında giydiği koruyucu önlük hangi pozisyonda sınıflandırılır?",
      "62.10", ["62.11", "63.07", "48.18", "56.03"],
      "62.10, 56.02, 56.03, 59.03, 59.06 veya 59.07 türü mensucattan hazır giyim eşyasını kapsar ve Not 6 gereği 62.09 dışındaki diğer pozisyonlara üstün gelir; koruyucu giysi olarak 62.11’e de uyması sonucu değiştirmez. Kâğıt veya selüloz vatkadan olsaydı 48.18’e giderdi; hazır eşya olduğu için 56.03’te kalmaz.",
      "Fasıl 62 Not 6; 62.10 pozisyon metni ve Açıklama Notu."),
    Q(E4,
      "Tarife Cetveline göre, örülmemiş pamuklu mensucattan dikilmiş erkek fanilası hangi pozisyonda sınıflandırılır?",
      "62.07", ["61.09", "62.05", "62.11", "62.08"],
      "62.07, erkekler ve erkek çocuklar için örülmemiş fanila, atlet, külot, slip, pijama ve bornozları kapsar. Örme fanila cinsiyetsiz olarak 61.09’da olurdu; Fasıl 62’de ise fanila cinsiyete göre 62.07 (erkek) veya 62.08 (kadın) pozisyonuna ayrılır. 62.05 gömlek pozisyonudur.",
      "62.07 pozisyon metni ve Açıklama Notu."),
    Q(E4,
      "Tarife Cetveline göre, kalın pamuklu dokunmuş mensucattan dikilmiş, sanayide el koruyucu olarak kullanılan türden iş eldiveni hangi pozisyonda sınıflandırılır?",
      "62.16", ["62.11", "61.16", "40.15", "63.07"],
      "62.16, örme olanlar dışındaki her tür mensucattan eldivenleri kapsar ve açıklama notu sanayide koruyucu olarak kullanılan türden eldivenleri açıkça bu pozisyona alır. Örme eldiven 61.16’da, kauçuktan eldiven 40.15’tedir; iş eşyası niteliği 62.11 veya 63.07’ye götürmez.",
      "62.16 Açıklama Notu."),
    Q(E4,
      "Tarife Cetveline göre, örülmüş elastik mensucattan yapılmış, plastik mesnetlerle desteklenmiş ve kopçalarla tutturulan kadın korse kemeri hangi pozisyonda sınıflandırılır?",
      "62.12", ["61.17", "61.08", "90.21", "40.15"],
      "62.12, sütyen, korse, korse kemeri, pantolon askısı, jartiyer ve benzerlerini örülmüş olsun olmasın kapsar; Fasıl 61 Not 2(a) bunları örme fasıldan çıkarır. Ortopedik cihaz niteliğinde olmadığından 90.21, tamamen kauçuktan olmadığından 40.15 uygulanmaz.",
      "62.12 pozisyon metni ve Açıklama Notu; Fasıl 61 Not 2(a)."),

    Q(OT,
      "Aşağıdakilerden hangisi 62.17 pozisyonunda <b>sınıflandırılmaz</b>?",
      "Kayarak işleyen fermuar",
      ["Dokunmuş mensucattan gemici yakası",
       "Kıymetli metal tokalı, dokunmuş kemer",
       "Danteladan yapılmış soket",
       "Yağmurluk için ayrı sunulan, takılıp çıkarılabilen astar"],
      "62.17 Açıklama Notu kayarak işleyen fermuarları hariç tutar ve 96.07’ye gönderir. Gemici yakası, kemer (kıymetli metal tokalı olsa da), danteladan soket ve yağmurluk için ayrı sunulan astar açıklama notunda bu pozisyona dahil eşya olarak sayılmıştır.",
      "62.17 Açıklama Notu."),
    Q(OT,
      "Aşağıdakilerden hangisi 62.10 pozisyonunda <b>yer almaz</b>?",
      "Selüloz vatkadan yapılmış tek kullanımlık önlük",
      ["Keçeden dikilmiş erkek yeleği",
       "Kauçuklu mensucattan (59.06) yağmurluk",
       "Plastikle kaplanmış mensucattan (59.03) dalgıç elbisesi",
       "Dokunmamış mensucattan radyasyona karşı koruyucu giysi"],
      "62.10 Açıklama Notu kâğıttan, selüloz vatkadan veya selüloz liflerinden tülbentten giyim eşyasını hariç tutar ve 48.18’e gönderir. Keçe (56.02) ve dokunmamış mensucat (56.03) ile 59.03 ve 59.06 türü mensucattan yapılmış giysiler 62.10’dadır.",
      "62.10 pozisyon metni ve Açıklama Notu (a)."),
    Q(OT,
      "Aşağıdakilerden hangisi Tarife Cetvelinin 62. faslında <b>sınıflandırılmaz</b>?",
      "Örülmüş pamuklu mendil",
      ["Örülmüş sütyen", "Dokunmuş ipek kravat", "Dokunmuş pamuklu bebek elbisesi", "Dokunmuş mensucattan dini cüppe"],
      "Fasıl 62 Not 1 örülmüş eşyayı (62.12 dışındakileri) kapsam dışı bırakır; örme mendil 61.17 Açıklama Notunda sayılmıştır. Örülmüş sütyen 62.12’nin “örülmüş olsun olmasın” ifadesiyle Fasıl 62’dedir; kravat 62.15, bebek elbisesi 62.09, dini cüppe 62.11’dedir.",
      "Fasıl 62 Not 1; 61.17 Açıklama Notu; 62.11 Açıklama Notu."),
    Q(OT,
      "Aşağıdakilerden hangisi 62.14 pozisyonunda <b>yer almaz</b>?",
      "Askeri üniforma eşarbı",
      ["Gelin duvağı", "Dikdörtgen şeklinde dokunmuş eşarp", "Kenarlarından biri 75 cm olan kare şal", "Danteladan kaşkol"],
      "62.14 Açıklama Notu, askeri veya dini üniforma eşarplarını hariç tutar ve 62.17’ye gönderir. Duvak, dikdörtgen eşarp, kenarı 60 cm’yi aşan kare şal ve kaşkol açıklama notunda bu pozisyonun eşyası olarak sayılmıştır.",
      "62.14 Açıklama Notu; Fasıl 62 Not 8."),

    Q(FA,
      "Aşağıdaki örülmemiş eşyadan hangisi diğerlerinden farklı bir pozisyonda sınıflandırılır?",
      "Kadın bluzu",
      ["Kadın sabahlığı", "Kadın geceliği", "Kadın kombinezonu", "Kadın fanilası"],
      "Örülmemiş kadın fanilası, kombinezonu, geceliği ve sabahlığı 62.08’de toplanır; örmede 61.09’a giden fanila Fasıl 62’de 62.08’dedir. Bluz ise bluz, gömlek ve gömlek-bluz pozisyonu olan 62.06’dadır.",
      "62.06 ve 62.08 pozisyon metinleri ve Açıklama Notları."),
    Q(FA,
      "Aşağıdakilerden hangisi diğerlerinden farklı bir fasılda yer alır?",
      "Dokunmuş masa örtüsü",
      ["Dokunmuş eldiven", "Dokunmuş kravat", "Dokunmuş mendil", "Dokunmuş şal"],
      "Masa örtüsü bir giyim aksesuarı değil, dokumaya elverişli maddelerden diğer hazır eşyadır ve 63.02’dedir. Dokunmuş eldiven 62.16, kravat 62.15, mendil 62.13, şal 62.14 ile Fasıl 62’nin aksesuar pozisyonlarındadır.",
      "62.13–62.16 pozisyon metinleri; 63.02 Açıklama Notu."),
    Q(FA,
      "Aşağıdaki eşya çiftlerinden hangisinde her iki eşya da <b>aynı</b> pozisyonda sınıflandırılır?",
      "Dokunmuş sütyen – örme sütyen",
      ["Dokunmuş erkek fanilası – örme erkek fanilası",
       "Dokunmuş eldiven – örme eldiven",
       "Kenarı 50 cm kare dokunmuş fular – kenarı 65 cm kare dokunmuş fular",
       "Dokunmuş kravat – örme kravat"],
      "62.12, sütyenleri örülmüş olsun olmasın kapsadığından iki sütyen de 62.12’dedir. Diğer çiftlerde örme/dokunmuş ayrımı veya 60 cm kuralı pozisyonu böler: fanila 62.07 – 61.09; eldiven 62.16 – 61.16; fular 62.13 – 62.14; kravat 62.15 – 61.17.",
      "62.12 pozisyon metni; Fasıl 62 Not 1 ve 8."),
    Q(FA,
      "Aşağıdaki örülmemiş giysilerden hangisi diğerlerinden farklı bir pozisyonda sınıflandırılır?",
      "Erkek pijaması",
      ["Erkek eşofmanı (spor kıyafeti)", "Kayak tulumu", "Kadın mayosu", "Pamuklu dokunmuş cerrah önlüğü"],
      "Spor, kayak ve yüzme kıyafetleri ile önlük, iş kıyafeti gibi diğer giysiler 62.11’dedir; 62.11 Açıklama Notu 61.12 ve 61.14 açıklamalarını gerekli değişikliklerle bu pozisyona uygular. Erkek pijaması ise 62.07’dedir.",
      "62.07 ve 62.11 pozisyon metinleri ve Açıklama Notları."),

    Q(FN,
      "Fasıl 62 Not 8’e göre bir fuların 62.13 pozisyonunda mendil olarak sınıflandırılabilmesi için hangi şart aranır?",
      "Kare veya karemsi olması ve hiçbir kenarının 60 cm’yi aşmaması",
      ["Kare olması ve alanının 0,36 metrekareyi aşmaması",
       "Kare veya dikdörtgen olması ve en az bir kenarının 60 cm’yi aşmaması",
       "Kare veya karemsi olması ve hiçbir kenarının 50 cm’yi aşmaması",
       "Saçaklar hariç ölçülen kenarlarının 60 cm’yi aşmaması"],
      "Not 8, fular ve fular tipi eşyanın kare veya karemsi olmasını ve hiçbir kenarının 60 cm’yi aşmamasını arar; bu durumda eşya 62.13’te mendildir. 62.13 Açıklama Notuna göre saçaklı eşyanın kenarları ölçülürken saçaklar da hesaba katılır; ölçüt alan değil kenar uzunluğudur.",
      "Fasıl 62 Not 8; 62.13 Açıklama Notu."),
    Q(FN,
      "Fasıl 62 Not 1 ve Genel Açıklamalarına göre aşağıdakilerden hangisi doğrudur?",
      "Fasıl, 62.12 hariç örülmüş eşya dışında, vatka dışındaki her nevi mensucattan hazır eşyaya uygulanır.",
      ["Fasıl yalnızca dokunmuş mensucattan giysileri kapsar; keçeden giysiler Fasıl 63’tedir.",
       "Fasıl, vatkadan yapılmış hazır giysileri de kapsar.",
       "Örülmüş sütyenler Fasıl 61’de, örülmemiş sütyenler 62.12’de sınıflandırılır.",
       "Fasıl, parça halindeki dokunmuş mensucatı da kapsar."],
      "Not 1, Fasıl 62’yi vatka dışında her nevi dokumaya elverişli mensucattan hazır eşyaya uygular ve örülmüş eşyayı (62.12 dışındakiler) kapsam dışı bırakır; Genel Açıklamalar keçe ve dokunmamış mensucatı açıkça dahil eder. Sütyenler örülmüş olsun olmasın 62.12’dedir; parça halindeki mensucat hazır eşya olmadığından bu faslın konusu değildir.",
      "Fasıl 62 Not 1; Genel Açıklamalar."),
    Q(FN,
      "Fasıl 62 Not 3(a)’ya göre kadınlar için takım elbisede vücudun alt kısmını kapamaya mahsus birden fazla parça (etek ve pantolon gibi) birlikte sunulduğunda hangisi alt parça olarak dikkate alınır?",
      "Etek veya pantolon etek",
      ["Pantolon", "Ağırlığı daha fazla olan parça", "Pozisyon numarası sırasına göre sonra gelen parça", "Her ikisi; takım dört parçalı sayılır"],
      "Not 3(a), birden çok alt parça birlikte sunulduğunda erkek takımlarında pantolonun, kadın veya kız çocuk takımlarında etek veya pantolon eteğin alt parça olarak dikkate alınacağını, diğer giysilerin ayrı ayrı değerlendirileceğini belirtir. Takım elbise iki veya üç parçadan oluşur; dört parçalı takım elbise yoktur.",
      "Fasıl 62 Not 3(a); 61.04 Açıklama Notu."),
    Q(FN,
      "Fasıl 62 Not 5 ve 6’ya göre aşağıdakilerden hangisi <b>yanlıştır</b>?",
      "Keçeden bebek tulumu, 62.10’un önceliği nedeniyle 62.10’da sınıflandırılır.",
      ["Bebek giyim eşyası, boyu 86 cm’yi geçmeyen küçük çocuklara mahsus eşyadır.",
       "İlk bakışta hem 62.09 hem diğer pozisyonlara girebilen eşya 62.09’dadır.",
       "İlk bakışta hem 62.10 hem 62.09 dışındaki pozisyonlara girebilen giysi 62.10’dadır.",
       "Bebek bezleri 62.09’da değil 96.19’da sınıflandırılır."],
      "Not 6, 62.10’a yalnız 62.09 dışındaki pozisyonlara karşı öncelik verir; Not 5(b) ise 62.09’u diğer bütün pozisyonların önüne koyar. 62.10 Açıklama Notu da 62.09’daki bebek giysilerini hariç tuttuğundan keçeden bebek tulumu 62.09’dadır. Bebek bezlerinin 96.19’a gittiği 62.09 Açıklama Notunda belirtilmiştir.",
      "Fasıl 62 Not 5 ve 6; 62.09 ve 62.10 Açıklama Notları."),

    Q(GY,
      "Perakende satış için tek bir ambalajda sunulan; pamuklu dokunmuş bir kadın bluzu ile farklı kumaştan, yünlü dokunmuş bir kadın eteği nasıl sınıflandırılır?",
      "Ayrı ayrı: bluz 62.06, etek 62.04 – GYK 1 (Bölüm XI Not 14)",
      ["Takım olarak 62.04 – GYK 1 (Fasıl 62 Not 3(b))",
       "GYK 3(b): esas karakteri veren eteğin pozisyonunda, 62.04",
       "GYK 3(c): numara sırasına göre sonuncu olan 62.06",
       "GYK 3(b): bluzun pozisyonunda, 62.06"],
      "Not 3(b)’deki “takım” için tüm parçaların aynı mensucattan olması gerekir; kumaşlar farklı olduğundan set takım sayılmaz. Bölüm XI Not 14 gereği değişik pozisyonlardaki giysiler perakende satışa hazır olsa bile kendi pozisyonlarında sınıflandırılır; bölüm notu uygulandığından dayanak GYK 1’dir, GYK 3 kurallarına başvurulmaz.",
      "GYK 1; Bölüm XI Not 14; Fasıl 62 Not 3(b); Genel Açıklamalar."),
    Q(GY,
      "Bir erkek gömleğinin tüm parçaları (ön, arka, kollar, yaka, manşetler) dokunmuş kumaştan belirli bir şekle göre kesilmiş ve henüz birleştirilmeden birlikte sunulmuştur. Bu eşya hangi pozisyonda ve hangi kurala göre sınıflandırılır?",
      "62.05 – GYK 2(a)",
      ["63.08 – GYK 1", "63.07 – GYK 1", "62.17 – GYK 1", "62.05 – GYK 3(b)"],
      "GYK 2(a), birleştirilmemiş halde sunulan eşyayı, bitmiş eşyanın esas karakterine sahipse bitmiş eşya olarak sınıflandırır; Fasıl 62 Genel Açıklamaları da bu eşyanın imali için şekil verilmiş mensucatı mamul eşyanın pozisyonuna gönderir. 63.08 Açıklama Notu giyim eşyası yapmak üzere takım halindeki mensucatı hariç tutar; 62.17 tek tek sunulan giysi parçaları içindir.",
      "GYK 2(a); Fasıl 62 Genel Açıklamalar; 63.08 Açıklama Notu."),

    Q(EB,
      "Aşağıdaki örülmemiş eşya – pozisyon eşleştirmelerinden hangisi <b>yanlıştır</b>?",
      "Erkekler için kolsuz gömlek – 62.05",
      ["Smokin – 62.03", "Kadın pantolon eteği – 62.04", "Erkek robdöşambrı – 62.07", "Kadın lizözü – 62.08"],
      "Fasıl 62 Not 4, 62.05’in kolsuz giysileri kapsamadığını açıkça belirtir; kolsuz erkek giysisi bu nedenle 62.05 dışında kalır. Smokin Not 3(a) gereği takım elbise olarak 62.03’te, pantolon etek 62.04’te, robdöşambr 62.07’de, lizöz 62.08’dedir.",
      "Fasıl 62 Not 3(a) ve Not 4; 62.03, 62.04, 62.07, 62.08 pozisyon metinleri."),
    Q(EB,
      "62.10 pozisyonu; ________, ________, 59.03, 59.06 veya 59.07 pozisyonlarındaki mensucattan hazır giyim eşyasını kapsar. Boşluklara sırasıyla hangisi gelmelidir?",
      "56.02 / 56.03",
      ["56.01 / 56.02", "58.11 / 56.03", "56.03 / 58.04", "48.18 / 56.02"],
      "62.10 metni 56.02 (keçe), 56.03 (dokunmamış mensucat), 59.03, 59.06 ve 59.07’deki mensucattan hazır giysileri sayar. 56.01 vatkadır ve Not 1 gereği Fasıl 62 dışındadır; 58.11 kapitoneli mensucattan giysiler genellikle 62.01 / 62.02’ye, kâğıt ve selüloz vatkadan giysiler 48.18’e gider.",
      "62.10 pozisyon metni ve Açıklama Notu; Fasıl 62 Not 1."),

    Q(CC,
      "Fasıl 62’ye göre aşağıdaki ifadelerden hangileri doğrudur? I. Örülmemiş fanila ve atletler cinsiyete göre 62.07 veya 62.08’de sınıflandırılır. II. Örülmemiş kısa ve uzun konçlu çoraplar 62.17’de sınıflandırılır. III. Sanayide koruyucu olarak kullanılan dokunmuş eldivenler 62.16 dışında kalır. IV. Elektrikle ısıtılan giyim eşyası Fasıl 62 dışında kalır.",
      "I ve II", ["I ve III", "II ve IV", "I, II ve III", "III ve IV"],
      "I, 62.07 ve 62.08 metinlerinden; II, 62.17 Açıklama Notundan (ve 61.15’in örülmemiş çorapları 62.17’ye göndermesinden) doğrudur. III yanlıştır: sanayi koruyucu eldivenleri 62.16 Açıklama Notunda açıkça dahildir. IV yanlıştır: Genel Açıklamalar elektrikle ısıtılan giysilerin bu fasılda kaldığını söyler.",
      "62.07, 62.08, 62.16, 62.17 Açıklama Notları; Genel Açıklamalar."),
    Q(CC,
      "62.13 pozisyonu ile ilgili aşağıdaki ifadelerden hangileri doğrudur? I. Saçaklı mendillerin kenar ölçümünde saçaklar da hesaba katılır. II. Tamamen danteladan yapılmış mendiller bu pozisyonda yer alabilir. III. Selüloz vatkadan yapılmış mendiller bu pozisyondadır. IV. Belirlenmiş çizgiler boyunca basitçe kesilerek mendile dönüştürülebilen, birkaç kareden oluşan parça halindeki mensucat bu pozisyondadır.",
      "I, II ve IV", ["I ve II", "II ve III", "I, III ve IV", "Yalnız IV"],
      "62.13 Açıklama Notu saçakların ölçüye katılacağını, mendillerin tamamen danteladan olabileceğini ve belirlenmiş çizgiler boyunca kesilerek ayrı mendillere dönüştürülebilen parça halindeki mensucatın bu pozisyonda yer aldığını belirtir. Kâğıttan, selüloz vatkadan veya selüloz lifli tülbentten mendiller ise 48.18’dedir.",
      "62.13 Açıklama Notu; Fasıl 62 Not 8."),

    Q(SN,
      "Kadınlar için; dış yüzü poliamid dokunmuş kumaştan, içi elyafla doldurulup kapitone yapılmış 58.11 türü parça halindeki kapitoneli mensucattan dikilmiş, kapşonlu, önü fermuarlı, kalçayı örten bir anorak ithal edilmiştir. Dış kumaş, kendi başına 59.03 pozisyonuna girecek şekilde plastikle kaplanmıştır. Tarife Cetveline göre bu eşya hangi pozisyonda sınıflandırılır?",
      "62.02", ["62.10", "62.04", "62.11", "58.11"],
      "Fasıl 62 Altpozisyon Açıklama Notu ve 62.10 Açıklama Notu, 58.11 kapitoneli mensucattan giysilerin dış kumaşı kendi başına 59.03, 59.06 veya 59.07’de yer alsa bile 62.10’a girmeyeceğini, genellikle 62.01 veya 62.02’de sınıflandırılacağını belirtir. Anorak kadınlar için olduğundan 62.02’dedir; hazır eşya olduğundan 58.11’de kalmaz.",
      "62.10 Açıklama Notu (b); Fasıl 62 Altpozisyon Açıklama Notu."),
    Q(SN,
      "Erkekler için dokunmuş yünlü kumaştan; önü soldan sağa kapanan, kalçanın yarısını geçmeyen, kollar hariç dış yüzü dört parçadan oluşan bir ceket ile aynı kumaştan ve uygun ölçüde askısız bir pantolon ve bir şort birlikte sunulmuştur. Fasıl 62 Not 3(a)’ya göre bu eşya nasıl değerlendirilir?",
      "Ceket ve pantolon takım elbise sayılır; şort ayrıca değerlendirilir.",
      ["Ceket, pantolon ve şort birlikte üç parçalı takım elbise sayılır.",
       "Ceket ve şort takım elbise sayılır; pantolon ayrıca değerlendirilir.",
       "Birden fazla alt parça bulunduğundan takım elbise sayılmaz; üçü de 62.11’dedir.",
       "GYK 3(b) uyarınca üç parça, ceketin esas karakteriyle 62.01’de sınıflandırılır."],
      "Not 3(a)’ya göre vücudun alt kısmını kapamaya mahsus birden fazla parça (pantolon ve şort gibi) birlikte sunulduğunda erkek takımlarında alt parça olarak pantolon dikkate alınır, diğer giysiler ayrı ayrı değerlendirilir. Takım elbisenin üçüncü parçası ancak takım kumaşından dikilmiş yelek olabilir; şort olamaz.",
      "Fasıl 62 Not 3(a); 61.03 Açıklama Notu (A)."),
]

d = {
    "tur": "fasil",
    "fasil": 62,
    "baslik": "Örülmemiş giyim eşyası ve aksesuarı",
    "bolum": "XI",
    "oz": {
        "vurgu": "Fasıl 62, örülmemiş her tür mensucattan (dokunmuş, keçe, dokunmamış, dantela vb.; vatka hariç) hazır giyim eşyası ve aksesuarını kapsar. Örme olanlar Fasıl 61’e gider; tek istisna 62.12’dir (sütyen, korse vb. örülmüş olsun olmasın burada). Öncelik sırası: bebek 62.09, sonra keçe/dokunmamış/kaplanmış mensucattan giysi 62.10, sonra diğer pozisyonlar.",
        "maddeler": [
            "Fasıl 61’in ayna görüntüsüdür: 62.01–62.08 erkek/kadın çiftleri, 62.09 bebek, 62.10 özel mensucattan giysi, 62.11 spor-kayak-yüzme ve diğer giysi, 62.12–62.17 aksesuar.",
            "Örülmemiş fanila, atlet ve kaşkorse cinsiyete göre 62.07 / 62.08’dedir (örme ise 61.09).",
            "Kare veya karemsi, hiçbir kenarı 60 cm’yi aşmayan fular 62.13’te mendildir; daha büyük kare veya kare olmayan şal ve eşarp 62.14 (Not 8).",
            "62.10: 56.02, 56.03, 59.03, 59.06, 59.07 mensucattan giysi; 62.09 hariç tüm pozisyonlara üstün gelir (Not 6).",
            "Örülmemiş çorap 62.17’de; ayrı sunulan dikilmiş yelek 62.11’de (örmede 61.10).",
        ],
    },
    "karar_tablosu": {
        "aciklama": "Soruları yukarıdan aşağıya sırayla sorun; ilk “evet” cevabı pozisyonu verir.",
        "satirlar": [
            ["1", "Sütyen, korse, korse kemeri, pantolon askısı, jartiyer mi?", "<b>62.12</b> (örülmüş olsun olmasın)"],
            ["2", "Örme mi?", "Fasıl <b>61</b>"],
            ["3", "Kâğıt, selüloz vatka veya selüloz lifli tülbentten mi?", "<b>48.18</b>"],
            ["4", "Fazlaca kullanılmış ve dökme/balya halinde mi?", "<b>63.09</b>"],
            ["5", "Boyu 86 cm’yi geçmeyen küçük çocuk için mi?", "<b>62.09</b>"],
            ["6", "Keçe (56.02), dokunmamış (56.03) veya 59.03/59.06/59.07 mensucattan giysi mi?*", "<b>62.10</b>"],
            ["7", "Spor, kayak, yüzme kıyafeti; iş önlüğü, cüppe; ayrı sunulan yelek mi?", "<b>62.11</b>"],
            ["8", "Palto-anorak / takım-ceket-pantolon-elbise-etek / gömlek-bluz / iç giyim-pijama?", "Erkek <b>62.01</b> / <b>62.03</b> / <b>62.05</b> / <b>62.07</b> · Kadın <b>62.02</b> / <b>62.04</b> / <b>62.06</b> / <b>62.08</b>"],
            ["9", "Mendil (kare/karemsi, kenarlar ≤ 60 cm) mi? · Şal, eşarp, peçe, duvak mı?", "<b>62.13</b> · <b>62.14</b>"],
            ["10", "Kravat, papyon mu? · Eldiven mi?", "<b>62.15</b> · <b>62.16</b>"],
            ["11", "Diğer aksesuar, çorap, kemer, giysi parçası mı?", "<b>62.17</b>"],
        ],
        "dipnot": "* 58.11 kapitoneli mensucattan giysi, dış kumaşı kendi başına 59.03, 59.06 veya 59.07 türü olsa bile 62.10’a girmez (genellikle 62.01 / 62.02).",
    },
    "pozisyon_haritasi": [
        ["62.01", "Erkek palto, kaban, anorak, rüzgarlık", "Keçe/kaplanmış mensucattan olan 62.10", "Erkek montu, trençkot"],
        ["62.02", "Kadın manto, kaban, anorak, rüzgarlık", "62.01’in kadın karşılığı", "Kadın mantosu, kapitone anorak"],
        ["62.03", "Erkek takım elbise, takım, ceket, pantolon, şort", "Not 3; yüzme kıyafeti hariç", "Takım elbise, smokin, pantolon"],
        ["62.04", "Kadın takım elbise, takım, ceket, elbise, etek, pantolon", "Not 3; alt parça etek esas", "Elbise, etek, pantolon etek"],
        ["62.05", "Erkek gömlekleri", "Bel altı cep, alt sıkma tertibatı, kolsuz hariç", "Pamuklu dokunmuş gömlek"],
        ["62.06", "Kadın bluz, gömlek, gömlek-bluz", "Not 4 sınırları", "İpek bluz"],
        ["62.07", "Erkek fanila, atlet, külot, slip, pijama, bornoz", "Örme benzerleri 61.07 / 61.09", "Dokunmuş erkek pijaması, fanila"],
        ["62.08", "Kadın fanila, kaşkorse, kombinezon, gecelik, sabahlık", "Sütyen ve korse 62.12", "Dokunmuş gecelik, kombinezon"],
        ["62.09", "Bebek giyim eşyası ve aksesuarı", "Boy ≤ 86 cm; öncelikli (Not 5)", "Dokunmuş bebek elbisesi"],
        ["62.10", "56.02, 56.03, 59.03, 59.06, 59.07 mensucattan giysi", "62.09 hariç öncelikli (Not 6)", "Dokunmamış önlük, muşamba yağmurluk"],
        ["62.11", "Spor, kayak, yüzme kıyafetleri; diğer giysiler", "Ayrı yelek dahil; spor kıyafeti astarlı olabilir", "Eşofman, mayo, iş önlüğü, cüppe"],
        ["62.12", "Sütyen, korse, korse kemeri, pantolon askısı, jartiyer", "Örülmüş olsun olmasın", "Sütyen, hamile korsesi, jartiyer"],
        ["62.13", "Mendiller", "Kare/karemsi; hiçbir kenar 60 cm’yi aşmaz", "Mendil, küçük kare fular"],
        ["62.14", "Şal, eşarp, fular, kaşkol, peçe, duvak", "Kenarı 60 cm’yi aşan kare veya kare olmayan", "Büyük kare şal, gelin duvağı"],
        ["62.15", "Boyun bağı, papyon, kravat", "Örme olanlar 61.17", "İpek kravat, papyon"],
        ["62.16", "Eldivenler (tek parmaklı, parmaksız dahil)", "Sanayi koruyucu eldiveni dahil", "Dokunmuş iş eldiveni"],
        ["62.17", "Diğer hazır aksesuarlar; giysi parçaları", "62.12 eşyası ve parçaları hariç", "Kemer, vatka, örülmemiş çorap, apolet"],
    ],
    "notlar": [
        ["Bölüm XI Not 7", "Hazır eşya: kare/dikdörtgen dışında kesilmiş, bitmiş halde üretilmiş, kenarı bastırılmış veya düğümlü saçaklı, dikilerek birleştirilmiş, örülerek şekil verilmiş eşya. Aynı kumaştan parçaların uç uca eklenmesi veya tabakaların üst üste birleştirilmesi hazır eşya yapmaz."],
        ["Bölüm XI Not 14", "Metinde aksi belirtilmedikçe değişik pozisyonlardaki giyim eşyası, perakende satışa hazır hale getirilmiş olsa bile kendi pozisyonunda sınıflandırılır; “giyim eşyası” 61.01–61.14 ve 62.01–62.11 eşyasıdır. Takım elbise, pijama, yüzme kıyafeti gibi pozisyon metninde geçen takımlara uygulanmaz."],
        ["Fasıl 62 Not 1", "Fasıl, örülmüş eşya (62.12’dekiler hariç) dışında, vatka dışındaki her nevi dokumaya elverişli mensucattan hazır eşyaya uygulanır (Genel Açıklamalara göre keçe ve dokunmamış mensucat dahil)."],
        ["Fasıl 62 Not 2", "Fasıl dışı: (a) 63.09’daki kullanılmış giyim eşyası ve diğer kullanılmış eşya; (b) ortopedik cihazlar, cerrahi bant ve kuşaklar, fıtık bağları (90.21)."],
        ["Fasıl 62 Not 3 (a)", "“Takım elbise”: dış yüzleri aynı mensucattan iki veya üç parça; üst parçanın dış yüzü kollar hariç dört veya daha fazla parçadan oluşur (takım kumaşından önlü, astar kumaşından arkalı dikilmiş yelek de bulunabilir); alt parça askısız ve üst ön parçasız pantolon, kısa pantolon, şort (yüzme kıyafeti hariç), etek veya pantolon etek. Parçalar aynı renk ve yapıda, aynı tarzda, uygun ölçüde olmalı; farklı kumaştan kaytan olabilir. Birden çok alt parçada erkekte pantolon, kadında etek veya pantolon etek esas alınır. Jaketatay, frak ve smokin şartlara bakılmaksızın takım elbisedir."],
        ["Fasıl 62 Not 3 (b)", "“Takım”: perakende satış için hazırlanmış, aynı mensucattan; bir üst giysi (ikili takımda ikinci üst giysi olarak kazak veya yelek olabilir) ve bir veya iki alt giysiden oluşan set. Parçalar aynı tarz, renk ve yapıda, uygun ölçüde olmalı. 62.07 ve 62.08 eşyası hariçtir; tabir 62.11’deki spor ve kayak kıyafetlerine uygulanmaz."],
        ["Fasıl 62 Not 4", "62.05 ve 62.06; bel kısmından aşağıda cebi olan, beli sıkmalı veya alt kısmında başka sıkma tertibatı bulunan giysileri kapsamaz; 62.05 kolsuz giysileri de kapsamaz. Gömlek ve bluz tanımları Fasıl 61 Not 4 ile aynıdır."],
        ["Fasıl 62 Not 5", "62.09’da “bebek giyim eşyası ve aksesuarı”: boyu 86 cm’yi geçmeyen küçük çocuklara mahsus eşya. İlk bakışta hem 62.09 hem bu fasılın diğer pozisyonlarına girebilen eşya 62.09’dadır."],
        ["Fasıl 62 Not 6", "İlk bakışta hem 62.10 hem de bu fasılın 62.09 dışındaki diğer pozisyonlarına girebilen giyim eşyası 62.10’dadır."],
        ["Fasıl 62 Not 7", "62.11 anlamında “kayak kıyafetleri”: kayak tulumu (tek parça) veya perakende iki-üç parçalı kayak takımı (fermuarla kapanan anorak benzeri üst + pantolon, kısa pantolon veya salopet); parçalar aynı tarz ve yapıda olmalı, aynı renk şartı yoktur."],
        ["Fasıl 62 Not 8", "Fular ve fular tipi eşya, kare veya karemsi olup hiçbir kenarı 60 cm’yi aşmıyorsa 62.13’te mendil olarak sınıflandırılır. Herhangi bir kenarı 60 cm’yi geçen mendiller 62.14’tedir."],
        ["Fasıl 62 Not 9–10", "Önü soldan sağa kapanan giysi erkek, sağdan sola kapanan kadın giysisidir; kesimi cinsiyeti açıkça gösteriyorsa bu kural uygulanmaz, cinsiyeti belirlenemeyen eşya kadın pozisyonuna gider. Fasıldaki eşya metal iplikten yapılmış olabilir."],
        ["Genel Açıklamalar", "Fasıl 50–56, 58 ve 59’daki mensucattan (vatka hariç; keçe ve dokunmamış dahil) giysi ve aksesuarları kapsar. Örülmüş mensucat, kürk, tüy, deri, plastik veya metal aksam basit süs niteliğindeyse sınıflandırmayı etkilemez. Elektrikle ısıtılan giysiler bu fasılda kalır. Bitmemiş eşya ve şekil verilmiş mensucat esas karaktere sahipse mamul eşyanın pozisyonundadır. Hariç: 39.26, 40.15, 42.03, 68.12 giysileri; az işlem görmüş örgü parçalar (63.07); oyuncak bebek giysileri (95.03)."],
        ["62.10 Açıklama Notu", "Keçeden veya dokunmamış mensucattan ya da 59.03, 59.06, 59.07 mensucattan (örme hariç) tüm hazır giysiler, cinsiyet ayrımı yapılmaksızın buradadır (yağmurluk, dalgıç elbisesi, muşamba elbise, radyasyon koruyucu giysi). Hariç: kâğıt, selüloz vatka, selüloz lifli tülbentten giysi (48.18); 58.11 kapitoneli mensucattan giysi (genellikle 62.01 / 62.02); aksesuarlar (ör. eldiven 62.16)."],
        ["62.11–62.12 Açıklama Notları", "62.11’deki spor kıyafetleri astarlı olabilir; 61.14’ten farklı olarak örülmemiş ve ayrı sunulan dikilmiş yelekler de buradadır. 62.12: sütyen, korse, korse kemeri, jartiyer-kemer, pantolon askısı, çorap bağı, hamile ve doğum sonrası korseleri (90.21’deki ortopedik cihazlar hariç); tamamen kauçuktan korse ve kemer 40.15."],
        ["62.13–62.17 Açıklama Notları", "Mendil kenarında saçaklar ölçüye dahildir; mendil tamamen danteladan olabilir. Basitçe kare kesilmiş dokunmamış mensucat 56.03, yalnız kesilip işlenmiş kenarsız mensucat 58.10. Üniforma eşarbı 62.17. Kravat patronuna göre kesilmiş kumaş 62.15’te, verev kesilmiş kravatlık kumaş hariç. Lif kabağından friksiyon eldiveni 46.02. 62.17: kemer, vatka, subra, apolet, gemici yakası, örülmemiş çorap; mesleki kemer 63.07, fermuar 96.07."],
    ],
    "sinir_komsulari": [
        ["Örme giysi, örme şal, kravat, mendil", "Fasıl 61 (61.17)", "Fasıl 62 Not 1"],
        ["Kâğıttan, selüloz vatkadan veya selüloz lifli tülbentten giysi, mendil, eldiven", "48.18", "62.10, 62.13, 62.16 Açıklama Notları"],
        ["Basitçe kare veya dikdörtgen kesilmiş dokunmamış mensucat", "56.03", "62.13 ve 62.14 Açıklama Notları"],
        ["Yalnız kare kesilip işlenmiş, kenarı yapılmamış mensucat", "58.10", "62.13 Açıklama Notu"],
        ["Askeri veya dini üniforma eşarbı", "62.17", "62.14 Açıklama Notu"],
        ["Din adamı ve adliye mensubu boyun atkısı (rabat), jabo", "62.17", "62.15 Açıklama Notu"],
        ["Lif kabağından friksiyon eldiveni", "46.02", "62.16 Açıklama Notu"],
        ["Tamamen kauçuktan korse ve kemer", "40.15", "62.12 Açıklama Notu"],
        ["Ortopedik korse, fıtık bağı, cerrahi kuşak", "90.21", "Fasıl 62 Not 2(b)"],
        ["Bebek bonesi; bebek bezi", "65.05 / 96.19", "62.09 Açıklama Notu"],
        ["Fazlaca kullanılmış, balya halinde giysi", "63.09", "Fasıl 62 Not 2(a)"],
        ["Tamamen plastikten subra; kaplanmamış kauçuk omuz vatkası", "39.26 / 40.15", "62.17 Açıklama Notu"],
        ["Elektrikçi, cam silici gibi mesleki kemer", "63.07", "62.17 Açıklama Notu"],
        ["Kayarak işleyen fermuar", "96.07", "62.17 Açıklama Notu"],
        ["Oyuncak bebek giysisi", "95.03", "Genel Açıklamalar"],
    ],
    "tuzaklar": [
        "<b>Örme sütyen de 62.12’dedir.</b> Fasıl 62 örülmüş eşyayı kapsamaz; tek istisna 62.12’dir (sütyen, korse, korse kemeri, pantolon askısı, jartiyer).",
        "<b>60 cm kuralı.</b> Kare veya karemsi ve hiçbir kenarı 60 cm’yi aşmayan fular 62.13’te mendildir; bir kenarı 60 cm’yi geçerse 62.14. Saçaklı olanlarda saçaklar da ölçüye katılır; kare olmayan eşarp her boyutta 62.14.",
        "<b>Fanila örme ise 61.09, dokunmuş ise 62.07 / 62.08.</b> Fasıl 62’de fanila ve atlet cinsiyete göre ayrılır.",
        "<b>Keçe ve dokunmamıştan giysi 62.10’dur.</b> 56.02, 56.03, 59.03, 59.06, 59.07 mensucattan giysi 62.09 hariç her pozisyona üstün gelir; kâğıt ve selüloz vatkadan giysi ise 48.18.",
        "<b>Kapitoneli mont 62.10 değildir.</b> 58.11 kapitoneli mensucattan anorak, dış kumaşı kendi başına 59.03 türü olsa bile genellikle 62.01 / 62.02’dedir.",
        "<b>Bebek 62.10’u da geçer.</b> Keçeden veya kaplanmış mensucattan bebek giysisi 62.10’a değil 62.09’a gider (Not 5(b), Not 6).",
        "<b>Örülmemiş çorap 62.17’dedir.</b> Örme çorap 61.15; dokunmuş mendil 62.13 iken örme mendil 61.17.",
        "<b>Ayrı yelek 62.11’de.</b> Örme yelek 61.10’dayken örülmemiş, ayrı sunulan dikilmiş yelek 62.11’dedir (takım elbisenin parçası ise 62.03 / 62.04).",
        "<b>Set ≠ takım.</b> Farklı kumaştan bluz ve etek perakende pakette olsa da takım sayılmaz; Bölüm XI Not 14 gereği ayrı ayrı sınıflandırılır.",
        "<b>Kravatlık kumaş.</b> Kravat patronuna göre kesilmiş kumaş 62.15’tedir; verev kesilmiş kravatlık kumaş ise 62.15 dışında kalır.",
    ],
    "hafiza": {
        "kanca": "61’İN AYNASI + MENDİL – ŞAL – KRAVAT – ELDİVEN – DİĞER",
        "aciklama": "62.01–62.08 tek numara erkek, çift numara kadındır (Fasıl 61 ile aynı düzen). 09 bebek, 10 keçe-dokunmamış-kaplanmış, 11 spor ve diğer, 12 sütyen-korse (örme de). Aksesuar zinciri baştan aşağı iner: 13 <b>mendil</b> cepte, 14 <b>şal</b> omuzda, 15 <b>kravat</b> boyunda, 16 <b>eldiven</b> elde, 17 kalan her şey (kemer, çorap, parçalar).",
    },
    "sinav_odagi": [
        "Fular/mendil ayrımında 60 cm kuralı (Fasıl 62 Not 8) doğrudan sorulmuş; seçenekler 62.13–62.17 aksesuar pozisyonlarından oluşmuştur.",
        "Eldiven sorusunda 62.15 (kravat) çeldirici olmuştur; dokunmuş eldiven 62.16, örme eldiven 61.16’dadır.",
        "Perakende satışa hazırlanmış pantolon + gömleğin ayrı ayrı ve GYK 1 ile sınıflandırılması (Bölüm XI Not 14) sorulmuştur.",
        "Uyku tulumu ve seyahat battaniyesi sorularında 62.03 ve 62.05 çeldirici olarak kullanılmıştır: giysi pozisyonları ile 63.01 ve 94.04 eşyası karıştırılmamalıdır.",
        "Kullanılmış giyim eşyasının Fasıl 62 değil Fasıl 63 (63.09) olduğu sorulmuştur.",
    ],
    "cikmis_ornekler": [
        {
            "soru": "Aşağıdaki tarife pozisyonlarının hangisinde bir kenarı 50 cm uzunluğunda kare biçiminde fular sınıflandırılır?",
            "secenekler": ["62.13", "62.14", "62.15", "62.16", "62.17"],
            "cevap": "A",
            "aciklama": "Fasıl 62 Not 8’e göre fular ve fular tipi eşya, kare veya karemsi olup hiçbir kenarı 60 cm’yi aşmıyorsa 62.13’te mendil olarak sınıflandırılır; kenarı 50 cm olan kare fular bu sınırın altındadır. Kenarı 60 cm’yi geçseydi 62.14’e girerdi.",
        },
        {
            "soru": "Perakende satışa hazır hale getirilmiş, yünden mamul bir pantolon ile pamuktan yapılmış bir gömlek hangi genel yorum kuralına (GYK) göre ve ne şekilde sınıflandırılır?",
            "secenekler": ["Ayrı ayrı, GYK 1", "Ayrı ayrı, GYK 3", "Gömleğin pozisyonunda, GYK 3", "Pantolonun pozisyonunda, GYK 3"],
            "cevap": "A",
            "aciklama": "Bölüm XI Not 14’e göre değişik pozisyonlardaki giyim eşyası perakende satışa hazır hale getirilmiş olsa bile kendi pozisyonunda sınıflandırılır; bölüm notu uygulandığından dayanak GYK 1’dir ve GYK 3(b) takım kuralına başvurulmaz.",
        },
    ],
    "ozet": [
        "Fasıl 62 = örülmemiş her tür mensucattan (keçe, dokunmamış dahil; vatka hariç) hazır giysi ve aksesuar.",
        "Örme olanlar Fasıl 61; tek istisna 62.12 (sütyen, korse vb. örülmüş olsun olmasın).",
        "Öncelik: 62.09 (bebek, ≤ 86 cm) → 62.10 (keçe, dokunmamış, kaplanmış mensucattan giysi) → diğerleri.",
        "Fanila ve atlet burada cinsiyete göre 62.07 / 62.08; ayrı yelek 62.11; örülmemiş çorap 62.17.",
        "Mendil 62.13: kare/karemsi, hiçbir kenarı 60 cm’yi aşmaz; aksi halde 62.14.",
        "Erkek/kadın: soldan sağa erkek, sağdan sola kadın; belirlenemezse kadın. Set ≠ takım (Bölüm XI Not 14).",
    ],
    "sorular": kur(sorular, 6204),
}

yaz(d, 62)
