import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from yardim_48_52 import *  # noqa

obj = {
 "tur": "fasil",
 "fasil": 51,
 "baslik": "Yapağı ve yün, ince veya kaba hayvan kılı; at kılından iplik ve dokunmuş mensucat",
 "bolum": "XI",
 "oz": {
  "vurgu": "Fasıl 51’de önce lifin kimliği belirlenir: koyun-kuzu ise yün, Not 1(b) listesindeki hayvandan ise ince kıl, diğerlerinden ise kaba kıl; fırça kılı (05.02) ve ham at kılı (05.11) fasıl dışıdır. Sonra eşyanın aşaması bulunur: ham lif, döküntü, karde-taranmış lif, iplik (karde, taranmış, perakende) veya dokunmuş mensucat.",
  "maddeler": [
   "“Yapağı ve yün” yalnız koyun veya kuzulardan elde edilen tabii liftir; tanım bütün tarifede geçerlidir.",
   "İnce hayvan kılı: alpaka, lama, vikuna, deve, yak; Ankara, Tibet, Kaşmir ve benzeri keçiler (adi keçi hariç); tavşan, yabani tavşan, kunduz, Güney Amerika kunduzu, misk faresi.",
   "At kılı (at veya sığırın yele ve kuyruk kılı) ham haliyle 05.11’dedir; at kılından iplik 51.10, dokunmuş mensucat 51.13’tedir.",
   "Karde (strayhgarn) ve taranmış (kamgarn) ayrımı iplikte 51.06 / 51.07, kumaşta 51.11 / 51.12 pozisyonlarını belirler.",
   "Yün ve hayvan kılı iplikleri hiçbir kalınlıkta sicim sayılmaz; perakende yün ve ince kıl ipliği 51.09, kaba kıl ve at kılı ipliği her durumda 51.10’dur."
  ]
 },
 "karar_tablosu": {
  "aciklama": "Soruları yukarıdan aşağıya sırayla sorun; ilk “evet” cevabı pozisyonu verir.",
  "satirlar": [
   ["1", "Fırça imaline uygun kıl mı (domuz, porsuk vb.)?", "<b>05.02</b>"],
   ["2", "At kılı mı (at veya sığırın yele-kuyruk kılı), ham veya uçları bağlanmamış tek kıl halinde?", "<b>05.11</b>"],
   ["3", "İnsan saçı mı? Peruk veya oyuncak bebek saçı için hazırlanmış yün veya kıl mı?", "<b>05.01</b> · <b>67.03</b>"],
   ["4", "Yün veya kıl hâlâ deri üzerinde mi?", "Ham post veya kürk: <b>41.02</b> / <b>43.01</b>"],
   ["5", "Karde edilmemiş ve taranmamış lif mi?", "Yün <b>51.01</b> · ince veya kaba kıl <b>51.02</b>"],
   ["6", "Döküntü mü?", "Ditilmemiş <b>51.03</b> · ditilmiş (shoddy, mungo) <b>51.04</b>"],
   ["7", "Karde veya taranmış mı (fitil, şerit, top, yığın halinde taranmış)?", "<b>51.05</b>"],
   ["8", "Kaba hayvan kılı veya at kılı ipliği mi?", "<b>51.10</b> (perakende olsun olmasın)"],
   ["9", "Yün veya ince kıl ipliği perakende satışa hazır mı (Bölüm XI Not 4)?", "<b>51.09</b>"],
   ["10", "Perakende değilse hangi iplik?", "Karde yün <b>51.06</b> · taranmış yün <b>51.07</b> · ince kıl <b>51.08</b>"],
   ["11", "Dokunmuş mensucat mı?", "Karde <b>51.11</b> · taranmış <b>51.12</b> · kaba kıl veya at kılı <b>51.13</b>"]
  ],
  "dipnot": "* Karışımlarda Bölüm XI Not 2 uygulanır; yün ve ince hayvan kılı aynı fasılda yer aldığından oranları toplanır (ör. %40 sentetik devamsız lif, %35 taranmış yün, %25 taranmış ince kıl → 51.12)."
 },
 "pozisyon_haritasi": [
  ["51.01", "Yün (karde-taranmamış)", "Koyun-kuzu; yağlı, yıkanmış, karbonize", "Kırkma yapağı, yolunmuş yün"],
  ["51.02", "İnce veya kaba hayvan kılı (karde-taranmamış)", "Not 1(b)–(c) listesi", "Kaşmir, moher, deve, adi keçi kılı"],
  ["51.03", "Yün ve kıl döküntüleri (ditme hariç)", "Tarama, iplik, yıkama döküntüsü", "Tarak altı döküntüsü"],
  ["51.04", "Ditme yoluyla elde edilen döküntüler", "Paçavra veya ipliğin ditilmesi", "Shoddy, mungo"],
  ["51.05", "Karde veya taranmış yün ve kıl", "Fitil, şerit, top; yığın halinde taranmış", "Yün topu, karde şerit"],
  ["51.06", "Karde (strayhgarn) yün ipliği", "Perakende değil; dolaşık lif", "Sanayi tipi karde iplik"],
  ["51.07", "Taranmış (kamgarn) yün ipliği", "Perakende değil; paralel lif", "Kamgarn iplik"],
  ["51.08", "İnce hayvan kılı ipliği", "Karde veya taranmış; perakende değil", "Alpaka, kaşmir ipliği"],
  ["51.09", "Perakende yün ve ince kıl ipliği", "Bölüm XI Not 4 şartları", "El örgüsü yün yumağı"],
  ["51.10", "Kaba kıl ve at kılı ipliği", "Perakende olsun olmasın; gipe at kılı dahil", "At kılı ipliği"],
  ["51.11", "Karde yün veya ince kıl mensucatı", "Strayhgarn kumaş", "Flanel, battaniyelik kumaş"],
  ["51.12", "Taranmış yün veya ince kıl mensucatı", "Kamgarn kumaş", "Takım elbiselik kumaş"],
  ["51.13", "Kaba kıl veya at kılı mensucatı", "Tek at kıllarından da olabilir", "At kılı elek bezi, tela"]
 ],
 "notlar": [
  ["Bölüm XI Notları", "Bölüm notlarının tamamı Fasıl 50 modülündedir. Bu fasıl için kritik olanlar: Not 1(a) (fırça kılı 05.02, at kılı 05.11 bölüm dışı), Not 2 (karışım; gipe edilmiş at kılı ipliği tek madde sayılır), Not 3(B)(a) (yün ve hayvan kılı iplikleri sicim sayılmaz), Not 4 (perakende), Not 14 (giyim takımları ayrı ayrı)."],
  ["Fasıl 51 Not 1(a)", "Tarifenin neresinde geçerse geçsin “yapağı ve yün”: koyun veya kuzulardan elde edilen tabii lifler."],
  ["Fasıl 51 Not 1(b)", "“İnce hayvan kılı”: alpaka, lama, vikuna, deve (tek hörgüçlü deve dahil), yak kılı; Ankara, Tibet, Kaşmir veya benzeri keçilerin (<b>adi keçiler hariç</b>) kılı; tavşan (Ankara tavşanı dahil), yabani tavşan, kunduz, Güney Amerika kunduzu ve misk faresinin kılı."],
  ["Fasıl 51 Not 1(c)", "“Kaba hayvan kılı”: yukarıda sayılmayan hayvanların kılı; 05.02’deki fırça yapımında kullanılan kıllar ile 05.11’deki at kılı hariç."],
  ["Genel Açıklamalar (Fasıl 5 Not 4)", "“At kılı”: tek tırnaklı veya sığır türü hayvanların yele veya kuyruk kılları. At kılı ve döküntüleri 05.11’de; at kılından iplik ve dokunmuş mensucat bu fasıldadır."],
  ["Bölüm XI Not 4 (yün için)", "Tek kat iplikler kural olarak perakende sayılmaz; ancak yün veya ince kıldan <b>ağartılmamış</b> tek kat iplik ile <b>5.000 desiteksten fazla</b> ağartılmış, boyanmış veya baskılı tek kat iplik istisnadır. Ağartılmamış katlı iplikte çile istisnası da yün ve ince kıla uygulanmaz."],
  ["51.01 Açıklama Notu", "Kırkılmış veya postlardan fermantasyonla ya da kimyasal yolla ayrılmış (yolunmuş) yün; yağlı, sırtta yıkanmış, yıkanmış veya karbonize. Karde veya taramadan önce ağartılmış ya da boyanmış olması sınıflandırmayı etkilemez. Ham postlar 41.02 veya 43.01’de; yığın halinde taranmış yün 51.05’tedir."],
  ["51.02 Açıklama Notu", "Karde edilmemiş, taranmamış ince ve kaba kıllar; yıkama, ağartma, boyama ve suni kıvrımlandırma serbesttir. Kaba kıl örnekleri: adi keçi, köpek, maymun, su samuru ve tek tırnaklıların yan taraf kılları. İnsan saçı 05.01’de, peruk için hazırlanmış kıllar 67.03’tedir."],
  ["51.03 – 51.04 Açıklama Notları", "51.03: ditme dışındaki döküntüler (tarak altı, kopuk iplik, yıkama ve yatak boşaltma döküntüsü); karbonize, ağartılmış veya boyanmış olabilir. Yalnızca gübre olarak kullanılan döküntü Fasıl 31’de, kırpıntı-toz-taraz 56.01’dedir. 51.04: paçavra veya iplik döküntüsünün ditilmesiyle elde edilen yün (shoddy, mungo); ditilmemiş paçavralar 63.10’dadır."],
  ["51.05 Açıklama Notu", "Karde veya taranmış yün ve kıl (fitil, şerit, top). “Yığın halinde taranmış yün” de buradadır: ortalama lif uzunluğu <b>45 mm’den az</b>, kamgarn veya pamuk eğirme sistemine uygun, eğrilmeden önce yeniden karde edilmesi gerekir. Hafif bükümlü fitiller esas büküm görmedikçe iplik sayılmaz."],
  ["51.06 – 51.07 Açıklama Notları", "Karde (strayhgarn) iplik dolaşık ve gevşek liflidir → 51.06; taranmış (kamgarn) iplik düzgün ve paralel liflidir → 51.07. Yığın halinde taranmış yünden ve “taranmış-karde” iplikler 51.06’dadır. Katları kısmen karde, kısmen taranmış katlı iplik ağırlıkça üstün olana göre sınıflandırılır."],
  ["51.10 – 51.13 Açıklama Notları", "Kaba kıl ve at kılı iplikleri perakende olsun olmasın 51.10’dadır; uçları düğümlenerek devamlı hale getirilmiş at kılları ve gipe edilmiş at kılı ipliği de buradadır, tek at kılları ise 05.11’dedir. At kılından mensucat tek at kıllarından (20–70 cm) da dokunabilir ve 51.13’tedir; teknik amaçlı mensucat 59.11’dedir."]
 ],
 "sinir_komsulari": [
  ["Fırça imaline uygun domuz veya porsuk kılı", "05.02", "Fasıl 51 Not 1(c); Bölüm XI Not 1(a)"],
  ["Ham at kılı, uçları bağlanmamış tek at kılları, at kılı döküntüsü", "05.11", "Fasıl 51 Not 1(c); 51.10 Açıklama Notu"],
  ["İnsan saçı", "05.01", "51.02 hariç tutmaları; Bölüm XI Not 1(b)"],
  ["Yünlü koyun postu (ham)", "41.02 / 43.01", "51.01 hariç tutmaları"],
  ["Peruk veya oyuncak bebek saçı için hazırlanmış yün ve kıl", "67.03", "51.02 ve 51.05 hariç tutmaları"],
  ["Yalnızca gübre olarak kullanılabilen yün döküntüsü", "Fasıl 31", "51.03 hariç tutmaları"],
  ["Yün vatka", "30.05 / 56.01", "51.03–51.05 hariç tutmaları"],
  ["Yün kırpıntı, toz ve tarazları", "56.01", "51.03 ve 51.04 hariç tutmaları"],
  ["Ditilmemiş yün paçavralar", "63.10", "51.04 hariç tutmaları"],
  ["Tıbbi madde içeren veya perakende yün bandaj", "30.05", "51.11 ve 51.12 hariç tutmaları"],
  ["Teknik kullanıma mahsus yün veya at kılı mensucat", "59.11", "51.11–51.13 hariç tutmaları"],
  ["Yün halı", "Fasıl 57", "Bölüm XI Genel Açıklamalar (C)(a)"],
  ["Gipe edilmiş yün ipliği (at kılı hariç); metalize yün ipliği", "56.06 / 56.05", "Bölüm XI Not 3(B); Genel Açıklamalar Tablo I"]
 ],
 "tuzaklar": [
  "<b>At kılı = yele ve kuyruk.</b> At veya sığırın yele-kuyruk kılı “at kılı”dır ve ham hali 05.11’dedir; atın gövdesinin yan tarafındaki kıllar ise kaba hayvan kılı olarak 51.02’dedir.",
  "<b>Adi keçi ince kıl vermez.</b> Ankara, Tibet, Kaşmir ve benzeri keçilerin kılı ince kıldır; adi keçi kılı kaba kıldır. Katır, at, eşek gibi hayvanlar ince kıl listesinde yoktur.",
  "<b>Tek at kılı 05.11, düğümlenince 51.10.</b> Uçlarından bağlanmamış tek at kılları 05.11’de; uçları düğümlenerek devamlı hale getirilmiş veya gipe edilmiş at kılı ipliği 51.10’dadır.",
  "<b>51.10 perakende ayrımı yapmaz.</b> Kaba kıl ve at kılı iplikleri perakende olsun olmasın 51.10’dadır; yün ve ince kılda ise perakende iplik 51.09’a ayrılır.",
  "<b>Yığın halinde taranmış yün 51.05’tir.</b> Ondan elde edilen iplik ise taranmış değil karde (strayhgarn) iplik sayılır → 51.06.",
  "<b>Hafif bükümlü fitil iplik değildir.</b> Tek kat iplik kalınlığındaki karde veya taranmış fitiller esas büküm görmedikçe 51.05’te kalır.",
  "<b>Ditme belirleyicidir.</b> Üretim döküntüsü 51.03, ditilmiş paçavra lifi (shoddy, mungo) 51.04, ditilmemiş paçavra 63.10’dadır.",
  "<b>Yün ipliği hiçbir zaman sicim olmaz.</b> Bölüm XI Not 3(B)(a) yün ve hayvan kılı ipliklerini (metal takviyeliler hariç) sicim tanımının dışında tutar.",
  "<b>Yün ve ince kıl karışımda toplanır.</b> %40 sentetik devamsız lif, %35 yün, %25 ince kıl: yün ve ince kıl birlikte %60 olduğundan kumaş Fasıl 51’dedir.",
  "<b>Tek kat yün ipliği de perakende olabilir.</b> Ağartılmamış tek kat yün ipliği ve 5.000 desiteksten kalın boyalı tek kat yün ipliği perakende sayılabilir; pamuk, ipek ve sentetik tek kat iplikler hiçbir zaman perakende sayılmaz."
 ],
 "hafiza": {
  "kanca": "AL-Vİ-DE-Y + KEÇİ + TAVŞAN + KUNDUZ + MİSK",
  "aciklama": "İnce kıl listesi: <b>AL</b>paka-lama, <b>Vİ</b>kuna, <b>DE</b>ve, <b>Y</b>ak; Ankara-Tibet-Kaşmir <b>KEÇİ</b>si (adi keçi hariç); <b>TAVŞAN</b> ve yabani tavşan; <b>KUNDUZ</b> ve Güney Amerika kunduzu; <b>MİSK</b> faresi. Pozisyon zinciri: 01 yün, 02 kıl, 03 döküntü, 04 ditme, 05 karde-taranmış; 06 karde iplik, 07 taranmış iplik, 08 ince kıl ipliği, 09 perakende, 10 kaba kıl-at kılı; 11 karde kumaş, 12 taranmış kumaş, 13 kaba kıl-at kılı kumaşı."
 },
 "sinav_odagi": [
  "“İnce hayvan kılı hangi hayvandan elde edilemez” kalıbı birden fazla kez sorulmuştur; doğru cevap listede bulunmayan katırdır, çeldiriciler lama, yak, alpaka, Tibet keçisi ve keçidir.",
  "Fasıl 51 Not 1 listesinin ezberlenmesi yeterlidir; adi keçi listeden hariç olduğu halde Ankara, Tibet, Kaşmir keçileri nedeniyle “keçi” seçeneği dikkatle okunmalıdır.",
  "Tibet keçisi gibi ince kıllı hayvanların adlarının deri ve kürk sorularında (Fasıl 43) da seçenek olarak kullanılması.",
  "Yünden pantolon ve pamuklu gömlek takımında Bölüm XI Not 14 uygulaması (ayrı ayrı, GYK 1).",
  "Bu fasıl pozisyon sorusundan çok tanım sorusu olarak gelmiştir."
 ],
 "cikmis_ornekler": [
  {
   "soru": "Türk Gümrük Tarife mevzuatına göre ince hayvan kılı aşağıda yer alan hayvanlardan hangisinden elde edilemez?",
   "secenekler": ["Lama", "Yak", "Tibet keçisi", "Alpaka", "Katır"],
   "cevap": "E",
   "aciklama": "Fasıl 51 Not 1(b) ince hayvan kılını alpaka, lama, vikuna, deve, yak, Ankara-Tibet-Kaşmir ve benzeri keçiler, tavşan, kunduz, Güney Amerika kunduzu ve misk faresiyle sınırlar; katır listede yoktur. Katırın yele ve kuyruk kılı at kılı (05.11), diğer kılları kaba kıldır."
  }
 ],
 "ozet": [
  "Yün yalnız koyun-kuzudan; ince kıl Not 1(b) listesinden; kalan hayvan kılları kaba kıl (fırça kılı ve at kılı hariç).",
  "At kılı (yele-kuyruk) ve döküntüsü 05.11; ipliği 51.10, kumaşı 51.13.",
  "Zincir: ham 51.01 / 51.02 → döküntü 51.03 / 51.04 → karde-taranmış 51.05 → iplik 51.06–51.10 → kumaş 51.11–51.13.",
  "Karde ve taranmış ayrımı iplikte 51.06 / 51.07, kumaşta 51.11 / 51.12; yığın halinde taranmış yünden iplik 51.06.",
  "Perakende yün ve ince kıl ipliği 51.09; kaba kıl ve at kılı ipliği perakende olsa da 51.10.",
  "Yün ipliği hiçbir kalınlıkta sicim olmaz; karışımda yün ve ince kıl oranları toplanır."
 ],
 "sorular": [
  S("Tarife Cetveline göre, canlı koyunlardan kırkılmış, henüz yıkanmamış (yağlı) yapağı hangi tarife pozisyonunda sınıflandırılır?",
    ["51.03", "51.01", "51.05", "41.02", "51.02"], "B", ESYA,
    "Karde edilmemiş ve taranmamış koyun yünü yağlı, sırtta yıkanmış, yıkanmış veya karbonize halde 51.01’dedir. 51.02 ince ve kaba hayvan kılı içindir; 51.05 karde veya taranmış yündür; 41.02 deri üzerindeki yünlü postlardır, kırkılmış yapağı değildir.",
    "Fasıl 51 Not 1(a); 51.01 Açıklama Notu."),
  S("Tarife Cetveline göre, karde edilip taranmış, top (taranmış bant) halindeki Kaşmir keçisi kılı hangi tarife pozisyonunda sınıflandırılır?",
    ["51.02", "51.08", "51.05", "51.03", "51.04"], "C", ESYA,
    "Kaşmir keçisi kılı ince hayvan kılıdır; karde edilmiş veya taranmış yün ve kıllar (topslar dahil) 51.05’tedir. 51.02 yalnız karde edilmemiş ve taranmamış kılı kapsar; 51.08 ise bu kılın bükülmüş ipliğidir.",
    "Fasıl 51 Not 1(b); 51.05 pozisyon metni ve Açıklama Notu."),
  S("Tarife Cetveline göre, yün paçavralarının ditilmesiyle elde edilen shoddy (ditme yünü) hangi tarife pozisyonunda sınıflandırılır?",
    ["51.03", "63.10", "56.01", "51.04", "51.05"], "D", ESYA,
    "51.04 paçavra veya iplik döküntülerinin ditilmesiyle elde edilen yün ve kıl döküntülerini (shoddy, mungo) kapsar. 51.03 ditme dışındaki döküntüler içindir; ditilmemiş paçavralar 63.10’da, kırpıntı ve tozlar 56.01’dedir; karde edilmiş olsaydı 51.05’e girerdi.",
    "51.04 pozisyon metni ve Açıklama Notu, hariç tutmalar."),
  S("Tarife Cetveline göre, karde edilmiş alpaka kılından, konik bobine sarılı tek kat iplik hangi tarife pozisyonunda sınıflandırılır?",
    ["51.06", "51.10", "51.09", "51.07", "51.08"], "E", ESYA,
    "Alpaka kılı ince hayvan kılıdır ve ince kıl iplikleri (karde veya taranmış) perakende değilse 51.08’dedir. Konik bobine sarılı iplik Bölüm XI Not 4(B)(d) uyarınca perakende sayılmaz, bu nedenle 51.09 değildir. 51.06 ve 51.07 yün ipliği, 51.10 kaba kıl ve at kılı ipliğidir.",
    "Fasıl 51 Not 1(b); 51.08 Açıklama Notu; Bölüm XI Not 4(B)(d)."),
  S("Tarife Cetveline göre, adi keçi kılı ipliğinden dokunmuş, top halindeki mensucat hangi tarife pozisyonunda sınıflandırılır?",
    ["51.13", "51.11", "51.12", "51.10", "59.11"], "A", ESYA,
    "Adi keçi kılı Not 1(b)’de ince kıldan açıkça hariç tutulduğundan kaba hayvan kılıdır; kaba kıl ipliğinden dokunmuş mensucat 51.13’tedir. 51.11 ve 51.12 yün veya ince kıl mensucatıdır; 51.10 ipliğin kendisidir; teknik amaçla hazırlanmış olmadığı için 59.11 değildir.",
    "Fasıl 51 Not 1(b)–(c); 51.13 Açıklama Notu."),
  S("Aşağıdakilerden hangisi Tarife Cetvelinin 51. faslında <b>sınıflandırılmaz</b>?",
    ["At kılından iplik", "At kılından dokunmuş mensucat", "Uçlarından birbirine bağlanmamış tek at kılları", "Pamuk ipliğiyle gipe edilmiş at kılı ipliği", "Kaba hayvan kılı döküntüleri"], "C", OLUMSUZ,
    "51.10 Açıklama Notuna göre tek at kılları (uçlarından bağlanmamış olanlar) 05.11’dedir. At kılı ipliği ve gipe edilmiş at kılı ipliği 51.10’da, at kılı mensucatı 51.13’te, kaba kıl döküntüleri 51.03’tedir.",
    "Fasıl 51 Not 1(c); 51.10 Açıklama Notu."),
  S("Aşağıdakilerden hangisi 51.03 pozisyonunda <b>yer almaz</b>?",
    ["Tarama sırasında tarak altına düşen kısa lifli yün döküntüsü", "Eğirme sırasında oluşan kopuk yün iplik döküntüsü", "Kullanılmış yatakların boşaltılmasından elde edilen yün döküntüsü", "Yalnızca gübre olarak kullanılmaya uygun yün döküntüsü", "Karbonize edilmiş yün tarama döküntüsü"], "D", OLUMSUZ,
    "51.03 Açıklama Notu, yalnızca gübre olarak kullanılmaya uygun yün veya hayvan kılı döküntülerini Fasıl 31’e gönderir. Tarak altı döküntüsü, iplik döküntüsü ve yatak boşaltma döküntüsü 51.03’te sayılmıştır; karbonize edilmesi sınıflandırmayı etkilemez.",
    "51.03 Açıklama Notu ve hariç tutmaları."),
  S("Aşağıdakilerden hangisi 51.01 pozisyonunda <b>yer almaz</b>?",
    ["Koyun postlarından fermantasyonla ayrılmış yolunmuş yün", "Hayvan üzerinde iken yıkanmış (sırtta yıkanmış) yapağı", "Karbonize edilmiş yün", "Karde edilmeden önce boyanmış yün", "Yığın halinde taranmış yün"], "E", OLUMSUZ,
    "Yığın halinde taranmış yün karde ve tarama makinelerinden geçmiş olduğundan 51.05’tedir; 51.01 hariç tutmalarında açıkça sayılmıştır. Yolunmuş yün, sırtta yıkanmış ve karbonize yün 51.01’dedir; karde öncesi boyama da sınıflandırmayı etkilemez.",
    "51.01 ve 51.05 Açıklama Notları."),
  S("Aşağıdakilerden hangisi 51.02 pozisyonunda <b>sınıflandırılmaz</b>?",
    ["Yıkanmış, karde edilmemiş deve kılı", "Dolgu için suni olarak kıvrımlandırılmış kaba hayvan kılı", "Ağartılmış, taranmamış Ankara keçisi (moher) kılı", "Köpek kılı", "Fırça imaline uygun domuz kılı"], "E", OLUMSUZ,
    "Fırça imaline uygun domuz ve porsuk kılları Not 1(c) gereği kaba kıldan hariçtir ve 05.02’dedir. Deve ve moher ince kıl, köpek kılı kaba kıl olarak 51.02’dedir; yıkama, ağartma ve suni kıvrımlandırma pozisyonu değiştirmez.",
    "Fasıl 51 Not 1(c); 51.02 Açıklama Notu."),
  S("Karde edilmemiş ve taranmamış halde sunulan aşağıdaki kıllardan hangisi diğerlerinden farklı bir pozisyonda sınıflandırılır?",
    ["Lama kılı", "Kunduz kılı", "Su samuru kılı", "Atın gövdesinin yan tarafından elde edilen kıl", "Atın yelesinden elde edilen kıl"], "E", FARKLI,
    "Yele ve kuyruk kılı “at kılı”dır ve 05.11’dedir. Lama ve kunduz kılı ince kıl, su samuru ve tek tırnaklıların yan taraf kılları kaba kıl olarak 51.02’dedir. Tuzak, atın her kılını at kılı sanmaktır.",
    "Fasıl 51 Not 1(b)–(c); Fasıl 51 Genel Açıklamalar; 51.02 Açıklama Notu."),
  S("Perakende satış için hazırlanmamış aşağıdaki ipliklerden hangisi diğerlerinden farklı bir pozisyonda sınıflandırılır?",
    ["Ağırlıkça %90 yün içeren karde (strayhgarn) yün ipliği", "Yığın halinde taranmış yünden elde edilen iplik", "“Taranmış-karde edilmiş iplik” olarak bilinen iplik", "Taranmış (kamgarn) yün ipliği", "Ağırlıkça %80 yün, %20 poliamid devamsız lif içeren karde yün ipliği"], "D", FARKLI,
    "Taranmış (kamgarn) yün ipliği 51.07’dedir. Karde yün iplikleri (karışımlı olanlar dahil), yığın halinde taranmış yünden elde edilen iplikler ve “taranmış-karde” iplikler 51.06 Açıklama Notunda sayılmış ve 51.07 Açıklama Notunda 51.07 dışında bırakılmıştır.",
    "51.06 ve 51.07 Açıklama Notları."),
  S("Aşağıdaki dokunmuş mensucattan (oranlar ağırlık itibariyledir) hangisi diğerlerinden farklı bir fasılda sınıflandırılır?",
    ["%35 yün, %35 sentetik devamsız lif, %30 pamuk", "%40 sentetik devamsız lif, %35 taranmış yün, %25 taranmış ince hayvan kılı", "%55 yün, %45 pamuk", "%45 karde yün, %30 keten, %25 pamuk", "%40 alpaka kılı, %30 ipek, %30 pamuk"], "A", FARKLI,
    "A’da yün ve sentetik devamsız lif eşittir; Bölüm XI Not 2(A) gereği numara sırasında en sondaki seçilir → Fasıl 55. B’de yün ve ince kıl aynı fasılda toplanır (%60) → Fasıl 51; C, D ve E’de yün veya ince kıl tek başına üstündür → Fasıl 51.",
    "Bölüm XI Not 2(A) ve 2(B)(d); Bölüm XI Genel Açıklamalar (I)(A)(1)(a)."),
  S("Aşağıdaki eşya çiftlerinden hangisinde her iki eşya da aynı tarife pozisyonunda sınıflandırılır?",
    ["Perakende yün ipliği – Perakende kaba hayvan kılı ipliği", "Kaba hayvan kılından iplik – At kılından iplik", "Karde yün ipliği – Karde ince hayvan kılı ipliği", "Ditme yünü – Yün tarama döküntüsü", "Karde yünden dokunmuş flanel – Taranmış yünden takım elbiselik kumaş"], "B", FARKLI,
    "Kaba hayvan kılı ve at kılı iplikleri birlikte 51.10’dadır. Diğer çiftler ayrılır: 51.09 / 51.10 (kaba kıl ipliği perakende olsa da 51.10); 51.06 / 51.08; 51.04 / 51.03; 51.11 / 51.12.",
    "51.03–51.12 pozisyon metinleri ve Açıklama Notları."),
  S("Tarife Cetvelinin 51. Fasıl notlarına göre aşağıdaki hayvanlardan hangisinin kılı “ince hayvan kılı” <b>değildir</b>?",
    ["Vikuna", "Yak", "Misk faresi", "Adi keçi", "Ankara tavşanı"], "D", TANIM,
    "Not 1(b) Ankara, Tibet, Kaşmir ve benzeri keçilerin kılını ince kıl sayarken adi keçileri açıkça hariç tutar; adi keçi kılı kaba kıldır. Vikuna, yak, misk faresi ve Ankara tavşanı listede sayılmıştır.",
    "Fasıl 51 Not 1(b)–(c)."),
  S("Tarife Cetvelinin 51. Fasıl notlarına göre “yapağı ve yün” tabirinden ne anlaşılır?",
    ["Koyun veya kuzulardan elde edilen tabii lifler", "Koyun, keçi ve deveden elde edilen tabii lifler", "Koyun ve lamadan elde edilen tabii lifler", "Tüm evcil hayvanların kırkılmış kılları", "Koyun ve Ankara keçisinden elde edilen lifler"], "A", TANIM,
    "Not 1(a)’ya göre tarifenin neresinde geçerse geçsin “yapağı ve yün” yalnızca koyun veya kuzulardan elde edilen tabii liflerdir. Keçi, deve, lama ve Ankara keçisi lifleri yün değil, ince veya kaba hayvan kılıdır.",
    "Fasıl 51 Not 1(a)."),
  S("Bölüm XI Not 4’e göre, diğer şartların sağlanması halinde aşağıdaki tek kat ipliklerden hangisi “perakende satış için hazırlanmış” sayılabilir?",
    ["Pamuktan ağartılmış tek kat iplik", "İpekten tek kat iplik", "Yünden ağartılmamış tek kat iplik", "Yünden boyanmış, 4.000 desiteks tek kat iplik", "Sentetik liflerden tek kat iplik"], "C", TANIM,
    "Not 4(B)(a) tek kat iplikleri perakende sayılmaktan çıkarır; istisna yalnız yün veya ince kıldan ağartılmamış tek kat iplik ile 5.000 desiteksten fazla ağartılmış, boyanmış veya baskılı yün-ince kıl tek kat ipliktir. 4.000 desiteks boyalı yün ipliği bu eşiği aşmaz; pamuk, ipek ve sentetik tek kat iplikler hiç perakende sayılmaz.",
    "Bölüm XI Not 4(B)(a)."),
  S("51.05 Açıklama Notuna göre “yığın halinde taranmış yün” için aşağıdakilerden hangisi doğrudur?",
    ["Ortalama lif uzunluğu 45 mm’den fazladır ve doğrudan strayhgarn sisteminde eğrilir.", "Ortalama lif uzunluğu 45 mm’den azdır; kamgarn veya pamuk eğirme sistemine uygundur ve eğrilmeden önce yeniden karde edilmelidir.", "Karde edilmemiş yün sayıldığından 51.01’de sınıflandırılır.", "Tarama döküntüsü olduğundan 51.03’te sınıflandırılır.", "Bundan elde edilen iplikler taranmış (kamgarn) iplik olarak 51.07’dedir."], "B", TANIM,
    "51.05 Açıklama Notu yığın halinde taranmış yünü ortalama lif uzunluğu 45 mm’den az, kamgarn veya pamuk eğirme sistemine uygun, strayhgarn sistemine uygun olmayan ve eğrilmeden önce yeniden karde edilmesi gereken ürün olarak tanımlar ve 51.05’e alır. Bu yünden elde edilen iplikler 51.06’dadır.",
    "51.05 Açıklama Notu; 51.06 ve 51.07 Açıklama Notları."),
  S("Ağırlıkça %48 taranmış yün, %30 pamuk ve %22 ketenden oluşan dokunmuş mensucat hangi kurallarla hangi pozisyonda sınıflandırılır?",
    ["GYK 1 (Bölüm XI Not 2) ve GYK 6 uyarınca 51.12’de", "GYK 3(b) uyarınca esas karakteri veren pamuk nedeniyle 52.12’de", "GYK 3(c) uyarınca numara sırasında en son gelen keten nedeniyle 53.09’da", "GYK 2(b) uyarınca karışım kuralıyla 51.11’de", "GYK 1 uyarınca pamuklu karışık mensucat olarak 52.11’de"], "A", GYK,
    "Bölüm XI Not 2(A) karışımı ağırlıkça her birine üstün gelen maddeye (yün %48) bağlar; bu bir bölüm notu olduğundan dayanak GYK 1’dir, alt pozisyon seçimi GYK 6 ile yapılır. Yün taranmış olduğundan 51.12’dedir; 51.11 karde yün mensucatıdır.",
    "GYK 1 ve 6; Bölüm XI Not 2(A); 51.12 Açıklama Notu."),
  S("Ağırlıkça %50 karde yün ve %50 sentetik devamsız liften oluşan dokunmuş mensucatın sınıflandırılmasına ilişkin aşağıdakilerden hangisi doğrudur?",
    ["Fasıl 51; GYK 3(b) – esas karakteri yün verir", "Fasıl 55; GYK 1 – Bölüm XI Not 2(A)’ya göre eşit ağırlıktakilerden numara sırasında en sonda gelen", "Fasıl 55; GYK 3(c) – numara sırasında en sonda gelen", "Fasıl 51; GYK 3(a) – en özel tanım", "Fasıl 54; GYK 1 – sentetik maddeler her zaman önceliklidir"], "B", GYK,
    "Hiçbir madde ağırlıkça üstün gelmediğinden Not 2(A)’nın ikinci paragrafı uygulanır: eşit ölçüde dikkate alınabilecek pozisyonlardan numara sırasında en sondaki seçilir → Fasıl 55. Sonuç bir bölüm notundan çıktığı için dayanak GYK 1’dir; C şıkkı doğru fasla yanlış kuralla ulaşır.",
    "GYK 1; Bölüm XI Not 2(A)."),
  S("Aşağıdaki eşyaları sınıflandırıldıkları pozisyonlarla eşleştiriniz: I. Kırkılmış, yıkanmamış yapağı · II. Karde edilmiş yün · III. Perakende olmayan karde (strayhgarn) yün ipliği · IV. Perakende satışa hazır yün ipliği — a) 51.01 · b) 51.05 · c) 51.06 · d) 51.09",
    ["I-a, II-c, III-b, IV-d", "I-b, II-a, III-c, IV-d", "I-a, II-b, III-d, IV-c", "I-d, II-b, III-c, IV-a", "I-a, II-b, III-c, IV-d"], "E", ESLE,
    "Ham yün 51.01’de, karde edilmiş yün (henüz iplik değil) 51.05’te, perakende olmayan karde yün ipliği 51.06’da, perakende satışa hazır yün ipliği 51.09’dadır. Karde edilmiş lif ile karde iplik arasındaki fark büküm işlemidir.",
    "51.01, 51.05, 51.06 ve 51.09 Açıklama Notları."),
  S("Tarife Cetveline göre insan saçı ……, fırça imaline uygun domuz kılı ……, at kılı ve döküntüleri …… ve peruk imali için hazırlanmış yün …… pozisyonunda sınıflandırılır. Boşlukları sırasıyla dolduran seçenek hangisidir?",
    ["05.02 / 05.01 / 05.11 / 67.03", "05.01 / 05.11 / 05.02 / 67.03", "05.01 / 05.02 / 51.10 / 67.04", "05.01 / 05.02 / 05.11 / 67.03", "67.03 / 05.02 / 05.11 / 51.05"], "D", ESLE,
    "İnsan saçı 05.01’de, fırça kılları 05.02’de, at kılı ve döküntüleri 05.11’dedir (Not 1(c)); peruk veya benzeri eşya için hazırlanmış yün ve kıllar 51.02 ve 51.05 hariç tutmalarına göre 67.03’tedir. 51.10 at kılının ipliğidir, ham kılı değildir.",
    "Fasıl 51 Not 1(c); Bölüm XI Not 1(a)–(b); 51.02 ve 51.05 hariç tutmaları."),
  S("Aşağıdakilerden hangileri 51.05 pozisyonunda yer alır? I. Henüz esas büküm görmemiş, hafifçe bükülmüş karde yün fitilleri II. Taranmış yün topları (tops) III. Karde edilmiş ince hayvan kılı IV. Peruk imali için hazırlanmış yün",
    ["I ve II", "II ve IV", "I, II ve III", "I, III ve IV", "II, III ve IV"], "C", COKLU,
    "51.05 karde veya taranmış yün ve kılları kapsar; tops ve fitiller (hafif bükümlü olsalar da esas büküm görmedikçe) buradadır. IV yanlıştır: peruk imali için hazırlanmış yün 51.05 hariç tutmalarına göre 67.03’tedir.",
    "51.05 pozisyon metni, Açıklama Notu ve hariç tutmaları."),
  S("Aşağıdaki ifadelerden hangileri doğrudur? I. At kılı, tek tırnaklı veya sığır türü hayvanların yele veya kuyruk kıllarıdır. II. Uçlarından birbirine bağlanmamış tek at kılları 51.10’da yer alır. III. At kılından dokunmuş mensucat, 05.11’deki tek at kıllarından da yapılmış olabilir ve 51.13’tedir. IV. Tavşan kılı kaba hayvan kılıdır.",
    ["I ve III", "I ve II", "II ve IV", "I, II ve III", "I, III ve IV"], "A", COKLU,
    "I Fasıl 51 Genel Açıklamalarındaki (Fasıl 5 Not 4) tanımdır; III 51.13 Açıklama Notunun ifadesidir. II yanlıştır: tek at kılları 05.11’de, uçları düğümlenmiş olanlar 51.10’dadır. IV yanlıştır: tavşan (Ankara tavşanı dahil) kılı Not 1(b)’ye göre ince kıldır.",
    "Fasıl 51 Not 1(b); Genel Açıklamalar; 51.10 ve 51.13 Açıklama Notları."),
  S("Taranmış Kaşmir keçisi kılından, ağartılmış, iki katlı bükülü, 1.500 desiteks iplik; el örgüsü için 50 g’lık yumaklar halinde ve banderollü olarak sunulmaktadır. Bu iplik hangi tarife pozisyonunda sınıflandırılır?",
    ["51.08", "51.09", "51.10", "51.07", "56.07"], "B", SENARYO,
    "Not 4(A)(b)(ii)’ye göre 2.000 desiteksten az ipliklerde top veya yumak ağırlığı 125 g’ı geçmiyorsa iplik perakende satışa hazırdır; ağartılmış ve yumak halinde olduğundan 4(B) istisnaları uygulanmaz. Perakende yün veya ince kıl ipliği 51.09’dadır; 51.08 perakende olmayan ince kıl ipliğidir. Hayvan kılı ipliği sicim sayılmaz.",
    "Fasıl 51 Not 1(b); Bölüm XI Not 3(B)(a), 4(A)(b) ve 4(B); 51.09 Açıklama Notu."),
  S("Ağırlıkça %70 karde edilmiş yün ve %30 poliamid devamsız liften dokunmuş, m2 ağırlığı 350 g olan paltoluk kumaş (top halinde) hangi tarife pozisyonunda sınıflandırılır?",
    ["51.12", "55.15", "51.11", "51.13", "55.12"], "C", SENARYO,
    "Yün ağırlıkça üstün olduğundan kumaş Fasıl 51’dedir (Bölüm XI Not 2(A)); yün karde edildiği için karde yün mensucatı olarak 51.11’dedir. 51.12 taranmış yün, 51.13 kaba kıl ve at kılı mensucatıdır; Fasıl 55 seçenekleri sentetik devamsız lif üstün olsaydı geçerli olurdu.",
    "Bölüm XI Not 2(A); 51.11 Açıklama Notu.")
 ]
}

yaz(obj, 51, 5101)
