import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from yardim_53_58 import S, SX, yaz  # noqa: E402

E4 = "Eşya → 4’lü pozisyon"
OT = "Olumsuz teşhis"
FA = "Farklı/aynı pozisyon veya fasıl"
FN = "Fasıl notu · Tanım/Eşik"
GY = "Genel Yorum Kuralı"
ES = "Eşleştirme / Boşluk doldurma"
CC = "Çoktan-çoğa (I–IV)"
SN = "Senaryo"

d = {
 "tur": "fasil",
 "fasil": 55,
 "baslik": "Sentetik ve suni devamsız lifler",
 "bolum": "XI",
 "oz": {
  "vurgu": "Fasıl 55, sentetik ve suni liflerin kısa kesilmiş (devamsız) hallerini ve Not 1’e uyan filament demetlerini kapsar; sıra demet → lif → döküntü → karde-taranmış lif → iplik → dokunmuş mensucattır. Kumaşta iki ölçü belirleyicidir: sentetik devamsız lif oranı (%85) ve pamukla karışık olanlarda m² ağırlığı (170 g).",
  "maddeler": [
   "Filament demeti, Fasıl 55 Not 1’in beş şartını birlikte taşıyorsa sentetik 55.01, suni 55.02; uzunluğu 2 m’yi geçmeyen demet 55.03 / 55.04; diğer demetler Fasıl 54’tedir.",
   "Lif: karde edilmemiş sentetik 55.03, suni 55.04; döküntü 55.05; karde edilmiş, taranmış veya iplik imaline hazırlanmış sentetik 55.06, suni 55.07.",
   "İplik: dikiş ipliği 55.08 (perakende olsun olmasın); sentetik 55.09, suni 55.10 (perakende değil); perakende iplik 55.11.",
   "Mensucat: sentetik devamsız lif ≥ %85 → 55.12; %85’ten az ve esasen pamukla karışık → 55.13 (≤ 170 g/m²) veya 55.14 (170 g/m²’yi geçen); diğer karışımlar 55.15; suni devamsız lif 55.16."
  ]
 },
 "karar_tablosu": {
  "aciklama": "Soruları yukarıdan aşağıya sırayla sorun; ilk “evet” cevabı pozisyonu verir.",
  "satirlar": [
   ["1", "Uzunluğu 5 mm’yi geçmeyen lif kırpıntısı (flok), lif tozu, taraz veya vatka mı?", "<b>56.01</b> (tıbbi vatka <b>30.05</b>)"],
   ["2", "Paçavra mı? Dokunmamış mensucat veya keçe mi?", "Paçavra <b>Fasıl 63</b> · dokunmamış <b>56.03</b> · keçe <b>56.02</b>"],
   ["3", "Filament demeti mi?", "Not 1’e uyuyorsa <b>55.01</b> / <b>55.02</b> · 2 m’yi geçmiyorsa <b>55.03</b> / <b>55.04</b> · diğerleri <b>Fasıl 54</b>"],
   ["4", "Karde edilmemiş döküntü mü? (tarak, iplik, ditme döküntüsü)", "<b>55.05</b>"],
   ["5", "Karde edilmemiş, taranmamış devamsız lif mi?", "Sentetik <b>55.03</b> · suni <b>55.04</b>"],
   ["6", "Karde edilmiş, taranmış, iplik imaline hazırlanmış mı? (şerit, tops, fitil; döküntüden olanlar dahil)", "Sentetik <b>55.06</b> · suni <b>55.07</b>"],
   ["7", "Dikiş ipliği mi? (Bölüm XI Not 5)", "<b>55.08</b>"],
   ["8", "10.000 desiteksten fazla, sicim niteliğinde iplik mi?", "<b>56.07</b>"],
   ["9", "Perakende satış için hazırlanmış iplik mi? (Bölüm XI Not 4)", "<b>55.11</b>"],
   ["10", "İplik mi?", "Sentetik <b>55.09</b> · suni <b>55.10</b>"],
   ["11", "Dokunmuş mensucat mı?*", "Sentetik ≥ %85 <b>55.12</b> · pamuklu ≤ 170 g/m² <b>55.13</b> · pamuklu &gt; 170 g/m² <b>55.14</b> · diğer <b>55.15</b> · suni <b>55.16</b>"]
  ],
  "dipnot": "* Karışımda önce Bölüm XI Not 2 uygulanır: 54 ve 55. fasıllar başka bir fasılla karşılaştırılırken tek fasıl sayılır; fasıl belirlendikten sonra o fasıl içinde ağırlıkça üstün lif aranır, eşitlikte numara sırasına göre son pozisyon alınır."
 },
 "pozisyon_haritasi": [
  ["55.01", "Sentetik filament demetleri", "Not 1’in beş şartı", "Poliester filament demeti (tow)"],
  ["55.02", "Suni filament demetleri", "Not 1; uzama şartı aranmaz", "Selüloz asetat demeti"],
  ["55.03", "Sentetik devamsız lifler (karde edilmemiş)", "Yeknesak boy; ≤ 2 m demet dahil", "Balya halinde poliester elyaf"],
  ["55.04", "Suni devamsız lifler (karde edilmemiş)", "55.03 ile aynı, suni", "Balya halinde viskoz elyaf"],
  ["55.05", "Sentetik ve suni lif döküntüleri", "Tarak, iplik, ditme döküntüsü", "Akrilik iplik döküntüsü"],
  ["55.06", "Sentetik devamsız lifler (karde/taranmış)", "Şerit, tops, fitil", "Akrilik tops"],
  ["55.07", "Suni devamsız lifler (karde/taranmış)", "55.06 ile aynı, suni", "Karde edilmiş viskoz şerit"],
  ["55.08", "Devamsız lif dikiş ipliği", "Not 5; perakende olsun olmasın", "Poliester devamsız lif dikiş ipliği"],
  ["55.09", "Sentetik devamsız lif ipliği (perakende değil)", "Dikiş ipliği hariç", "Akrilik iplik, poliester-pamuk iplik"],
  ["55.10", "Suni devamsız lif ipliği (perakende değil)", "Dikiş ipliği hariç", "Viskoz devamsız lif ipliği"],
  ["55.11", "Devamsız lif ipliği (perakende)", "Bölüm XI Not 4", "Örgü için akrilik yumak"],
  ["55.12", "Sentetik devamsız lif mensucatı (≥ %85)", "Oran şartı", "%100 poliester devamsız lif kumaş"],
  ["55.13", "%85’ten az, pamuklu, ≤ 170 g/m²", "Oran + pamuk + ağırlık", "%65 poliester – %35 pamuk gömleklik"],
  ["55.14", "%85’ten az, pamuklu, 170 g/m²’yi geçen", "Oran + pamuk + ağırlık", "Ağır poliester-pamuk kumaş"],
  ["55.15", "Sentetik devamsız lif diğer mensucatı", "Yün, viskoz, filament karışımları", "%60 poliester – %40 yün kumaş"],
  ["55.16", "Suni devamsız lif mensucatı", "Oran alt pozisyonda", "Viskoz devamsız lif kumaş"]
 ],
 "notlar": [
  ["Fasıl 55 Not 1", "55.01 ve 55.02, demet uzunluğuna eşit yeknesak uzunlukta paralel filamentlerden oluşan ve şu şartları taşıyan demetlere uygulanır: (a) demet uzunluğu 2 m’den fazla; (b) büküm metrede 5 turdan az; (c) her filament 67 desiteksten az; (d) yalnız sentetik demetlerde, çekildiğinde uzunluğunun %100’ünden fazla uzatılamayan; (e) toplam demet 20.000 desiteksten fazla. Uzunluğu 2 m’yi geçmeyen demetler 55.03 veya 55.04’tedir."],
  ["Fasıl 54 Not 2", "54.02 ve 54.03, Fasıl 55’teki sentetik veya suni filament demetlerine uygulanmaz."],
  ["Bölüm XI Not 2(A)", "Karışımda ağırlıkça üstün gelen madde esas alınır; hiçbiri üstün gelmezse, her biri geçerli olabilecek pozisyonların numara sırasına göre sonuncusu uygulanır."],
  ["Bölüm XI Not 2(B)(b)–(c)", "Önce fasıl, sonra fasıl içindeki pozisyon seçilir; o fasılda sınıflandırılmayan madde dikkate alınmaz. 54 ve 55. fasılların her ikisi bir başka fasılla ilgili olduğunda tek fasıl kabul edilir. Açıklama Notu örneği: 210 g/m², %40 pamuk + %30 suni + %30 sentetik devamsız lif → Fasıl 55 → eşitlikte son pozisyon 55.16."],
  ["Bölüm XI Not 3", "Suni veya sentetik liflerden iplik 10.000 desiteksten fazlaysa sicim, ip ve halat sayılır (56.07). Fasıl 55’teki lif demetleri bu kurala tabi değildir."],
  ["Bölüm XI Not 4–5", "Perakende iplik 55.11’dedir; tek kat iplik (yün hariç), çapraz sarılmış çile ve sanayide kullanımı gösteren mesnetteki iplik perakende sayılmaz. Dikiş ipliği (55.08): çok katlı veya kable, mesnetle 1.000 g’ı geçmeyen, aprelenmiş, “Z” bükülü."],
  ["Genel Açıklamalar", "Lifler düzeden çıkan filamentlerin demet halinde toplanıp kesilmesiyle elde edilir; kesim uzunluğu genellikle 25–180 mm’dir. Tarak, iplik ve ditme döküntüleri bu fasıldadır. Hariç: 5 mm’yi geçmeyen lifler (flok) 56.01; amyant 25.24, 68.12–68.13; karbon lifleri 68.15; cam lifleri 70.19."],
  ["55.01 Açıklama Notu", "Toplam ölçüsü 20.000 desiteksi geçmeyen veya çekilmemiş demetler 54.02; filamentleri 67 desiteks ve üzeri demetler 54.04 veya Fasıl 39; 2 m’yi geçmeyen demetler 55.03. Germe işlemi görmemiş demetler uzunluklarının üç-dört katına kadar uzayabilir; %100 şartı demetin devamsız life dönüştürülmeye hazır olduğunu gösterir."],
  ["55.03 / 55.05 Açıklama Notu", "55.03’teki lifler genellikle preslenmiş balyalar halindedir ve 55.05 döküntülerinden boylarının yeknesak oluşuyla ayrılır. 55.05: yumuşak döküntü (tarak döküntüsü), sert döküntü (iplik döküntüsü), ditme döküntüsü; ağartılmış veya boyanmış olabilir. Hariç: vatka 30.05/56.01; karde edilmiş döküntü 55.06/55.07; kırpıntı, toz, taraz 56.01; paçavra Fasıl 63."],
  ["55.06 Açıklama Notu", "Karde edilmiş, taranmış veya iplik imaline başka şekilde hazırlanmış sentetik devamsız lifler (döküntüden olanlar dahil). Bobine sarılı veya yumak halindeki taranmış şeritlere “tops” denir; tops, “tow-to-top” işlemiyle doğrudan filament demetinden de elde edilebilir. Vatkalar hariçtir."],
  ["55.13–55.15 Açıklama Notu", "55.13/55.14: ağırlıkça %85’ten az sentetik devamsız lif içeren, esas itibariyle veya sadece pamukla karışık mensucat; ayrım m² ağırlığının 170 g’ı geçip geçmemesidir. 55.15 yalnız bu fasılın önceki pozisyonlarına ve 58–59. fasıllara girmeyen karışık mensucatı kapsar."],
  ["55.12–55.16 Açıklama Notu", "Perakende satılacak hale getirilmiş veya tıbbi madde içeren bandajlar 30.05’tedir."]
 ],
 "sinir_komsulari": [
  ["Not 1’e uymayan filament demeti (≤ 20.000 dtex veya çekilmemiş)", "54.02 / 54.03", "Fasıl 54 kapsamı"],
  ["Filamentleri 67 desiteks ve üzeri demet", "54.04 / Fasıl 39", "55.01 Açıklama Notu"],
  ["Sentetik/suni filament ipliği ve mensucatı", "Fasıl 54", "Lif devamlı"],
  ["Uzunluğu 5 mm’yi geçmeyen lif kırpıntısı (flok), lif tozu, taraz", "56.01", "Fasıl 55 Genel Açıklamalar"],
  ["Vatka", "56.01 / 30.05", "55.05 ve 55.06 hariç tutmaları"],
  ["Devamsız liflerden dokunmamış mensucat; keçe", "56.03 / 56.02", "Fasıl 56 ürünleri"],
  ["Sentetik paçavralar", "Fasıl 63", "55.05 hariç tutması"],
  ["10.000 desiteksi aşan sentetik devamsız lif ipliği", "56.07", "Bölüm XI Not 3"],
  ["Pamuğun ağır bastığı poliester-pamuk karışımı", "Fasıl 52", "Bölüm XI Not 2"],
  ["Yünün ağır bastığı akrilik-yün karışımı", "Fasıl 51", "Bölüm XI Not 2"],
  ["Devamsız lif ipliğinden kadife, havlı dokuma", "58.01", "Özel dokunmuş mensucat"],
  ["Perakende bandaj", "30.05", "55.12–55.16 hariç tutmaları"],
  ["Karbon, cam, amyant lifleri", "68.15 / 70.19 / 25.24", "Fasıl 55 Genel Açıklamalar"]
 ],
 "tuzaklar": [
  "<b>Demet her zaman Fasıl 55 değildir.</b> Filament demeti ancak Not 1’in beş şartını birlikte taşırsa 55.01/55.02’ye girer; 2 m’yi geçmeyen demet 55.03/55.04’te, diğerleri Fasıl 54’te kalır.",
  "<b>Uzama şartı yalnız sentetik demette aranır.</b> “%100’den fazla uzatılamama” şartı (Not 1(d)) suni demetlere (55.02) uygulanmaz.",
  "<b>Yeknesak boy lif, karışık boy döküntü.</b> 55.03’teki lifler 55.05 döküntülerinden genellikle boylarının yeknesak oluşuyla ayrılır.",
  "<b>Karde edilen döküntü artık döküntü değildir.</b> Karde edilmiş, taranmış döküntü lifleri 55.05’ten çıkar, 55.06/55.07’ye geçer.",
  "<b>5 mm sınırı.</b> Uzunluğu 5 mm’yi geçmeyen lif kırpıntıları (flok) Fasıl 55’te değil 56.01’dedir.",
  "<b>Pamuklu karışımda ölçü 170 g/m².</b> %85’ten az sentetik devamsız lif içeren, esasen pamukla karışık kumaş 170 g/m²’yi geçmiyorsa 55.13, geçiyorsa 55.14; pamuk dışı karışımlar 55.15’e gider.",
  "<b>Suni lif kumaşı tek pozisyondur.</b> 55.16’da oran ve karışım ayrımı alt pozisyonda yapılır; sentetikteki gibi dört pozisyona bölünmez.",
  "<b>54 ve 55 birlikte tartılır.</b> Sentetik ve suni lifler, başka fasıl lifine karşı tek fasıl sayılır; örneğin %40 pamuk + %30 suni + %30 sentetik devamsız lif içeren kumaş Fasıl 55’e, eşitlik nedeniyle 55.16’ya gider.",
  "<b>Önce fasıl, sonra pozisyon.</b> Tek başına en ağır lif pamuk olsa bile sentetik ve suni liflerin toplamı pamuğu geçiyorsa eşya Fasıl 55’tedir."
 ],
 "hafiza": {
  "kanca": "DEMET – LİF – DÖKÜNTÜ – TARAK – DİKİŞ – İPLİK – PERAKENDE – KUMAŞ",
  "aciklama": "Fasıl 55 bir iplik fabrikası hattıdır: 01/02 demet, 03/04 lif, 05 döküntü, 06/07 tarak-taranmış, 08 dikiş ipliği, 09/10 iplik, 11 perakende, 12–15 sentetik kumaş, 16 suni kumaş. Çiftlerde önce sentetik, sonra suni gelir. Sentetik kumaş dört kapılıdır: “85 – pamuk ince – pamuk kalın – diğer”."
 },
 "sinav_odagi": [
  "Bu fasıl çıkmış sorularda doğrudan değil, karışım ve GYK sorularıyla dolaylı olarak yer almıştır.",
  "Sentetik lif, suni lif, ipek ve pamuk karışımından dokunmuş kumaşın hangi GYK ile sınıflandırıldığı: Bölüm XI Not 2 belirleyici olduğundan GYK 1.",
  "Ağırlıkça üstün gelen maddenin belirlenmesinde sentetik ve suni liflerin birlikte değerlendirilmesi.",
  "Seçeneklerde GYK 2(a), 2(b) ve 3(b) gibi kuralların çeldirici olarak kullanılması.",
  "Lif cinsine göre fasıl ayrımı: pamuk Fasıl 52, bitkisel lifler Fasıl 53, filament Fasıl 54, devamsız lif Fasıl 55."
 ],
 "cikmis_ornekler": [
  {
   "soru": "%35 sentetik lif, %20 suni lif, %40 ipek ve %5 pamuk karışımından dokunmuş kumaşın tarife cetvelinde sınıflandırılmasında tarifenin hangi genel yorum kuralı kullanılır?",
   "secenekler": ["3 (b)", "2 (b)", "2 (a)", "1"],
   "cevap": "D",
   "aciklama": "Sentetik ve suni lifler birlikte (%55) ipeği (%40) geçer; eşyanın yerini Bölüm XI Not 2 doğrudan belirlediğinden sınıflandırma GYK 1’e dayanır. Karışım kuralı bir bölüm notu olduğu için GYK 3(b) uygulanmaz."
  }
 ],
 "ozet": [
  "Fasıl 55 = sentetik ve suni lifin devamsız (kesilmiş) hali ve Not 1’e uyan filament demetleri.",
  "Demet 55.01/55.02 (beş şart), lif 55.03/55.04, döküntü 55.05, karde-taranmış 55.06/55.07.",
  "İplik: dikiş 55.08, sentetik 55.09, suni 55.10, perakende 55.11.",
  "Kumaş: sentetik ≥ %85 55.12; pamuklu ≤ 170 g/m² 55.13, daha ağırı 55.14; diğer 55.15; suni 55.16.",
  "5 mm’yi geçmeyen lif kırpıntısı, toz ve vatka 56.01; paçavra Fasıl 63.",
  "Karışımda 54 ve 55 tek fasıl; önce fasıl, sonra fasıl içinde en ağır lif, eşitlikte son pozisyon."
 ],
 "sorular": [
  # --- Eşya → 4'lü (5)
  S("Tarife Cetveline göre, karde edilmemiş ve taranmamış, preslenmiş balyalar halinde, 38 mm yeknesak boyda kesilmiş poliester devamsız lifleri hangi pozisyonda sınıflandırılır?",
    "55.03", ["55.05", "55.06", "54.02", "55.01"], "D", E4,
    "Karde edilmemiş, taranmamış veya iplik imali için hazırlanmamış sentetik devamsız lifler 55.03’tedir; yeknesak boy onları 55.05 döküntülerinden ayırır. Karde edilmiş veya taranmış olsaydı 55.06’ya giderdi. 55.01 Not 1’e uyan filament demetleri, 54.02 filament iplikleri içindir.",
    "55.03 pozisyon metni ve Açıklama Notu."),
  S("Tarife Cetveline göre, viskoz devamsız liflerinden elde edilmiş, perakende satış için hazırlanmamış, iki katlı ve dikiş ipliği niteliğinde olmayan iplik hangi pozisyondadır?",
    "55.10", ["55.09", "54.03", "55.11", "55.08"], "B", E4,
    "Viskoz suni liftir; suni devamsız liflerden iplikler (dikiş ipliği hariç, perakende değil) 55.10’dadır. 55.09 sentetik devamsız lif ipliği, 54.03 suni filament ipliği, 55.11 perakende iplik, 55.08 dikiş ipliği içindir.",
    "Fasıl 54 Not 1(b); 55.10 pozisyon metni."),
  S("Tarife Cetveline göre, tamamı akrilik devamsız liflerden dokunmuş, boyanmış, parça halindeki mensucat hangi pozisyondadır?",
    "55.12", ["55.15", "54.07", "55.16", "55.13"], "A", E4,
    "Ağırlık itibariyle %85 veya daha fazla sentetik devamsız lif içeren dokunmuş mensucat 55.12’dedir; akrilik sentetik liftir. 55.13 ve 55.15 %85’ten az sentetik lif içeren karışımlar, 55.16 suni devamsız lif, 54.07 sentetik filament mensucatı içindir.",
    "55.12 pozisyon metni ve Açıklama Notu."),
  S("Tarife Cetveline göre, akrilik devamsız liflerin karde edilip taranmasıyla elde edilen ve bobinlere sarılmış taranmış şerit (tops) hangi pozisyondadır?",
    "55.06", ["55.03", "55.07", "55.05", "55.09"], "E", E4,
    "Karde edilmiş, taranmış veya iplik imali için başka şekilde hazırlanmış sentetik devamsız lifler 55.06’dadır; bobine sarılı taranmış şeritler “tops” olarak adlandırılır. 55.03 karde edilmemiş lif, 55.07 suni lif, 55.05 döküntü, 55.09 iplik içindir; tops henüz bükülmemiştir.",
    "55.06 Açıklama Notu."),
  S("Tarife Cetveline göre, viskoz devamsız lif ipliklerinin bükme ve dokuma işlemleri sırasında ortaya çıkan, boyanmış, karde edilmemiş kopuk ve dolaşık iplik döküntüleri hangi pozisyondadır?",
    "55.05", ["55.04", "55.07", "56.01", "55.10"], "C", E4,
    "Bükme, sarma, dokuma gibi işlemler sırasında oluşan kopuk, düğümlü veya dolaşık iplikler “sert döküntü” olarak 55.05’tedir; karde edilmedikçe ağartılmış veya boyanmış olmaları yerlerini değiştirmez. 55.04 yeknesak boylu lif, 55.07 karde edilmiş lif, 56.01 kırpıntı-toz-taraz içindir.",
    "55.05 Açıklama Notu."),
  # --- Olumsuz teşhis (4)
  S("Aşağıdakilerden hangisi Tarife Cetvelinin 55. faslında <b>sınıflandırılmaz</b>?",
    "Uzunluğu 3 mm olan poliamid lif kırpıntıları (flok)",
    ["Poliester tarak döküntüleri", "Akrilik paçavraların ditilmesiyle elde edilen lifler",
     "Karde edilmiş viskoz lif şeridi", "Viskoz devamsız liflerden dokunmuş kumaş"], "C", OT,
    "Fasıl 55 Genel Açıklamaları, uzunluğu 5 mm’yi geçmeyen dokumaya elverişli lifleri (flok) hariç tutar; bunlar 56.01’dedir. Tarak döküntüsü ve paçavraların ditilmesiyle elde edilen lifler 55.05’te, karde edilmiş viskoz şerit 55.07’de, viskoz devamsız lif kumaşı 55.16’dadır.",
    "Fasıl 55 Genel Açıklamalar; 56.01 Açıklama Notu (B)."),
  S("Aşağıdakilerden hangisi 55.05 pozisyonunda <b>sınıflandırılmaz</b>?",
    "Karde edilerek iplik imaline hazırlanmış poliester döküntü lifleri",
    ["Ağartılmış akrilik tarak döküntüsü",
     "Dokuma sırasında oluşan kopuk, düğümlü naylon iplik döküntüleri",
     "Boyanmış viskoz lif döküntüleri",
     "Poliester ipliklerin ditilmesiyle elde edilen lifler"], "A", OT,
    "Karde edilmiş, taranmış veya iplik imali için hazırlanmış döküntü lifler 55.05’in hariç tuttuğu eşyadır; sentetik olanlar 55.06’dadır. Ağartılmış veya boyanmış tarak döküntüleri, iplik döküntüleri ve ditme döküntüleri karde edilmedikçe 55.05’te kalır.",
    "55.05 ve 55.06 Açıklama Notları."),
  S("Aşağıdaki dokunmuş mensucattan hangisi 55.15 pozisyonunda <b>yer almaz</b>?",
    "Ağırlık itibariyle %70 poliester devamsız lif ve %30 pamuk içeren, 150 g/m² mensucat",
    ["Ağırlık itibariyle %60 poliester devamsız lif ve %40 yün içeren mensucat",
     "Ağırlık itibariyle %55 poliester devamsız lif ve %45 viskoz devamsız lif içeren mensucat",
     "Ağırlık itibariyle %70 akrilik devamsız lif ve %30 yün içeren mensucat",
     "Ağırlık itibariyle %75 poliester devamsız lif ve %25 naylon filament içeren mensucat"], "E", OT,
    "%85’ten az sentetik devamsız lif içeren ve esasen pamukla karışık, 170 g/m²’yi geçmeyen mensucat 55.13’tedir. 55.15 ise sentetik devamsız liflerin ağır bastığı ama pamuk dışındaki liflerle (yün, viskoz devamsız lif, filament) karışık olan ve önceki pozisyonlara girmeyen mensucatı kapsar.",
    "55.13 ve 55.15 pozisyon metinleri ve Açıklama Notları; Bölüm XI Not 2."),
  S("Aşağıdaki ipliklerden hangisi 55.11 pozisyonunda <b>sınıflandırılmaz</b>?",
    "Dokuma sanayiinde kullanılacağını gösteren konik bobine sarılı, 80 g’lık, iki katlı akrilik devamsız lif ipliği",
    ["Mesnetle birlikte 50 g’lık makaraya sarılı, boyanmış, iki katlı poliester devamsız lif ipliği",
     "40 g’lık yumak halinde, boyanmış, iki katlı akrilik devamsız lif ipliği",
     "Ayırıcı ipliklerle 25’er gramlık eşit küçük çilelere bölünmüş, boyanmış, iki katlı viskoz devamsız lif ipliği",
     "60 g’lık kartona sarılı, ağartılmış, kable akrilik devamsız lif ipliği"], "B", OT,
    "Bölüm XI Not 4(B)(d) uyarınca büküm makinesi tüpleri, masura, bobin veya konik bobin gibi mensucat sanayiinde kullanımı gösteren mesnetlere sarılı iplikler ağırlığı ne olursa olsun perakende sayılmaz; bu iplik 55.09’dadır. Küçük makara, yumak, ayırıcı iplikli küçük çile ve karton üzerindeki boyalı-ağartılmış çok katlı iplikler 55.11’dedir.",
    "Bölüm XI Not 4; 55.11 Açıklama Notu."),
  # --- Farklı/aynı (4)
  S("Aşağıdaki dokunmuş mensucattan hangisi diğerlerinden <b>farklı</b> bir pozisyonda sınıflandırılır?",
    "Ağırlık itibariyle %60 poliester devamsız lif ve %40 viskoz devamsız lif içeren mensucat",
    ["Tamamı viskoz devamsız liften mensucat",
     "Ağırlık itibariyle %60 viskoz devamsız lif ve %40 pamuk içeren mensucat",
     "Ağırlık itibariyle %50 viskoz devamsız lif ve %50 yün içeren mensucat",
     "Ağırlık itibariyle %80 viskoz devamsız lif ve %20 naylon filament içeren mensucat"], "D", FA,
    "Poliester (sentetik) devamsız lif viskozdan (suni) ağır bastığı için ilk mensucat sentetik devamsız lif mensucatı olarak 55.15’tedir. Diğerlerinde suni devamsız lif üstündür veya %50-%50 eşitlikte numara sırasına göre son pozisyon (yün mensucata karşı 55.16) uygulanır; hepsi 55.16’dadır.",
    "Bölüm XI Not 2(A) ve 2(B)(b); 55.15 ve 55.16 pozisyon metinleri."),
  S("Aşağıdaki eşya çiftlerinden hangisinin her ikisi de <b>aynı</b> pozisyonda yer alır?",
    "Poliester devamsız lif dikiş ipliği – Viskoz devamsız lif dikiş ipliği",
    ["Karde edilmemiş viskoz devamsız lif – Karde edilmemiş poliester devamsız lif",
     "Poliester tarak döküntüsü – Karde edilmiş poliester döküntü lifi",
     "Akrilik devamsız lif ipliği – Akrilik filament ipliği (ikisi de perakende değil)",
     "Sentetik devamsız lif dikiş ipliği – Sentetik filament dikiş ipliği"], "B", FA,
    "55.08 sentetik ve suni devamsız liflerden dikiş ipliğini birlikte kapsar. Karde edilmemiş viskoz 55.04, poliester 55.03; tarak döküntüsü 55.05, karde edilmiş döküntü 55.06; akrilik devamsız lif ipliği 55.09, filament ipliği 54.02; filament dikiş ipliği 54.01’dedir.",
    "55.08 pozisyon metni; 55.03–55.06, 55.09 ve 54.01, 54.02 pozisyon metinleri."),
  S("Aşağıdakilerden hangisi diğerlerinden <b>farklı</b> bir fasılda yer alır?",
    "Poliester devamsız liflerden elde edilmiş dokunmamış mensucat",
    ["Poliester devamsız lif döküntüleri",
     "Fasıl 55 Not 1 şartlarını taşıyan selüloz asetat filament demeti",
     "Akrilik tops", "Perakende satış için hazırlanmış viskoz devamsız lif ipliği"], "E", FA,
    "Dokunmamış mensucat, lifi ne olursa olsun 56.03’tedir. Lif döküntüsü 55.05’te, Not 1’e uyan suni filament demeti 55.02’de, akrilik tops 55.06’da, perakende devamsız lif ipliği 55.11’de olup Fasıl 55’tedir.",
    "56.03 pozisyon metni; 55.02, 55.05, 55.06, 55.11 pozisyon metinleri."),
  S("Aşağıdaki dokunmuş mensucattan hangisi, diğerlerinden farklı olarak 55. fasıl <b>dışında</b> sınıflandırılır?",
    "Ağırlık itibariyle %55 pamuk, %25 poliester devamsız lif ve %20 viskoz devamsız lif içeren mensucat",
    ["Ağırlık itibariyle %40 pamuk, %35 poliester devamsız lif ve %25 viskoz devamsız lif içeren mensucat",
     "Ağırlık itibariyle %45 yün, %30 akrilik devamsız lif ve %25 viskoz devamsız lif içeren mensucat",
     "Ağırlık itibariyle %50 pamuk ve %50 poliester devamsız lif içeren mensucat",
     "Ağırlık itibariyle %48 keten ve %52 viskoz devamsız lif içeren mensucat"], "A", FA,
    "Sentetik ve suni lifler toplanır (%45) ama pamuğu (%55) geçemez; eşya Fasıl 52’dedir. Diğerlerinde sentetik ve suni liflerin toplamı diğer lifi aşar (%60, %55, %52) ya da %50-%50 eşitlikte numara sırasına göre son fasıl olan 55 seçilir.",
    "Bölüm XI Not 2(A) ve 2(B)(b)–(c)."),
  # --- Fasıl notu · Tanım/Eşik (4)
  S("Fasıl 55 Not 1’e göre aşağıdakilerden hangisi 55.01 ve 55.02 kapsamındaki filament demetlerinin şartlarından biri <b>değildir</b>?",
    "Demet uzunluğunun 2 m’yi geçmemesi",
    ["Demet bükümünün metre başına 5 turdan az olması",
     "Her bir filamentin 67 desiteksten az olması",
     "Toplam demet ölçüsünün 20.000 desiteksten fazla olması",
     "Sentetik demetlerde, çekildiğinde uzunluğunun %100’ünden fazla uzatılamaması"], "C", FN,
    "Not 1(a), demet uzunluğunun 2 m’den <b>fazla</b> olmasını arar; 2 m’yi geçmeyen demetler 55.03 veya 55.04’e gider. Metrede 5 turdan az büküm, 67 desiteksten az filament, 20.000 desiteksten fazla toplam ölçü ve (yalnız sentetikte) %100 uzama sınırı Not 1’in diğer şartlarıdır.",
    "Fasıl 55 Not 1."),
  S("Fasıl 55 Not 1’deki “çekildiğinde kendi uzunluğunun %100’ünden fazla uzatılamama” şartı ile ilgili aşağıdakilerden hangisi <b>doğrudur</b>?",
    "Yalnız sentetik filament demetleri için aranır; suni filament demetlerinde aranmaz.",
    ["Hem sentetik hem suni filament demetleri için aranır.",
     "Yalnız suni filament demetleri için aranır.",
     "55.03’teki 2 m’yi geçmeyen demetler için de aranır.",
     "Germe işlemi görmemiş demetlerin bu şartı karşıladığı kabul edilir."], "D", FN,
    "Not 1(d) şartı “sadece sentetik filament demetleri söz konusu olduğunda” uygulanır; 55.02 Açıklama Notu da Not 1(d)’yi suni demetler için dışarıda bırakır. Şart, demetin germe işlemiyle devamsız life dönüştürülmeye hazır olduğunu gösterir; germe görmemiş demetler üç-dört katına kadar uzayabilir. 2 m’yi geçmeyen demetlerde bu şart aranmaz.",
    "Fasıl 55 Not 1(d); 55.01 ve 55.02 Açıklama Notları."),
  S("55.13 ve 55.14 pozisyonlarını birbirinden ayıran ölçüt hangisidir?",
    "Mensucatın m² ağırlığının 170 g’ı geçip geçmemesi",
    ["Sentetik devamsız lif oranının %85’i geçip geçmemesi",
     "Mensucatın m² ağırlığının 200 g’ı geçip geçmemesi",
     "Mensucatın boyalı veya baskılı olması",
     "Karışımdaki ikinci lifin pamuk veya yün olması"], "A", FN,
    "Her iki pozisyon da %85’ten az sentetik devamsız lif içeren ve esasen pamukla karışık mensucatı kapsar; 55.13 m² ağırlığı 170 g’ı geçmeyenler, 55.14 geçenler içindir. 200 g/m² ölçüsü pamuk mensucat pozisyonlarına aittir; renk durumu alt pozisyon ayrımıdır.",
    "55.13 ve 55.14 pozisyon metinleri."),
  S("Bölüm XI Not 3’e göre sentetik veya suni devamsız liflerden bir ipliğin “sicim, ip ve halat” sayılması için ölçüsü hangi değeri aşmalıdır?",
    "10.000 desiteks",
    ["20.000 desiteks", "1.429 desiteks", "5.000 desiteks", "3.000 desiteks"], "E", FN,
    "Not 3(A)(b) suni veya sentetik liflerden ipliklerde sınırı 10.000 desiteks olarak koyar; aşan iplik 56.07’dedir. 20.000 desiteks ipek ve bitkisel lifler (ve filament demetinin toplam ölçüsü), 1.429 desiteks cilalı keten-kendir için geçerlidir.",
    "Bölüm XI Not 3(A)(b)."),
  # --- GYK (2)
  S("Ağırlık itibariyle %40 pamuk, %32 viskoz devamsız lif ve %28 poliester devamsız liften dokunmuş, 190 g/m² ağırlığındaki parça halinde mensucatın pozisyonu ve dayandığı kural hangi seçenekte doğru verilmiştir?",
    "55.16 – GYK 1 (Bölüm XI Not 2 uyarınca)",
    ["52.10 – GYK 1 (Bölüm XI Not 2 uyarınca)", "55.13 – GYK 1 (Bölüm XI Not 2 uyarınca)",
     "55.16 – GYK 3(c)", "52.10 – GYK 3(b)"], "C", GY,
    "Suni ve sentetik devamsız lifler aynı fasılda toplanır (%60) ve pamuğu (%40) geçer; Fasıl 55 seçilir. Fasıl içinde viskoz (%32) poliesterden (%28) ağır olduğundan suni devamsız lif mensucatı 55.16 uygulanır. Karar Bölüm XI Not 2’den çıktığı için dayanak GYK 1’dir; 55.13 sentetik lifin ağır bastığı pamuklu karışımlar içindir.",
    "Bölüm XI Not 2(A), 2(B)(b); GYK 1."),
  S("Bölüm XI Genel Açıklamalarına göre, dokumaya elverişli maddeler ile dokumaya elverişli olmayan maddelerden oluşan bir karışım ürüne Bölüm XI Not 2’deki ağırlık kuralı hangi durumda uygulanabilir?",
    "Ürün, Tarifenin Yorumuna ilişkin Genel Kurallara göre tekstil ürünü sayılıyorsa",
    ["Dokumaya elverişli maddelerin ağırlık oranı %50’yi geçiyorsa",
     "Her durumda; dokumaya elverişli olmayan madde de ağırlık hesabına katılarak",
     "Hiçbir durumda; bu ürünler daima GYK 3(c)’ye göre sınıflandırılır",
     "Yalnızca ürün perakende satış için hazırlanmışsa"], "B", GY,
    "Genel Açıklamalara göre Not 2’nin dokumaya elverişli ve elverişli olmayan maddelerden karışım ürüne uygulanması, ancak bu ürünün Genel Yorum Kurallarına göre tekstil ürünü sayılması halinde mümkündür. Önce GYK ile ürünün tekstil eşyası olup olmadığı belirlenir; Not 2 yalnızca dokumaya elverişli maddeler arasındaki ağırlık karşılaştırmasıdır.",
    "Bölüm XI Genel Açıklamalar (I)(A)."),
  # --- Eşleştirme / Boşluk (2)
  S("Aşağıdaki eşya – pozisyon eşleştirmelerinden hangisi <b>yanlıştır</b>?",
    "Karde edilmiş poliester döküntü lifi – 55.05",
    ["Fasıl 55 Not 1’e uyan akrilik filament demeti – 55.01",
     "Viskoz devamsız lif dikiş ipliği – 55.08",
     "Tamamı viskoz devamsız liften dokunmuş mensucat – 55.16",
     "Karde edilmemiş naylon devamsız lif – 55.03"], "D", ES,
    "Karde edilmiş döküntü lifler 55.05’ten çıkar; sentetik olanlar 55.06’dadır. Not 1’e uyan sentetik demet 55.01, devamsız lif dikiş ipliği 55.08, suni devamsız lif mensucatı 55.16, karde edilmemiş sentetik devamsız lif 55.03 ile doğru eşleşmiştir.",
    "55.05 ve 55.06 Açıklama Notları; Fasıl 55 Not 1."),
  S("“Ağırlık itibariyle %85’ten az sentetik devamsız lif içeren ve esas itibariyle pamukla karışık dokunmuş mensucat, m² ağırlığı 170 g’ı geçmiyorsa ..... , geçiyorsa ..... pozisyonunda; sentetik devamsız liflerin pamuk dışındaki liflerle karışık olanları ise ..... pozisyonunda sınıflandırılır.” Boşluklara sırasıyla gelmesi gerekenler hangisidir?",
    "55.13 – 55.14 – 55.15",
    ["55.14 – 55.13 – 55.15", "55.12 – 55.13 – 55.16", "55.13 – 55.14 – 55.16", "52.10 – 52.11 – 55.15"], "C", ES,
    "55.13 m² ağırlığı 170 g’ı geçmeyen, 55.14 geçen pamuklu karışımları kapsar; pamuk dışındaki karışımlar 55.15’tedir. 55.12 %85 ve üzeri sentetik devamsız lif, 55.16 suni devamsız lif mensucatı içindir; sentetik lif ağır bastığı için pamuk pozisyonları söz konusu olmaz.",
    "55.13, 55.14, 55.15 pozisyon metinleri ve Açıklama Notları."),
  # --- Çoktan-çoğa (2)
  SX("Fasıl 55 Açıklama Notlarına göre aşağıdaki ifadelerden hangileri <b>doğrudur</b>? I. Sentetik ve suni liflerin kesim uzunlukları genellikle 25 mm ile 180 mm arasındadır. II. 55.03’teki lifler 55.05’teki döküntülerden genellikle boylarının yeknesak oluşuyla ayırt edilir. III. Sentetik liflerden vatkalar 55.05 veya 55.06’da sınıflandırılır. IV. Taranmış şeritlerin bobine sarılmış veya yumak haline getirilmiş olanlarına “tops” denir.",
     ["I ve III", "II ve IV", "I, II ve III", "I, II ve IV", "II, III ve IV"], "D", CC,
     "I, II ve IV Açıklama Notlarında aynen yer alır. III yanlıştır: vatkalar 55.05 ve 55.06’dan açıkça hariç tutulmuş olup 30.05 veya 56.01’dedir.",
     "Fasıl 55 Genel Açıklamalar; 55.03, 55.05, 55.06 Açıklama Notları."),
  SX("Aşağıdakilerden hangileri 55. fasılda sınıflandırılır? I. Uzunluğu 2 m’yi geçmeyen, her bir filamenti 67 desiteksten az sentetik filament demeti II. Uzunluğu 5 mm’yi geçmeyen akrilik lif kırpıntıları III. “Tow-to-top” yöntemiyle filament demetinden doğrudan elde edilmiş poliester tops IV. Toplam ölçüsü 20.000 desiteksi geçmeyen, 3 m uzunluğunda poliester filament demeti",
     ["I ve II", "I ve III", "II ve IV", "I, III ve IV", "II, III ve IV"], "B", CC,
     "2 m’yi geçmeyen demet (I) 55.03’te, tow-to-top ile elde edilen tops (III) 55.06’dadır. 5 mm’yi geçmeyen kırpıntılar (II) 56.01’e, toplam ölçüsü 20.000 desiteksi geçmeyen demet (IV) Not 1’i karşılamadığından 54.02’ye gider.",
     "Fasıl 55 Not 1; 55.01, 55.03, 55.06 Açıklama Notları; Fasıl 55 Genel Açıklamalar."),
  # --- Senaryo (2)
  S("Bir konfeksiyon firması; ağırlık itibariyle %65 poliester devamsız lif ve %35 pamuktan oluşan, bez ayağı dokunmuş, boyanmış, m² ağırlığı 120 g olan, top halinde gömleklik kumaş ithal etmektedir. Kumaş hangi pozisyonda sınıflandırılır?",
    "55.13", ["55.14", "52.10", "55.12", "55.15"], "A", SN,
    "Poliester ağır bastığından kumaş Fasıl 55’tedir; sentetik devamsız lif oranı %85’ten azdır, karışım esasen pamukladır ve m² ağırlığı 170 g’ı geçmez: 55.13. 170 g’ı geçseydi 55.14, oran %85 ve üzeri olsaydı 55.12 olurdu; 55.15 pamuk dışı karışımlar içindir.",
    "Bölüm XI Not 2; 55.13 pozisyon metni ve Açıklama Notu."),
  S("Bir firma; ağırlık itibariyle %50 akrilik devamsız lif ve %50 taranmış yünden dokunmuş, parça halinde paltoluk kumaş ithal etmektedir. Kumaş hangi pozisyonda sınıflandırılır?",
    "55.15", ["51.12", "55.12", "55.14", "55.16"], "E", SN,
    "Hiçbir lif ağırlıkça üstün gelmediğinden Bölüm XI Not 2(A) ikinci paragrafı uygulanır: eşya, geçerli olabilecek pozisyonların (taranmış yün mensucatı ile sentetik devamsız lif mensucatı) numara sırasına göre sonuncusunda sınıflandırılır. Akrilik %85’ten az olup yünle karışık olduğundan 55.15’tir; 55.12 %85 şartını, 55.14 pamuk karışımını, 55.16 suni lifi gerektirir.",
    "Bölüm XI Not 2(A); 55.15 pozisyon metni.")
 ]
}

yaz(d, 55)
