import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from yardim_48_52 import *  # noqa

obj = {
 "tur": "fasil",
 "fasil": 49,
 "baslik": "Basılı kitaplar, gazeteler, resimler ve baskı sanayinin diğer mamulleri; el ve makina yazısı metinler ve planlar",
 "bolum": "X",
 "oz": {
  "vurgu": "Fasıl 49’un tek sorusu şudur: Eşyanın esas karakterini ve kullanımını üzerindeki baskı (metin, motif, resim) mı belirliyor? Evetse eşya Fasıl 49’dadır ve sonra türüne göre (kitap, gazete, çocuk kitabı, nota, harita, plan, kıymetli evrak, çıkartma, kart, takvim, diğer) pozisyonu bulunur. Baskı teferruat ise eşya malzemesinin faslında (kağıtsa Fasıl 48) kalır.",
  "maddeler": [
   "“Baskılı” geniş yorumlanır: teksir, bilgisayar çıktısı, kabartma, fotoğraf, fotokopi, termokopi ve daktilo da baskıdır (Not 2); el yazısı metinler ve elle çizilmiş planlar da bu fasıldadır (49.06).",
   "Kitap 49.01, gazete-periyodik 49.02; reklam ağırlıklı yayın ve ticari katalog ise 49.01’e değil 49.11’e gider (Not 5).",
   "Eşya kağıt dışında (tekstil, plastik) bir malzemeye basılmış olabilir; ancak kabartma haritalar 90.23’e, oyun kağıtları Fasıl 95’e, orijinal gravürler ve koleksiyon pulları Fasıl 97’ye gider (Not 1).",
   "49.11 artık pozisyondur: reklam yayınları, biletler, formlar, resimler-fotoğraflar, stickerlar, piyango biletleri."
  ]
 },
 "karar_tablosu": {
  "aciklama": "Soruları yukarıdan aşağıya sırayla sorun; ilk “evet” cevabı pozisyonu verir.",
  "satirlar": [
   ["1", "Fasıl 49 Not 1’de hariç tutulmuş mu? (saydam negatif, kabartma harita-küre, oyun kağıdı, orijinal gravür, koleksiyon pulu, antika)", "Fasıl 37 · <b>90.23</b> · Fasıl 95 · <b>97.02</b> · <b>97.04</b>"],
   ["2", "Baskı eşyanın asıl kullanımında teferruat mı? (kırtasiye, ambalaj kağıdı, duvar kağıdı, etiket, baskılı tekstil)", "Fasıl 48 (<b>48.14</b>, <b>48.17</b>, <b>48.20</b>, <b>48.21</b>…) · tekstil ise Bölüm XI"],
   ["3", "Tedavüldeki kullanılmamış pul, damgalı kağıt, banknot, çek defteri, hisse senedi, tahvil mi?", "<b>49.07</b>"],
   ["4", "Gazete veya periyodik yayın mı (tarihli, numaralı, ciltsiz veya kağıt kapaklı tek sayı)?", "<b>49.02</b> (başka şekilde ciltli veya tek kapakta birden fazla sayı ise <b>49.01</b>)"],
   ["5", "Resimleri metne üstün çocuk kitabı ya da resim-boyama kitabı mı?", "<b>49.03</b> (kesilecek model sayfaların yarısını aşarsa Fasıl 95)"],
   ["6", "Müzik notası mı (basılı veya elle yazılmış)?", "<b>49.04</b>"],
   ["7", "Basılı harita, atlas, küre, topografya planı mı?", "<b>49.05</b>"],
   ["8", "Elle çizilmiş orijinal plan-çizim veya el yazması metin ya da bunların karbon kopyası, hassas kağıda fotoğrafik reprodüksiyonu mu?", "<b>49.06</b>"],
   ["9", "Çıkartma mı?", "<b>49.08</b>"],
   ["10", "Basılı veya resimli kartpostal, tebrik, davetiye, teşekkür kartı mı?", "<b>49.09</b>"],
   ["11", "Takvim mi (blok takvim dahil)?", "<b>49.10</b>"],
   ["12", "Kitap, broşür, risale mi (reklam ağırlıklı değil)?", "<b>49.01</b> · reklam, katalog, bilet, form, resim, sticker → <b>49.11</b>"]
  ],
  "dipnot": "* Seramik, cam veya adi metalden, üzerinde basılı yazı veya resim bulunan dükkan levhaları ve vitrin harfleri sırasıyla 69.14, 70.20 ve 83.10’da; ışıklı ise 94.05’tedir."
 },
 "pozisyon_haritasi": [
  ["49.01", "Kitaplar, broşürler, risaleler", "Okuma materyali; reklam ağırlıklı değil", "Ders kitabı, sözlük, telefon rehberi"],
  ["49.02", "Gazeteler ve periyodik yayınlar", "Düzenli aralık, aynı isim, tarih ve numara", "Günlük gazete, aylık dergi"],
  ["49.03", "Çocuk resimli kitapları; resim-boyama albümleri", "Resim metne üstün (Not 6)", "Resimli alfabe, boyama kitabı"],
  ["49.04", "Müzik notaları", "Basılı veya el yazması", "Nota kitabı, partisyon"],
  ["49.05", "Basılı haritalar, atlaslar, küreler", "Basılı; kabartma değil", "Atlas, yol haritası, dünya küresi"],
  ["49.06", "Elle çizilmiş planlar; el yazması metinler", "Orijinal veya karbon kopya, fotoğrafik reprodüksiyon", "Mimari proje, el yazması"],
  ["49.07", "Pul, damgalı kağıt, banknot, çek, senet", "Tedavülde itibari değer", "Posta pulu, çek defteri, hisse senedi"],
  ["49.08", "Her nevi çıkartmalar", "Yüzeye aktarılan baskı", "Cam çıkartması, ütüyle aktarılan çıkartma"],
  ["49.09", "Kartpostallar; tebrik, davetiye, teşekkür kartları", "Basılı veya resimli; kişisel mesaj", "Resimli kartpostal, yılbaşı kartı"],
  ["49.10", "Matbu takvimler", "Esas karakter takvim; blok dahil", "Duvar takvimi, koparmalı blok takvim"],
  ["49.11", "Diğer matbu yayınlar; resimler, fotoğraflar", "Artık pozisyon", "Katalog, afiş, bilet, form, sticker"]
 ],
 "notlar": [
  ["Fasıl 49 Not 1", "Fasıl dışı: saydam mesnetli negatif ve pozitif fotoğraflar (Fasıl 37); baskılı olsun olmasın <b>rölyef</b> (kabartma) haritalar, planlar ve küreler (90.23); oyun kağıtları ve Fasıl 95’in diğer eşyası; orijinal gravür, estamp ve litograflar (97.02); 97.04’teki posta, damga ve harç pulları, posta damgalı zarflar, ilk gün zarfları ve benzerleri; yüz yılı aşan antikalar ve Fasıl 97’nin diğer eşyası."],
  ["Fasıl 49 Not 2", "“Baskılı” tabiri; teksir makinesiyle çoğaltılmış, otomatik bilgi işlem makinesinin kontrolünde üretilmiş, kabartılmış, fotoğrafı çekilmiş, fotokopi veya termokopi edilmiş ya da daktilo edilmiş anlamını da kapsar."],
  ["Fasıl 49 Not 3", "Kağıttan başka şekilde ciltlenmiş gazete ve periyodik yayınlar ile tek kapak içinde birden fazla sayıdan oluşan takımlar, reklam içersin içermesin <b>49.01</b>’dedir."],
  ["Fasıl 49 Not 4", "49.01 ayrıca: (a) numaralı sayfalı, ciltlenmeye elverişli, eser ve sanatçıları hakkında metin içeren sanat eseri reprodüksiyonu koleksiyonları; (b) kitapla birlikte bulunan ve onu tamamlayan resimli ilaveler; (c) bir eserin tamamını veya bir kısmını oluşturan, ciltlenmek üzere fasikül veya ayrı sayfalar halindeki kitapları kapsar. Ancak forma veya ayrı sayfa halindeki <b>metinsiz</b> gravür ve resimler 49.11’dedir."],
  ["Fasıl 49 Not 5", "Not 3 saklı kalmak üzere, esasen reklama ayrılmış yayınlar (broşür, prospektüs, ticari katalog, ticari birlik yıllıkları, turistik tanıtım) 49.01’e girmez; <b>49.11</b>’dedir."],
  ["Fasıl 49 Not 6", "49.03 anlamında “çocuklar için resimli albüm ve kitaplar”: resimleri yazılı metne nazaran çocukların öncelikli ilgisini çeken kitaplardır; metin tali olmalıdır."],
  ["Genel Açıklamalar", "Fasıl, esas karakteri ve kullanımı baskı ile belirlenen eşyayı kapsar. Baskısı teferruat olan kağıt eşya (sargılık kağıt, kırtasiye) Fasıl 48’de; süs amaçlı baskılı tekstil (eşarp, mendil) Bölüm XI’de kalır. 39.18, 39.19, 48.14 ve 48.21 eşyası baskılı olsa da bu fasıl dışındadır. Renklendirme veya tekrarlı dekoratif desen baskısı “baskı” sayılmaz. Işık geçirmez mesnet üzerindeki mikrokopiler 49.11’dedir."],
  ["49.01 Açıklama Notu", "Ders kitapları (soru ve alıştırma içeren çalışma kitapları dahil), sözlük, ansiklopedi, telefon rehberi, müze ve kütüphane katalogları, dua kitapları buradadır. Kitapla birlikte sunulan toz kılıfı ve kitap ayracı kitabın parçasıdır. Ciltsiz gazete 49.02, çocuk çalışma kitabı 49.03, müzik kitabı 49.04, atlas 49.05’tedir."],
  ["49.02 Açıklama Notu", "Belirli aralıklarla, aynı isimle, tarih ve genellikle sıra numarası taşıyarak yayımlanır; ciltsiz veya kağıt kapaklıdır. Haftalık fasiküllerle tamamlanan ansiklopediler 49.01’de; gazete ve dergilerin eski nüshaları kağıt döküntüsü olarak 47.07’dedir. Firma personel dergileri ve tanıtım amaçlı moda dergileri de 49.02’dedir."],
  ["49.03 Açıklama Notu", "Seçilmiş olayların resimleriyle sürekli öykü biçiminde yazılmış kitaplar 49.01’dedir. Kapaklar dahil sayfaların <b>yarısından fazlası</b> kesilecek modelden oluşuyorsa kitap oyuncak sayılır (Fasıl 95). Bezden çocuk kitapları ve az miktarda sulu boyalı albümler 49.03’tedir."],
  ["49.07 Açıklama Notu", "Tedavülde veya tedavüle çıkacak, ülkesinde itibari değeri olan kullanılmamış pullar buradadır; tedavülde olmayan pullar 97.04’te, koleksiyon banknotları 97.05’tedir. İndirim kuponu ve hayır pulları ile seri numaralı, güvenlikli kağıda basılmış piyango biletleri 49.11’dedir."],
  ["49.09 – 49.10 Açıklama Notları", "Kartpostal olarak kullanılacağını gösteren basılı işareti olmayan resimli kartlar resim olarak 49.11’de; posta pulu basılı posta kartları 49.07’de; baskısı önemsiz düz kartpostallar 48.17’de; takvim şeklindeki yılbaşı kartları 49.10’dadır. Takvimli hatıra defterleri 48.20’de; blok takvimi olmayan takvim arkalıkları 49.11’dedir."],
  ["49.11 Açıklama Notu", "Çerçeveli resim ve fotoğraf, esas karakteri resim veriyorsa 49.11’de, aksi halde çerçevenin malzemesine göre sınıflandırılır. Basılı formlar, biletler, sirkülerler, kimlik kartları, anatomi şemaları, şematik haritalar ve kendinden yapışkanlı dekoratif stickerlar 49.11’dedir; akıllı kartlar 85.23’tedir."]
 ],
 "sinir_komsulari": [
  ["Mikrofilm, saydam mesnetli negatif", "Fasıl 37", "Fasıl 49 Not 1(a)"],
  ["Kabartma (rölyef) harita, plan veya küre", "90.23", "Not 1(b); baskılı olsa da"],
  ["Oyun kağıdı; çocukların kesip çıkardığı baskılı kağıt oyuncak", "Fasıl 95", "Not 1(c); 49.11 hariç tutmaları"],
  ["Orijinal gravür ve litograf", "97.02", "Not 1(d)"],
  ["Tedavülde olmayan pul; pullu ilk gün zarfı", "97.04", "Not 1(d); 49.07 Açıklama Notu"],
  ["Ajanda, takvimli hatıra defteri, iş formu (baskı tali)", "48.20", "Baskı asıl kullanımda tali"],
  ["Baskılı etiket; duvar kağıdı", "48.21 / 48.14", "Baskılı olsa da Fasıl 48 (Fasıl 48 Not 12)"],
  ["Adres-pul yeri basılı düz kartpostal", "48.17", "49.09 hariç tutmaları"],
  ["Satılmamış eski gazete", "47.07", "49.02 Açıklama Notu"],
  ["Harita basılı eşarp veya mendil", "Bölüm XI", "49.05 hariç tutma (e)"],
  ["Basılı yazılı adi metal dükkan levhası; ışıklı reklam levhası", "83.10 / 94.05", "Fasıl Genel Açıklamalar"],
  ["Istampacılık varakları; litografya transfer kağıtları", "32.12 / 48.09–48.16", "49.08 Açıklama Notu"],
  ["Mekanik müzik aletleri için delikli nota rulosu", "92.09", "49.04 hariç tutmaları"],
  ["Akıllı kart (yakınlık kartı dahil)", "85.23", "49.11 hariç tutmaları"]
 ],
 "tuzaklar": [
  "<b>Kabartma harita Fasıl 49 değildir.</b> Basılı olsa bile rölyef haritalar, planlar ve küreler 90.23’tedir; düz basılı harita ve küre 49.05’tedir.",
  "<b>Reklamlı gazete yine gazetedir.</b> Gazete ve periyodik yayınlar reklam içerse de 49.02’dedir; ancak reklama ayrılmış broşür ve ticari kataloglar 49.11’e gider (Not 5).",
  "<b>Cilt gazeteyi kitaba çevirir.</b> Kağıttan başka şekilde ciltlenmiş veya tek kapakta birden fazla sayıdan oluşan gazete-dergi takımı 49.01’dedir (Not 3).",
  "<b>Tarih taşıyan her yayın periyodik değildir.</b> Haftalık fasiküllerle tamamlanan ansiklopedi 49.01’dedir; takvim diye anılan bilgi yıllıkları da takvim değil yayındır.",
  "<b>Çocuk kitabında ölçüt resmin ağırlığıdır.</b> Resimler metne üstünse 49.03; sürekli öykü biçiminde yazılıp resimlenmişse 49.01; sayfaların yarısından fazlası kesilecek modelse Fasıl 95.",
  "<b>Pulun yeri tedavüle bağlıdır.</b> Tedavüldeki kullanılmamış pul 49.07; tedavülde olmayan koleksiyon pulu 97.04; firmaların indirim pulları 49.11.",
  "<b>El ile çizilmiş ≠ basılmış.</b> Elle çizilmiş harita ve plan 49.06’da, basılı olanı 49.05 veya 49.11’de; daktilo yazılarının teksir kopyaları ise 49.01 veya 49.11’dedir.",
  "<b>Takvimli ajanda takvim değildir.</b> Hatıra ve randevu defterleri 48.20’de; blok takvim içermeyen takvim arkalıkları 49.11’de; kalıcı takvimler 49.10’dadır.",
  "<b>Baskılı etiket ve duvar kağıdı Fasıl 49’a gelmez.</b> Baskı esas unsur olsa bile 48.21 ve 48.14 istisnadır; kendinden yapışkanlı dekoratif sticker ise 49.11’dedir.",
  "<b>Kartpostal yazısı olmayan resimli kart 49.09 değildir.</b> Kartpostal olarak kullanılacağını gösteren basılı işaret yoksa resim olarak 49.11’e gider."
 ],
 "hafiza": {
  "kanca": "Kİ-GA-ÇO-NO-HA-PLA  /  PUL-ÇIK-KART-TAK-DİĞ",
  "aciklama": "<b>49.01</b> Kİtap · <b>49.02</b> GAzete · <b>49.03</b> ÇOcuk · <b>49.04</b> NOta · <b>49.05</b> HArita · <b>49.06</b> PLAn (elle) · <b>49.07</b> PUL-para · <b>49.08</b> ÇIKartma · <b>49.09</b> KART · <b>49.10</b> TAKvim · <b>49.11</b> DİĞer. Görsel benzetme: bir kitapçıda soldan sağa yürüyün; kitap rafı, gazete standı, çocuk köşesi, nota dolabı, harita masası, mimar çizim masası; kasada pul ve çek; çıkışta kartpostal standı, takvimler ve broşür sepeti."
 },
 "sinav_odagi": [
  "Bu fasıl çıkmış sorularda az sayıda doğrudan soruyla yer almıştır; ağırlıklı olarak Fasıl 48 ile sınırı sorulmuştur.",
  "“Hangisi 49. fasılda sınıflandırılır” kalıbında takvimin (49.10) sigara kağıdı (48.13), ajanda (48.20) ve gazete kağıdından (48.01) ayrılması.",
  "Basılı ve rölyef halindeki haritanın baskılı olsa bile Fasıl 49 dışında, 90.23’te yer alması.",
  "Gazete zinciri sıralaması: kağıt hamuru (47.06), satılmamış eski gazete (47.07), gazete kağıdı (48.01), günün gazetesi (49.02).",
  "Pozisyon sırasına dizme sorularında basılı ve kağıt eşyanın diğer fasıllarla birlikte kullanılması."
 ],
 "cikmis_ornekler": [
  {
   "soru": "Aşağıdakilerden hangisi Türk Gümrük Tarife Cetveli’nde 49. fasılda sınıflandırılır?",
   "secenekler": ["Sigara kâğıdı", "Takvim", "Ajanda", "Gazete kâğıdı"],
   "cevap": "B",
   "aciklama": "Matbu takvimler 49.10’dadır. Sigara kağıdı 48.13’te, ajanda (baskısı tali kırtasiye) 48.20’de, gazete kağıdı 48.01’dedir."
  },
  {
   "soru": "Aşağıda yer alan eşyanın tarife cetvelindeki sıraya göre doğru dizilişi aşağıdakilerden hangisidir? I- Gazete kağıdı II- Bugünün gazetesi III- Önceki günden satılmayan gazeteler IV- Geri kazanılmış kağıt liflerinin hamurları",
   "secenekler": ["I-II-III-IV", "I-III-II-IV", "IV-I-III-II", "IV-III-I-II"],
   "cevap": "D",
   "aciklama": "49.02 Açıklama Notuna göre gazetelerin eski nüshaları kağıt döküntüsü olarak 47.07’dedir. Sıra: hamur (47.06) → eski gazete (47.07) → gazete kağıdı (48.01) → günün gazetesi (49.02)."
  }
 ],
 "ozet": [
  "Baskı esas unsursa Fasıl 49, teferruatsa malzemenin faslı (kağıtta Fasıl 48); 48.14 ve 48.21 her durumda Fasıl 48.",
  "Not 1 dışarıda bırakır: saydam negatif (37), kabartma harita (90.23), oyun kağıdı (95), orijinal gravür ve koleksiyon pulu (97).",
  "Gazete 49.02; başka şekilde ciltli veya çok sayı tek kapakta ise 49.01; reklam yayını ve ticari katalog 49.11.",
  "Çocuk kitabı 49.03 (resim üstün); nota 49.04; basılı harita 49.05; elle çizilmiş plan 49.06.",
  "Tedavüldeki pul, banknot, çek, hisse senedi 49.07; çıkartma 49.08; kart 49.09; takvim 49.10; kalan her şey 49.11."
 ],
 "sorular": [
  S("Tarife Cetveline göre, haftada bir yayımlanan, her sayısında tarih ve sıra numarası bulunan, kağıt kapaklı ve reklam içeren moda dergisi hangi tarife pozisyonunda sınıflandırılır?",
    ["49.01", "49.11", "49.02", "48.20", "49.03"], "C", ESYA,
    "Belirli aralıklarla, aynı isim altında, tarih ve sıra numarasıyla yayımlanan, ciltsiz veya kağıt kapaklı yayınlar reklam içerse de 49.02’dedir. 49.01 başka şekilde ciltlenmiş dergileri (Not 3) kapsar; 49.11 reklama ayrılmış broşür ve kataloglar içindir, periyodik yayınları kapsamaz.",
    "49.02 pozisyon metni ve Açıklama Notu; Fasıl 49 Not 3 ve 5."),
  S("Tarife Cetveline göre, bir sanayi firmasının kendi ürünlerini tanıtmak amacıyla yayımladığı, ürün resimleri ve fiyat listesi içeren ciltli ticari katalog hangi tarife pozisyonunda sınıflandırılır?",
    ["49.11", "49.01", "49.02", "48.20", "49.10"], "A", ESYA,
    "Not 5 uyarınca esasen reklama ayrılmış yayınlar (ticari kataloglar dahil) 49.01’e girmez ve 49.11’de sınıflandırılır. Ciltli olması onu kitap yapmaz; periyodik olmadığı için 49.02 de söz konusu değildir.",
    "Fasıl 49 Not 5; 49.01 ve 49.11 Açıklama Notları."),
  S("Tarife Cetveline göre, bir mimar tarafından elle çizilmiş orijinal bina projesi (plan) hangi tarife pozisyonunda sınıflandırılır?",
    ["49.05", "49.11", "97.01", "90.23", "49.06"], "E", ESYA,
    "Mimarlık, mühendislik ve benzeri amaçlarla orijinali elle çizilmiş planlar ve çizimler 49.06’dadır. Basılı plan ve haritalar 49.05 veya 49.11’de, kabartma planlar 90.23’tedir. Elle çizilmiş olması onu sanat eseri yapmaz.",
    "49.06 pozisyon metni ve Açıklama Notu."),
  S("Tarife Cetveline göre, üzerinde dünya haritası basılı, içinde aydınlatma tertibatı bulunan ve oyuncak niteliğinde olmayan masa küresi hangi tarife pozisyonunda sınıflandırılır?",
    ["94.05", "49.05", "90.23", "95.03", "49.11"], "B", ESYA,
    "49.05 her nevi matbu küreyi kapsar; Açıklama Notu içinde aydınlatma tertibatı olan basılı kürelerin, oyuncak mahiyetinde olmamak kaydıyla bu pozisyonda kalacağını açıkça belirtir. Kabartma küreler 90.23’e gider; bu küre kabartma değildir.",
    "49.05 pozisyon metni ve Açıklama Notu; Fasıl 49 Not 1(b)."),
  S("Tarife Cetveline göre, bir konser için basılmış, numaralı giriş bileti hangi tarife pozisyonunda sınıflandırılır?",
    ["49.07", "48.21", "49.09", "49.11", "48.23"], "D", ESYA,
    "49.11 Açıklama Notu, eğlence yerleri (sinema, tiyatro, konser) için giriş biletlerini ve seyahat biletlerini açıkça sayar. 49.07 itibari değeri olan kıymetli evrak içindir; bilet etiket (48.21) veya kart (49.09) değildir.",
    "49.11 Açıklama Notu."),
  S("Aşağıdakilerden hangisi Tarife Cetvelinin 49. faslında <b>sınıflandırılmaz</b>?",
    ["Basılı duvar takvimi", "Baskılı, kabartma (rölyef) halindeki dünya haritası", "Basılı tebrik kartı", "Basılı müzik notası", "Seramik süslemede kullanılan basılı çıkartma"], "B", OLUMSUZ,
    "Not 1(b) uyarınca baskılı olsun olmasın rölyef haritalar, planlar ve küreler 90.23’tedir. Takvim 49.10, tebrik kartı 49.09, müzik notası 49.04, çıkartma 49.08’dedir.",
    "Fasıl 49 Not 1(b); 49.05 hariç tutma (f)."),
  S("Aşağıdakilerden hangisi 49.01 pozisyonunda <b>yer almaz</b>?",
    ["Fasiküller halinde yayımlanan ansiklopedi", "Kağıttan başka bir malzemeyle ciltlenmiş gazete koleksiyonu", "Sarı sayfalı telefon rehberi", "Soru ve alıştırmalar içeren, boşlukları el yazısıyla doldurulacak ders kitabı", "Bir turizm derneğinin yayımladığı tanıtım broşürü"], "E", OLUMSUZ,
    "Turistik tanıtım gibi esasen reklama ayrılmış yayınlar Not 5 gereği 49.11’dedir. Fasiküllerle yayımlanan ansiklopedi ve telefon rehberi 49.01 Açıklama Notunda sayılır; başka şekilde ciltli gazete koleksiyonu Not 3 gereği 49.01’dedir; alıştırmalı ders kitapları da 49.01’dedir.",
    "Fasıl 49 Not 3 ve Not 5; 49.01 Açıklama Notu."),
  S("Aşağıdakilerden hangisi 49.07 pozisyonunda <b>sınıflandırılmaz</b>?",
    ["Seri numaralı, özel güvenlikli kağıda basılmış piyango bileti", "Tedavüldeki kullanılmamış posta pulu", "Koleksiyon niteliğinde olmayan banknot", "Çek defteri", "Hisse senedi"], "A", OLUMSUZ,
    "49.07 Açıklama Notu, seri numaralı ve özel emniyetli kağıda basılmış olsa bile piyango biletlerini bu pozisyon dışında bırakır; bunlar 49.11’dedir. Tedavüldeki pul, banknot, çek defteri ve hisse senedi 49.07’nin pozisyon metninde sayılmıştır.",
    "49.07 pozisyon metni ve Açıklama Notu; 49.11 Açıklama Notu (11)."),
  S("Aşağıdakilerden hangisi 49.11 pozisyonunda <b>yer almaz</b>?",
    ["Anatomiye ait öğretici duvar şeması", "Dekoratif amaçlı, kendinden yapışkanlı baskılı sticker", "Sirk programını gösteren broşür", "Elle doldurulmak üzere basılmış randevu defteri (ajanda)", "Posta pulu taşımayan resimli ilk gün zarfı"], "D", OLUMSUZ,
    "Ajanda ve randevu defterleri, baskıları kullanımda tali olduğundan 48.20’dedir. Anatomi şemaları, dekoratif stickerlar, faaliyet programları ve pulsuz ilk gün zarfları 49.11 Açıklama Notunda sayılmıştır.",
    "49.11 Açıklama Notu; 48.20 Açıklama Notu."),
  S("Aşağıdaki eşyadan hangisi diğerlerinden farklı bir fasılda yer alır?",
    ["Basılı tebrik kartı", "Basılı çıkartma", "İskambil oyun kağıdı", "Basılı resimli kartpostal", "Basılı reklam afişi"], "C", FARKLI,
    "Oyun kağıtları Not 1(c) gereği Fasıl 95’tedir. Tebrik kartı ve resimli kartpostal 49.09’da, çıkartma 49.08’de, reklam afişi 49.11’dedir; hepsi Fasıl 49’dur.",
    "Fasıl 49 Not 1(c); 49.08, 49.09, 49.11."),
  S("Aşağıdakilerden hangisi diğerlerinden farklı bir tarife pozisyonunda yer alır?",
    ["Resimli alfabe kitabı", "Çocuklar için boyama kitabı", "Çocuklar için bezden resimli kitap", "Az miktarda sulu boya paleti bulunan resimli çocuk albümü", "Seçilmiş olayların resimleriyle zenginleştirilmiş, sürekli öykü biçiminde yazılmış çocuk romanı"], "E", FARKLI,
    "Bolca resimli olsa bile sürekli öykü biçiminde yazılmış kitaplarda metin esastır; 49.03 Açıklama Notu bunları 49.01’e gönderir. Resimli alfabe, boyama kitabı, bezden çocuk kitabı ve sulu boyalı albüm 49.03’tedir.",
    "Fasıl 49 Not 6; 49.03 Açıklama Notu."),
  S("Aşağıdaki eşya çiftlerinden hangisinde her iki eşya da aynı pozisyonda sınıflandırılır?",
    ["Matbu duvar takvimi – Ahşap kaideye takılmış, her gün yaprağı koparılan blok takvim", "Takvimli hatıra defteri – Matbu duvar takvimi", "Basılı harita – Elle çizilmiş harita", "Tedavüldeki kullanılmamış posta pulu – Tedavülde olmayan koleksiyon pulu", "Resimli kartpostal – Üzerine posta pulu basılmış posta kartı"], "A", FARKLI,
    "49.10 her türlü matbu takvimi, kağıt dışı mesnetlere monte edilmiş blok takvimler dahil kapsar. Diğer çiftler ayrılır: 48.20 / 49.10; 49.05 / 49.06; 49.07 / 97.04; 49.09 / 49.07.",
    "49.10 Açıklama Notu; 49.05, 49.06, 49.07, 49.09 Açıklama Notları."),
  S("Tarife Cetveline göre, müzikle ilgili aşağıdaki eşyadan hangisi diğerlerinden farklı bir pozisyonda sınıflandırılır?",
    ["Notalı ilahi kitabı", "Prova parçaları içeren müzik öğretim metodu", "Elle yazılmış müzik notası", "Mekanik müzik aleti için delikli nota rulosu", "Ciltli minyatür partisyon"], "D", FARKLI,
    "Mekanik müzik aletleri için kartlar, diskler ve rulolar 49.04 hariç tutmalarına göre 92.09’dadır. Notalı ilahi kitapları, alıştırmalı müzik metotları, elle yazılmış notalar ve minyatür partisyonlar 49.04’tedir.",
    "49.04 pozisyon metni ve Açıklama Notu."),
  S("Tarife Cetvelinin 49. Fasıl notları ve Genel Açıklamalarına göre aşağıdakilerden hangisi “baskılı” tabirinin kapsamına <b>girmez</b>?",
    ["Daktilo ile yazılarak çoğaltılmış metin", "Yalnızca süsleme amacıyla tekrarlı desen basılmış yüzey", "Fotokopi ile çoğaltılmış metin", "Otomatik bilgi işlem makinesinin kontrolünde üretilmiş çıktı", "Termokopi ile çoğaltılmış metin"], "B", TANIM,
    "Not 2 daktilo, fotokopi, termokopi ve bilgisayar kontrolünde üretilmiş çoğaltmaları “baskılı” sayar. Fasıl Genel Açıklamaları ise renklendirme ve dekoratif ya da tekrarlı desen baskılarının bu tabirin kapsamında olmadığını belirtir.",
    "Fasıl 49 Not 2; Fasıl 49 Genel Açıklamalar."),
  S("Tarife Cetvelinin 49. Fasıl notlarına göre, 49.03 pozisyonu anlamında “çocuklar için resimli albüm ve kitaplar” tabirinin ölçütü nedir?",
    ["Sayfalarının yarısından fazlasının renkli resim olması", "Yalnızca okul öncesi eğitimde kullanılması", "Ciltsiz olması ve kağıt üzerine basılmış olması", "İçinde kesilip çıkarılacak modeller bulunması", "Resimlerin, yazılı metne nazaran çocukların öncelikli ilgisini çekmesi"], "E", TANIM,
    "Not 6’ya göre ölçüt, resimlerin metne nazaran çocukların öncelikli ilgisini çekmesidir. Sayfa oranı ölçüt değildir; yarıdan fazla sayfa kriteri yalnızca kesilecek modeller için geçerlidir ve bu durumda kitap oyuncak (Fasıl 95) sayılır. Bezden çocuk kitapları da 49.03’tedir.",
    "Fasıl 49 Not 6; 49.03 Açıklama Notu."),
  S("Gazete ve periyodik yayınlarla ilgili aşağıdaki ifadelerden hangisi <b>yanlıştır</b>?",
    ["Kağıttan başka şekilde ciltlenmiş gazeteler 49.01’de yer alır.", "Tek bir kapak içinde birden fazla sayıdan oluşan dergi takımları 49.01’de yer alır.", "Reklam içeren gazeteler 49.11’de sınıflandırılır.", "Gazetelerin eski nüshaları kağıt döküntüsü olarak 47.07’de yer alır.", "Haftalık fasiküller halinde yayımlanan ansiklopedi bölümleri 49.01’de yer alır."], "C", TANIM,
    "49.02 pozisyon metni gazete ve periyodik yayınları “reklam içersin içermesin” kapsar; reklam içermeleri onları 49.11’e götürmez. Not 3 başka şekilde ciltli gazete ve çok sayılı takımları 49.01’e alır; eski nüshalar 47.07’de, ansiklopedi fasikülleri 49.01’dedir.",
    "Fasıl 49 Not 3; 49.02 pozisyon metni ve Açıklama Notu."),
  S("49.01 pozisyonuna ilişkin fasıl notlarına göre aşağıdakilerden hangisi <b>doğrudur</b>?",
    ["Formalar veya ayrı sayfalar halindeki, metin içermeyen gravür ve resimler 49.11’de yer alır.", "Ticari birliklerin yayımladığı reklam ağırlıklı yıllıklar 49.01’de yer alır.", "Kitapla birlikte sunulan ve kitabı tamamlayan resimli ilaveler 49.11’de yer alır.", "Ciltlenmek üzere ayrı fasiküller halinde neşredilen ve bir eserin parçasını oluşturan kitaplar 49.02’de yer alır.", "Eser ve sanatçıları hakkında metin içeren, numaralı sayfalı sanat eseri reprodüksiyonu koleksiyonları 49.11’de yer alır."], "A", TANIM,
    "Not 4’ün son cümlesi, metin içermeyen gravür ve resimleri forma veya ayrı sayfa halinde olsalar da 49.11’e gönderir. Reklam ağırlıklı yıllıklar Not 5 gereği 49.11’de; resimli ilaveler, fasikül halindeki kitaplar ve metinli reprodüksiyon koleksiyonları ise Not 4 gereği 49.01’dedir.",
    "Fasıl 49 Not 4 ve Not 5."),
  S("Ahşap bir çerçeve içinde sunulan basılı bir resim reprodüksiyonunda eşyanın esas karakterini resim vermektedir. Bu eşyanın sınıflandırılmasına ilişkin aşağıdakilerden hangisi doğrudur?",
    ["GYK 3(c) uyarınca numara sırasında sonra gelen ahşap çerçeve pozisyonunda", "GYK 2(a) uyarınca bitmemiş tablo olarak Fasıl 97’de", "GYK 5(a) uyarınca çerçeve ayrı, resim ayrı pozisyonlarda", "GYK 3(b) uyarınca esas karakteri veren resim nedeniyle 49.11’de", "GYK 1 uyarınca tebrik kartı olarak 49.09’da"], "D", GYK,
    "Çerçeveli resim iki farklı malzemeden oluşan bileşik bir eşyadır; 49.11 Açıklama Notu, esas karakteri resim veriyorsa eşyanın 49.11’de, aksi halde çerçeveye uygun pozisyonda sınıflandırılacağını belirtir. Bu esas karakter ölçütü GYK 3(b)’nin gereğidir. Çerçeve bir mahfaza olmadığından GYK 5(a) uygulanmaz.",
    "GYK 3(b); 49.11 Açıklama Notu."),
  S("Ciltlenmek üzere ayrı formalar (fasiküller) halinde sunulan ve bir romanın tamamını oluşturan basılı sayfalar hangi kurallarla hangi pozisyonda sınıflandırılır?",
    ["GYK 3(a) uyarınca basılı sayfa olarak 49.11’de", "GYK 1 (Fasıl 49 Not 4) ve GYK 6 uyarınca 49.01’de", "GYK 2(a) uyarınca bitmemiş eşya olarak 48.02’de", "GYK 4 uyarınca en çok benzediği eşya olarak 49.02’de", "GYK 3(c) uyarınca numara sırasında en sonda gelen 49.11’de"], "B", GYK,
    "Not 4(c), bir eserin tamamını veya bir kısmını oluşturan, ciltlenmek üzere fasikül veya ayrı sayfalar halinde sunulan kitapları açıkça 49.01’e alır. Eşya bir fasıl notuyla doğrudan tanımlandığından GYK 1 (alt pozisyon için GYK 6) yeterlidir; GYK 2(a) veya GYK 3’e başvurulmaz.",
    "GYK 1 ve 6; Fasıl 49 Not 4(c)."),
  S("Tarife Cetveline göre saydam mesnetli fotoğraf negatifleri ……, kabartma haritalar ……, orijinal gravürler …… ve oyun kağıtları …… fasıl veya pozisyonunda yer alır. Boşlukları sırasıyla dolduran seçenek hangisidir?",
    ["Fasıl 37 / 49.05 / 97.02 / Fasıl 95", "Fasıl 49 / 90.23 / 97.02 / Fasıl 95", "Fasıl 37 / 90.23 / 97.02 / Fasıl 95", "Fasıl 37 / 90.23 / 49.11 / Fasıl 48", "Fasıl 90 / 90.23 / 97.04 / Fasıl 95"], "C", ESLE,
    "Not 1 sırasıyla saydam mesnetli negatif ve pozitifleri Fasıl 37’ye, rölyef haritaları 90.23’e, oyun kağıtlarını Fasıl 95’e, orijinal gravürleri 97.02’ye gönderir. 97.04 pullar içindir; basılı ama kabartma olmayan haritalar 49.05’tedir.",
    "Fasıl 49 Not 1."),
  S("Aşağıdaki eşyaları sınıflandırıldıkları pozisyonlarla eşleştiriniz: I. Üzerinde basılı yazı bulunan, ışıksız adi metal dükkan levhası · II. Işıklı reklam levhası · III. Bir yüzüne resim basılmış dekoratif cam ayna · IV. Akıllı kart — a) 83.10 · b) 94.05 · c) 70.09 · d) 85.23",
    ["I-b, II-a, III-c, IV-d", "I-a, II-c, III-b, IV-d", "I-d, II-b, III-c, IV-a", "I-a, II-b, III-d, IV-c", "I-a, II-b, III-c, IV-d"], "E", ESLE,
    "Fasıl Genel Açıklamaları ve 49.11 hariç tutmalarına göre adi metalden yazılı levhalar 83.10’da, ışıklı olanlar 94.05’te; bir yüzü resim basılı dekoratif aynalar 70.09 (veya 70.13) kapsamında; akıllı kartlar 85.23’tedir. Üzerlerindeki baskı bu eşyaları Fasıl 49’a çekmez.",
    "Fasıl 49 Genel Açıklamalar; 49.11 hariç tutmaları."),
  S("Tarife Cetveline göre aşağıdaki ifadelerden hangileri doğrudur? I. Takvimli ve günlüklü hatıra defterleri 49.10’da yer alır. II. Blok halinde takvim içermeyen matbu takvim arkalıkları 49.11’de yer alır. III. Kalıcı (yıllık yenilenebilir) türden takvimler 49.10’da yer alır. IV. Dokunmuş mensucat üzerine basılmış takvimler, esas karakterini baskı oluşturuyorsa 49.10’da yer alır.",
    ["I ve II", "I ve III", "I, II ve IV", "II, III ve IV", "I, III ve IV"], "D", COKLU,
    "II, III ve IV 49.10 Açıklama Notunda açıkça yer alır: takvim her malzeme üzerine basılabilir, kalıcı takvimler dahildir, blok içermeyen takvim arkalıkları 49.11’dedir. I yanlıştır: takvimli ve günlüklü hatıra defterleri (randevu defterleri dahil) 48.20’dedir.",
    "49.10 Açıklama Notu ve hariç tutmaları."),
  S("49.09 pozisyonu ile ilgili aşağıdaki ifadelerden hangileri doğrudur? I. Kişisel tebrik içeren basılı kartlar zarflı veya süslemeli olsalar da 49.09’dadır. II. Üzerinde kartpostal olarak kullanılacağını gösteren basılı işaret bulunmayan resimli kartlar 49.09’da yer alır. III. Takvim şeklindeki yılbaşı kartları 49.10’da yer alır. IV. Çocukların boyaması için hazırlanmış resimli kartpostallar 49.09’da yer alır.",
    ["I ve III", "I ve II", "II ve IV", "I, III ve IV", "II, III ve IV"], "A", COKLU,
    "I pozisyon metninin, III 49.09 hariç tutmalarının ifadesidir. II yanlıştır: kartpostal işareti olmayan resimli kartlar resim olarak 49.11’e gider. IV yanlıştır: çocukların boyamasına uygun kartpostallar 49.03’tedir.",
    "49.09 pozisyon metni, Açıklama Notu ve hariç tutmaları."),
  S("Bir otomobil üreticisi adına ayda bir yayımlanan, her sayısı tarihli ve numaralı, kağıt kapaklı, yalnızca firma personeli arasında dağıtılan ve firmanın ürünlerine ilgiyi artırmayı amaçlayan kurum dergisi hangi tarife pozisyonunda sınıflandırılır?",
    ["49.11", "49.02", "49.01", "48.20", "49.10"], "B", SENARYO,
    "49.02 Açıklama Notu, motorlu taşıt imalatçıları gibi sınai firmalar adına yayımlanan periyodik yayınları ve yalnızca kuruluş içinde dağıtılan personel dergilerini açıkça bu pozisyona alır. Not 5’teki reklam kuralı 49.01 içindir; düzenli, tarihli ve numaralı yayın olduğu için 49.11’e gitmez.",
    "49.02 Açıklama Notu; Fasıl 49 Not 5."),
  S("Bir mühendislik firması, elle çizilmiş orijinal makine montaj çiziminin hassas kağıt üzerine alınmış fotoğrafik kopyasını ithal etmektedir. Kopya üzerinde elle yazılmış açıklamalar vardır ve kopya ciltsizdir. Bu eşya hangi tarife pozisyonunda sınıflandırılır?",
    ["49.11", "37.03", "49.06", "49.05", "48.20"], "C", SENARYO,
    "49.06, orijinali elle çizilmiş sınai planları ve bunların hassas kağıt üzerine fotoğrafik reprodüksiyonları ile karbon kopyalarını kapsar; üzerinde basılı veya elle yazılmış açıklama bulunabilir. Basılı planlar 49.05 veya 49.11’de olurdu; pozlanmamış hassas kağıt 37.03’tedir, bu eşya ise görüntü taşıyan bir kopyadır.",
    "49.06 pozisyon metni ve Açıklama Notu.")
 ]
}

yaz(obj, 49, 4902)
