from yardim_59_63 import Q, kur, yaz

E4 = "Eşya → 4’lü pozisyon"
OT = "Olumsuz teşhis"
FA = "Farklı/aynı pozisyon veya fasıl"
FN = "Fasıl notu · Tanım/Eşik"
GY = "Genel Yorum Kuralı"
EB = "Eşleştirme / Boşluk doldurma"
CC = "Çoktan-çoğa (I–IV)"
SN = "Senaryo"

sorular = [
    Q(E4,
      "Tarife Cetveline göre, eni 25 cm olan, ağırlıkça %8 elastomerik iplik içeren, tüysüz ve kaplanmamış, top halindeki örme mensucat hangi pozisyonda sınıflandırılır?",
      "60.02", ["60.04", "60.03", "58.06", "60.06"],
      "60.02, eni 30 cm’yi geçmeyen ve ağırlıkça %5 veya daha fazla elastomerik veya kauçuk iplik içeren örme veya kroşe mensucatı kapsar (60.01 hariç). Aynı oranda elastomer içeren fakat eni 30 cm’yi geçen mensucat 60.04’e, elastomeri %5’ten az olan dar mensucat 60.03’e gider. 58.06 dokunmuş dar mensucat pozisyonudur; örme ürüne uygulanmaz.",
      "60.02 ve 60.03 pozisyon metinleri ve Açıklama Notları; Bölüm XI Not 13."),
    Q(E4,
      "Tarife Cetveline göre, atkılı yuvarlak örme makinesinde örülmüş, eni 150 cm olan, ağırlıkça %3 elastomerik iplik içeren, tüysüz ve kaplanmamış pamuklu örme kumaş (top halinde) hangi pozisyonda sınıflandırılır?",
      "60.06", ["60.04", "60.05", "60.01", "60.03"],
      "Eni 30 cm’yi geçtiği halde elastomerik iplik oranı %5’in altında kaldığından 60.04’e giremez; atkılı örme olduğu için çözgü tipi örgüleri kapsayan 60.05 de uygun değildir. 60.06 Açıklama Notu, eni 30 cm’yi aşan ve %5’ten az elastomer içeren atkılı örme ve kroşe mensucatı örnek olarak sayar. Tüy veya bukle olmadığından 60.01 de elenir.",
      "60.04, 60.05 ve 60.06 pozisyon metinleri ve Açıklama Notları."),
    Q(E4,
      "Tarife Cetveline göre, çözgü tipi (Raschel) örme makinesinde üretilmiş, dantelaya benzeyen, elastomerik iplik içermeyen, kenarları muntazam ve paralel, eni 40 cm olan belirsiz uzunluktaki perdelik örme şerit hangi pozisyonda sınıflandırılır?",
      "60.05", ["58.04", "63.03", "60.03", "60.06"],
      "60.05 Açıklama Notu, Raschel tipi makinelerde yapılan ve dantelaya benzeyen örme taklit dantela şeritlerini, kenarları muntazam ve paralel ve genişliği 30 cm’yi geçmek şartıyla bu pozisyona alır. Dantelaya benzese de örme olduğundan 58.04’e girmez; eni 30 cm’yi geçtiği için 60.03 elenir. Hazır perde olmadığından 63.03 de uygun değildir.",
      "60.05 Açıklama Notu; Fasıl 60 Genel Açıklamalar."),
    Q(E4,
      "Tarife Cetveline göre, dairesel örgü makinesinde ilave ipliklerle ilmekleri dışarı çıkarılıp sonra kesilerek kadife görünümlü bir yüzey kazandırılmış örme mensucat (top halinde) hangi pozisyonda sınıflandırılır?",
      "60.01", ["58.01", "58.02", "43.04", "60.06"],
      "60.01 Açıklama Notu, ilave ipliklerle ilmeklerin dışarı çıkarılıp kesilmesiyle kadife benzeri yüzey kazandırılmış örme mensucatı bu pozisyonun üretim yöntemleri arasında sayar. Dokunmuş havlı mensucat 58.01’e, tufte edilmiş örme mensucat 58.02’ye, suni kürk 43.04’e gider. Tüylü olduğundan 60.06 elenir.",
      "60.01 Açıklama Notu (1) ve hariç tutmalar."),
    Q(E4,
      "Tarife Cetveline göre, bir yüzü çıplak gözle görülür biçimde poliüretanla kaplanmış, esnekliğini koruyan, tüysüz, eni 140 cm olan atkılı örme mensucat (top halinde) hangi pozisyonda sınıflandırılır?",
      "59.03", ["60.06", "60.01", "59.07", "60.04"],
      "Fasıl 60 Not 1(c), emdirilmiş, sıvanmış, kaplanmış veya lamine edilmiş örme mensucatı Fasıl 59’a gönderir; Fasıl 59 Not 1 de 60.02–60.06 örme mensucatını “dokumaya elverişli mensucat” sayar. Plastikle görülür biçimde kaplı olduğundan 59.03’tedir. 60.01’de kalma istisnası yalnız tüylü örme mensucat içindir.",
      "Fasıl 60 Not 1(c); Fasıl 59 Not 1 ve 2."),

    Q(OT,
      "Aşağıdakilerden hangisi Tarife Cetvelinin 60. faslında <b>sınıflandırılmaz</b>?",
      "Tığ ile yapılmış (kroşe) dantela",
      ["Metal ipliklerden örülmüş, döşemecilikte kullanılan türden mensucat",
       "İlmikleri dokumaya elverişli iplikten oluşturulan dikiş-trikotaj mensucat",
       "Plastikle kaplanmış örme tüylü mensucat",
       "Kare şeklinde kesilmiş, başka işlem görmemiş örme mensucat parçası"],
      "Fasıl 60 Not 1(a), 58.04’teki tığla yapılmış dantelaları fasıl dışına çıkarır. Metal iplikten giyim veya döşemecilik türü örme eşya Not 2 ile, dikiş-trikotaj eşyası Not 3 ile, kaplanmış tüylü örme mensucat Not 1(c) istisnasıyla, basitçe kare kesilmiş parça ise Genel Açıklamalar gereği Fasıl 60’tadır.",
      "Fasıl 60 Not 1, 2 ve 3; Genel Açıklamalar."),
    Q(OT,
      "Aşağıdakilerden hangisi 60.01 pozisyonunda <b>yer almaz</b>?",
      "Tufte edilmiş örme mensucat",
      ["Tarak şeridinden gelen liflerin ilmek oluşumu sırasında zemine sokulduğu uzun tüylü örme mensucat",
       "Ortak bukle ipliğiyle yüz yüze örülüp kesilerek ayrılmış kesik tüylü örme mensucat",
       "Arka yüzünde zincir dikiş sıraları bulunan örme taklit havlu mensucat",
       "Kauçukla kaplanmış örme tüylü mensucat"],
      "60.01 Açıklama Notu tufte edilmiş örme veya kroşe mensucatı açıkça hariç tutar ve 58.02’ye gönderir. Uzun tüylü mensucat, yüz yüze örülüp kesilen kesik tüylü mensucat ve arkasında zincir dikiş sıraları bulunan taklit havlu 60.01’in üretim yöntemleri arasındadır; kaplanmış tüylü örme mensucat da Not 1(c) ile 60.01’de kalır.",
      "60.01 Açıklama Notu; Fasıl 60 Not 1(c)."),
    Q(OT,
      "60.02–60.06 Açıklama Notlarına göre aşağıdakilerden hangisi bu pozisyonlarda <b>sınıflandırılmaz</b>?",
      "Tıbbi amaçlı, perakende ambalajlı örme sargı",
      ["Eni 20 cm olan, elastomerik iplik içermeyen pamuklu örme şerit",
       "Eni 160 cm olan, ağırlıkça %10 elastomerik iplik içeren örme kumaş",
       "Eni 180 cm olan, çözgülü örme perdelik mensucat",
       "Eni 120 cm olan, kroşe işi mensucat"],
      "60.02–60.06 açıklama notlarının hepsi, tıbbi ve cerrahi amaçlı kullanılmak üzere perakende satılacak şekilde ambalajlanmış örme sargıları hariç tutar ve 30.05’e gönderir. Diğer seçenekler sırasıyla 60.03, 60.04, 60.05 ve 60.06’dadır.",
      "60.02–60.06 Açıklama Notları, hariç tutmalar."),
    Q(OT,
      "Fasıl 60 Genel Açıklamalarına göre aşağıdakilerden hangisi bu faslın kapsamı <b>dışındadır</b>?",
      "Liflerin kendisinin toplanmasıyla tülbentten dikme-örme yöntemiyle elde edilen mensucat",
      ["Çözgülü atkı ipliklerini tığ işi ilmek zincirleriyle tutan, çözgülü makinede örülmüş mensucat",
       "Elle iki şiş kullanılarak örülmüş, parça halindeki mensucat",
       "Dairesel örgü makinesinde boru şeklinde örülmüş parça halindeki mensucat",
       "Elastomerik iplikle birleştirilmiş kroşe mensucat"],
      "Genel Açıklamalar, dokumaya elverişli liflerden oluşan tülbentten liflerin kendileri toplanarak dikme-örme yöntemiyle imal edilen mensucatı Fasıl 60 dışında tutar ve 56.02’ye gönderir. İlmekleri iplikten oluşan dikiş-trikotaj ise Not 3 gereği örmedir. El şişiyle, dairesel makinede boru şeklinde örülen veya elastomerik iplikle birleştirilmiş örme ve kroşe mensucat fasıl kapsamındadır.",
      "Fasıl 60 Genel Açıklamalar; Fasıl 60 Not 3."),

    Q(FA,
      "Aşağıdakilerden hangisi diğerlerinden farklı bir pozisyonda sınıflandırılır?",
      "Eni 200 cm, galloon örgü makinesinde yapılmış çözgülü örme mensucat",
      ["Eni 90 cm, elastomerik iplik içermeyen atkılı örme mensucat",
       "Eni 140 cm, ağırlıkça %2 elastomerik iplikli atkılı örme mensucat",
       "Eni 110 cm, kroşe işi mensucat",
       "Eni 60 cm, döşemecilik türünden metal iplikli atkılı örme mensucat"],
      "Galloon örgü makinelerinde yapılanlar dahil çözgü tipi örgülü mensucat 60.05’tedir. Eni 30 cm’yi geçen, %5’ten az elastomerli atkılı örme ve kroşe mensucat ile döşemecilik türü metal iplikli örme mensucat artık pozisyon olan 60.06’dadır. Ayrım, ilmek yapısının atkı mı çözgü mü olduğudur.",
      "60.05 ve 60.06 pozisyon metinleri ve Açıklama Notları; Fasıl 60 Not 2."),
    Q(FA,
      "Aşağıdakilerden hangisi diğerlerinden farklı bir fasılda yer alır?",
      "Örme veya kroşe etiketler ve armalar",
      ["Top halinde örme havlu mensucat",
       "Eni 28 cm, ağırlıkça %7 elastomerik iplikli örme bant",
       "Raschel makinesinde örülmüş, eni 180 cm perdelik mensucat",
       "İlmikleri iplikten oluşan dikiş-trikotaj mensucat"],
      "Fasıl 60 Not 1(b), 58.07’deki örme veya kroşe etiketleri, armaları ve benzeri eşyayı fasıl dışında bırakır; bunlar Fasıl 58’dedir. Örme havlu mensucat 60.01’de, dar elastik örme bant 60.02’de, Raschel perdelik mensucat 60.05’te, dikiş-trikotaj mensucat Fasıl 60’tadır.",
      "Fasıl 60 Not 1(b) ve Not 3."),
    Q(FA,
      "Aşağıdaki eşya çiftlerinden hangisinde her iki eşya da <b>aynı</b> pozisyonda sınıflandırılır?",
      "Eni 20 cm, %6 kauçuk iplikli örme – eni 20 cm, %6 elastomerik iplikli örme",
      ["Örme kadife – dokunmuş kadife",
       "Plastik kaplı örme tüylü mensucat – plastik kaplı tüysüz örme mensucat",
       "Eni 30 cm, elastomersiz örme – eni 31 cm, elastomersiz atkılı örme",
       "Örme taklit havlu mensucat – tufte edilmiş örme mensucat"],
      "60.02, eni 30 cm’yi geçmeyen ve ağırlıkça %5 veya daha fazla elastomerik iplik ya da kauçuk iplik içeren mensucatı birlikte kapsar; iki ürün de 60.02’dedir. Diğer çiftler ayrılır: 60.01 – 58.01; 60.01 – 59.03; 60.03 (eni 30 cm’yi geçmeyen) – 60.06; 60.01 – 58.02.",
      "60.02 pozisyon metni; Fasıl 60 Not 1(c); 60.01 Açıklama Notu."),
    Q(FA,
      "Aşağıdakilerden hangisi diğerlerinden farklı bir fasılda sınıflandırılır?",
      "Basitçe dikdörtgen kesilmiş örme mensucat parçası",
      ["Kenarları bastırılmış, kare kesilmiş örme mensucattan boyun atkısı",
       "Örülerek şekil verilmiş kazak parçaları",
       "Örme eldiven",
       "Örme kravat"],
      "Fasıl 60, parça halinde veya yalnızca basitçe kare/dikdörtgen kesilmiş örme mensucatı kapsar. Kenarı bastırılmış parçalar ve örülerek şekil verilmiş eşya Bölüm XI Not 7 anlamında hazır eşyadır; Fasıl 60 Genel Açıklamaları bunları dışarıda bırakır ve diğer seçeneklerin tümü Fasıl 61’e gider.",
      "Fasıl 60 Genel Açıklamalar (e); Bölüm XI Not 7 ve 8."),

    Q(FN,
      "Tarife Cetveline göre 60.02 ve 60.04 pozisyonlarını diğer örme mensucattan ayıran elastomerik veya kauçuk iplik oranı hangisidir?",
      "Ağırlıkça %5 veya daha fazla",
      ["Ağırlıkça %5’ten fazla", "Ağırlıkça %10 veya daha fazla", "Hacimce %5 veya daha fazla", "Ağırlıkça %3 veya daha fazla"],
      "60.02 ve 60.04 pozisyon metinleri “ağırlık itibariyle %5 veya daha fazla elastomerik iplik veya kauçuk iplik içeren” örme mensucattan söz eder. Tam %5 içeren mensucat da bu pozisyonlara girer; ölçüt hacim değil ağırlıktır.",
      "60.02 ve 60.04 pozisyon metinleri."),
    Q(FN,
      "Bölüm XI Not 13’teki “elastomerik iplik” tanımı aşağıdakilerin hangisinde doğru verilmiştir?",
      "Üç katına gerilince kopmayan, 5 dakika iki katına gerildikten sonra 1,5 katını aşmayan boya dönen sentetik filament iplik",
      ["İki katına gerilince kopmayan, 5 dakika üç katına gerildikten sonra 1,5 katını aşmayan boya dönen sentetik filament iplik",
       "Üç katına gerilince kopmayan, 10 dakika iki katına gerildikten sonra 2 katını aşmayan boya dönen sentetik filament iplik",
       "Üç katına gerilince kopmayan, 5 dakika iki katına gerildikten sonra 1,5 katını aşmayan boya dönen tekstüre iplik",
       "Üç katına gerilince kopmayan, 5 dakika iki katına gerildikten sonra 1,5 katını aşmayan boya dönen suni filament iplik"],
      "Not 13’e göre elastomerik iplik; orijinal uzunluğunun üç katına kadar gerildiğinde kopmayan ve 5 dakika iki katı uzunlukta gerildikten sonra orijinal uzunluğunun 1,5 katından fazla olmayan uzunluğa dönen, dokumaya elverişli sentetik maddelerden filament ipliktir (monofilament dahil). Tekstüre iplik tanımın dışında tutulmuştur; suni (sentetik olmayan) lifler de tanıma girmez.",
      "Bölüm XI Not 13."),
    Q(FN,
      "Fasıl 60 Not 3 ve Genel Açıklamalarına göre aşağıdakilerden hangisi doğrudur?",
      "“Örme eşya” tabirine, tarifenin her yerinde, ilmikleri iplikten dikiş-trikotaj eşyası da dahildir.",
      ["Dikiş-trikotaj eşyası yalnızca Fasıl 60’ta örme sayılır; diğer fasıllarda dokunmuş kabul edilir.",
       "İlmikleri tülbendin kendi liflerinden oluşan dikme-örme mensucat da örme eşyadır.",
       "Dikiş-trikotaj usulüyle birleştirilmiş kapitoneli ürünler Fasıl 60’tadır.",
       "Dikiş-trikotaj eşyası, atkılı örmelerin bir türü olarak 60.06’da sınıflandırılır."],
      "Not 3, “örme eşya” tabirine yapılan her atfın ilmikleri dokumaya elverişli iplikten olan dikiş-trikotaj eşyasını da kapsadığını, bunun tarifenin tamamında geçerli olduğunu söyler. Genel Açıklamalar dikiş-trikotajı çözgü örgüleri arasında sayar; liflerin kendisiyle yapılan dikme-örme mensucat 56.02’ye, dikiş-trikotajla birleştirilmiş kapitoneli ürünler 58.11’e gider.",
      "Fasıl 60 Not 3; Fasıl 60 Genel Açıklamalar (A)(II)."),
    Q(FN,
      "Fasıl 60 Genel Açıklamalarına göre atkılı örme ile çözgülü örme arasındaki farka ilişkin aşağıdakilerden hangisi doğrudur?",
      "Atkılı örmede iplik koparsa kaçık oluşur; çözgülü örmede oluşmaz.",
      ["Çözgülü örmede iplik koparsa kaçık oluşur; atkılı örmede ilmekler sökülmez.",
       "Atkılı örmede çözgü ve atkı iplikleri birbirini dik açıyla çaprazlar.",
       "Çözgülü örme yalnızca elle, şiş kullanılarak yapılabilir.",
       "Atkılı örme mensucat, eni ne olursa olsun 60.05’te sınıflandırılır."],
      "Genel Açıklamalara göre atkılı örmede tek bir iplik enine ilmek sıraları oluşturur, ilmekler gevşek geçtiğinden iplik koptuğunda kolayca sökülür ve kaçık oluşur. Çözgülü örmede her iplik komşu ipliklerin ilmekleriyle zincirleme bağlandığından kaçık olmaz. Çözgü ve atkının dik açıyla çaprazlanması dokumaya özgüdür.",
      "Fasıl 60 Genel Açıklamalar (A)(I)–(II)."),

    Q(GY,
      "Bir kazağın imali için örülerek şekil verilmiş ön, arka ve kol parçaları henüz birleştirilmeden birlikte sunulmuştur. Parçalar kazağın esas karakterini taşımaktadır. Bu eşyanın sınıflandırılmasıyla ilgili hangisi doğrudur?",
      "Hazır eşyadır; GYK 2(a) uyarınca bitmiş kazağın pozisyonunda (61.10) sınıflandırılır.",
      ["Parça halinde örme mensucat olduğundan GYK 1 uyarınca 60.06’da sınıflandırılır.",
       "Kare veya dikdörtgen olmadığından GYK 1 uyarınca 63.07’de sınıflandırılır.",
       "GYK 3(b) uyarınca esas karakteri veren ön parçaya göre 61.17’de sınıflandırılır.",
       "GYK 3(c) uyarınca numara sırasına göre sonuncu olan 63.07’de sınıflandırılır."],
      "Örülerek şekil verilmiş parçalar Bölüm XI Not 7(g) gereği hazır eşyadır ve Fasıl 60 kapsamından çıkar. Fasıl 61 Genel Açıklamaları, bitmemiş eşya ile bu eşyanın imaline mahsus şekil verilmiş örme mensucatı, esas karaktere sahip olmak şartıyla mamul eşyanın pozisyonunda sınıflandırır; birleştirilmemiş haldeki tam set için dayanak GYK 2(a)’dır.",
      "GYK 2(a); Bölüm XI Not 7(g) ve 8; Fasıl 61 Genel Açıklamalar."),
    Q(GY,
      "Arka yüzü çıplak gözle görülür biçimde plastikle kaplanmış, örme tüylü (kesik bukleli) bir mensucat hem 60.01 hem de 59.03 pozisyonuna uyar görünmektedir. Bu mensucat hangi kurala göre ve hangi pozisyonda sınıflandırılır?",
      "GYK 1 – 60.01",
      ["GYK 3(a) – 59.03", "GYK 3(c) – 60.01", "GYK 3(b) – 59.03", "GYK 2(b) – 59.07"],
      "Fasıl 60 Not 1(c), kaplanmış örme mensucatı Fasıl 59’a gönderirken emdirilmiş, sıvanmış, kaplanmış veya lamine edilmiş tüylü örme mensucatın 60.01’de kalacağını açıkça söyler; 60.01 Açıklama Notu da bunu tekrarlar. Sonuç fasıl notuyla belirlendiğinden kural GYK 1’dir. GYK 3(c) aynı pozisyonu verse de bu, notun bulunduğu durumda uygulanacak kural değildir.",
      "GYK 1; Fasıl 60 Not 1(c); 60.01 Açıklama Notu."),

    Q(EB,
      "Aşağıdaki eşya – pozisyon eşleştirmelerinden hangisi <b>yanlıştır</b>?",
      "Örme etiket ve armalar – 60.03",
      ["Örme taklit havlu mensucat – 60.01",
       "Tıbbi, perakende ambalajlı örme sargı – 30.05",
       "Örgü işi halı – 57.05",
       "Şenet iplik – 56.06"],
      "Örme veya kroşe etiketler, armalar ve benzeri eşya Fasıl 60 Not 1(b) gereği 58.07’dedir; dar olmaları onları 60.03’e sokmaz. Taklit havlu 60.01’de; tıbbi sargı, örgü halı ve şenet iplik ise açıklama notlarında sırasıyla 30.05, 57.05 ve 56.06’ya gönderilmiştir.",
      "Fasıl 60 Not 1(b); Genel Açıklamalar; 60.01–60.03 Açıklama Notları."),
    Q(EB,
      "Fasıl 60 Not 1(c)’ye göre emdirilmiş, sıvanmış, kaplanmış veya lamine edilmiş örme veya kroşe mensucat ________ fasılda yer alır; ancak bu işlemleri görmüş ________ örme veya kroşe mensucat 60.01 pozisyonunda kalır. Boşluklara sırasıyla hangisi gelmelidir?",
      "59. / tüylü",
      ["39. / tüylü", "59. / dar enli", "56. / elastik", "59. / çözgülü"],
      "Not 1(c), kaplanmış örme mensucatı Fasıl 59’a gönderir ve yalnız tüylü örme mensucat için 60.01 istisnası tanır. Dar enli, elastik veya çözgülü olmak bu istisnayı doğurmaz; Fasıl 39 seçeneği Bölüm XI Not 1(h) ile karışıklık yaratmak için verilmiştir.",
      "Fasıl 60 Not 1(c)."),

    Q(CC,
      "Fasıl 60’a göre aşağıdaki ifadelerden hangileri doğrudur? I. Tüylüler hariç, eni 30 cm’yi geçmeyen örme mensucat elastomerik veya kauçuk iplik oranına göre 60.02 veya 60.03’te yer alır. II. 60.01’deki tüylü örme mensucatta en ve elastomerik iplik oranı belirleyici değildir. III. Tığ işi dantela 60.06’da sınıflandırılır. IV. Örgü işi halılar 60.01’de sınıflandırılır.",
      "I ve II", ["I ve III", "II ve IV", "I, II ve III", "III ve IV"],
      "I, 60.02 ve 60.03 metinlerinin özetidir; II doğrudur, çünkü 60.01 metninde en veya elastomer ölçütü yoktur ve 60.02–60.05 metinleri 60.01’dekileri hariç tutar. III yanlıştır: tığ işi dantela Not 1(a) ile 58.04’tedir. IV yanlıştır: örgü işi halılar Genel Açıklamalar gereği 57.05’tedir.",
      "60.01–60.03 pozisyon metinleri; Fasıl 60 Not 1(a); Genel Açıklamalar."),
    Q(CC,
      "Aşağıdakilerden hangileri Fasıl 60’ta sınıflandırılır? I. Metal iplikten örülmüş, giyim eşyası imalinde kullanılan türden mensucat II. Çözgülü örme makinesinde üretilmiş, eni 200 cm perdelik mensucat III. Örme mensucattan, kenarları bastırılmış dikdörtgen masa örtüsü IV. İlmikleri dokumaya elverişli iplikten oluşturulmuş dikiş-trikotaj mensucat",
      "I, II ve IV", ["I ve II", "II ve III", "I, III ve IV", "Yalnız II"],
      "I Not 2 ile, IV Not 3 ile Fasıl 60’tadır; II, çözgü tipi örgülü mensucat olarak 60.05’tedir. III ise kenarları bastırılmış olduğundan Bölüm XI Not 7 anlamında hazır eşyadır ve Fasıl 60 Genel Açıklamaları gereği bu fasıl dışında (Fasıl 63) kalır.",
      "Fasıl 60 Not 2 ve 3; Genel Açıklamalar (e); Bölüm XI Not 7."),

    Q(SN,
      "Bir tekstil firması; çözgülü örme makinesinde poliamid ve ağırlıkça %18 elastomerik iplikle üretilmiş, tüysüz, kaplanmamış, eni 155 cm olan mayo kumaşını top halinde ithal etmektedir. Tarife Cetveline göre bu eşya hangi pozisyonda sınıflandırılır?",
      "60.04", ["60.05", "60.02", "61.12", "60.06"],
      "Eni 30 cm’yi geçen ve ağırlıkça %5 veya daha fazla elastomerik iplik içeren örme mensucat 60.04’tedir. Çözgülü örme olması 60.05’i düşündürse de 60.05 metni 60.01–60.04’tekileri hariç tutar. Kumaş henüz hazır eşya olmadığından mayo pozisyonu 61.12 uygulanmaz; eni 30 cm’yi geçtiği için 60.02 de elenir.",
      "60.04 ve 60.05 pozisyon metinleri; Bölüm XI Not 13."),
    Q(SN,
      "Bir firma; ilmekleri dokumaya elverişli iplikten oluşan zincir dikişlerle paralel iplik katları birbirine dikilerek (dikiş-trikotaj yöntemiyle) üretilmiş, tüysüz, kaplanmamış, elastomerik iplik içermeyen, eni 210 cm mensucatı top halinde ithal etmektedir. Tarife Cetveline göre bu eşya hangi pozisyonda sınıflandırılır?",
      "60.05", ["56.02", "58.11", "60.06", "56.03"],
      "Not 3 gereği ilmikleri iplikten olan dikiş-trikotaj eşyası “örme eşya”dır ve Genel Açıklamalar bunu çözgü örgüleri arasında sayar; eni 30 cm’yi geçen, elastomersiz çözgü örgüsü 60.05’e girer. Dikme-örme ilmekleri tülbendin kendi liflerinden oluşsaydı 56.02, dikiş-trikotajla birleştirilmiş kapitoneli ürün olsaydı 58.11 söz konusu olurdu.",
      "Fasıl 60 Not 3; Genel Açıklamalar (A)(II); 60.05 Açıklama Notu."),
]

d = {
    "tur": "fasil",
    "fasil": 60,
    "baslik": "Örme mensucat",
    "bolum": "XI",
    "oz": {
        "vurgu": "Fasıl 60, ilmeklerin birbirinin içinden geçmesiyle oluşan örme veya kroşe mensucatı yalnızca parça halinde veya basitçe kare/dikdörtgen kesilmiş olarak kapsar. Sınıflandırma üç soruyla yapılır: tüylü mü (60.01)? Eni 30 cm’yi geçiyor mu? Ağırlıkça %5 veya daha fazla elastomerik ya da kauçuk iplik içeriyor mu? Hazır eşya haline gelen örme ürün Fasıl 61–63’e gider.",
        "maddeler": [
            "Dokumada çözgü ve atkı çaprazlanır; örmede ilmek serileri birbirine geçer. Atkılı örmede kaçık oluşur, çözgülü örmede oluşmaz.",
            "İlmikleri dokumaya elverişli iplikten olan dikiş-trikotaj eşyası, tarifenin her yerinde “örme eşya” sayılır (Not 3).",
            "Kaplanmış örme mensucat Fasıl 59’a gider; kaplanmış tüylü örme mensucat ise 60.01’de kalır (Not 1(c)).",
            "Tığ işi dantela 58.04, örme etiket ve arma 58.07, örgü halı 57.05, ağ ve fileler 56.08, tufte örme 58.02, suni kürk 43.04.",
            "Metal iplikten giyim, döşemecilik ve benzeri işlere mahsus örme eşya da Fasıl 60’tadır (Not 2).",
        ],
    },
    "karar_tablosu": {
        "aciklama": "Soruları yukarıdan aşağıya sırayla sorun; ilk “evet” cevabı pozisyonu verir.",
        "satirlar": [
            ["1", "Hazır eşya mı? (kenarı bastırılmış, şekil verilerek örülmüş, giysi, örtü vb.)", "Fasıl <b>61</b> / <b>62.12</b> / <b>63</b>"],
            ["2", "Tığ işi dantela, örme etiket-arma, örgü halı, ağ-file mi?", "<b>58.04</b> / <b>58.07</b> / <b>57.05</b> / <b>56.08</b>"],
            ["3", "Tüylü mü? (uzun tüylü, kesik tüylü, taklit havlu)*", "<b>60.01</b> (kaplanmış olsa da; en ve elastomer önemsiz)"],
            ["4", "Emdirilmiş, sıvanmış, kaplanmış veya lamine mi?", "Fasıl <b>59</b> (<b>59.03</b> / <b>59.06</b> / <b>59.07</b>)"],
            ["5", "Eni ≤ 30 cm ve elastomerik/kauçuk iplik ağırlıkça ≥ %5 mi?", "<b>60.02</b>"],
            ["6", "Eni ≤ 30 cm, diğer mi?", "<b>60.03</b>"],
            ["7", "Eni 30 cm’yi geçiyor ve elastomerik/kauçuk iplik ≥ %5 mi?", "<b>60.04</b>"],
            ["8", "Çözgü tipi örgü mü? (Raschel, galloon, dikiş-trikotaj)", "<b>60.05</b>"],
            ["9", "Hiçbiri değilse (atkılı örme, kroşe)", "<b>60.06</b>"],
        ],
        "dipnot": "* Tufte edilmiş örme mensucat 58.02’dedir. Ayrıca: tıbbi, perakende ambalajlı örme sargı 30.05; liflerin kendisiyle tülbentten dikme-örme mensucat 56.02; dikiş-trikotajla birleştirilmiş kapitoneli ürün 58.11.",
    },
    "pozisyon_haritasi": [
        ["60.01", "Örme/kroşe tüylü mensucat (uzun tüylü, havlu dahil)", "Tüy veya bukle; kaplanmış olsa da burada", "Örme kadife, örme peluş, taklit havlu"],
        ["60.02", "Eni ≤ 30 cm, elastomerik/kauçuk iplik ≥ %5", "Dar + elastik", "Dar elastik örme bant"],
        ["60.03", "Eni ≤ 30 cm, diğer örme mensucat", "Dar; elastomer %5’ten az", "Dar örme şerit"],
        ["60.04", "Eni 30 cm’yi geçen, elastomerik/kauçuk iplik ≥ %5", "Geniş + elastik", "Elastomerli geniş örme kumaş"],
        ["60.05", "Çözgü tipi örgülü diğer mensucat (galloon dahil)", "Geniş; çözgü örgüsü; kaçık olmaz", "Raschel perdelik örme, taklit dantela"],
        ["60.06", "Diğer örme veya kroşe mensucat", "Artık pozisyon", "Geniş atkılı örme kumaş, kroşe mensucat"],
    ],
    "notlar": [
        ["Bölüm XI Not 7–8", "Hazır eşya (kenarı bastırılmış, şekilli kesilmiş, örülerek şekil verilmiş, dikilerek birleştirilmiş vb.) için 60. fasıl uygulanmaz; 60. fasıl 56–59. fasıllardaki eşyaya da uygulanmaz."],
        ["Bölüm XI Not 10", "Dokumaya elverişli maddelerin kauçuk ipliklerle birleştirilmesiyle oluşan elastik ürünler Bölüm XI’de sınıflandırılır."],
        ["Bölüm XI Not 13", "“Elastomerik iplik”: orijinal uzunluğunun üç katına kadar gerildiğinde kopmayan ve 5 dakika süreyle iki katı uzunlukta gerildikten sonra orijinal uzunluğunun 1,5 katından fazla olmayan uzunluğa dönen, sentetik maddelerden filament iplik (monofilament dahil; tekstüre iplik hariç)."],
        ["Fasıl 60 Not 1", "Fasıl dışı: (a) 58.04’teki tığla yapılmış dantelalar; (b) 58.07’deki örme veya kroşe etiketler, armalar ve benzeri eşya; (c) Fasıl 59’daki emdirilmiş, sıvanmış, kaplanmış veya lamine edilmiş örme mensucat. Ancak bu işlemleri görmüş tüylü örme mensucat 60.01’de kalır."],
        ["Fasıl 60 Not 2", "Metal ipliklerden imal edilip giyim eşyasında, döşemecilikte ve benzeri işlerde kullanılan türden eşya da bu fasıldadır."],
        ["Fasıl 60 Not 3", "Tarifenin neresinde geçerse geçsin “örme eşya” tabirine, ilmikleri dokumaya elverişli iplikten olan dikiş-trikotaj eşyası da dahildir."],
        ["Genel Açıklamalar", "Örme mensucat ilmek serilerinin birbirine geçmesiyle oluşur: atkılı örmede iplik koparsa ilmekler sökülür ve kaçık oluşur; çözgülü örmede kaçık olmaz. Dikiş-trikotaj ve tığ işi ilmek zinciriyle yapılan çözgülü mensucat çözgü örgüsüdür. Fasıl, parça halinde (boru şeklinde dahil) veya basitçe kare/dikdörtgen kesilmiş mensucatı kapsar; elastomerik veya kauçuk iplikle birleştirilmiş olması fark etmez."],
        ["Genel Açıklamalar (hariç)", "Tülbentten liflerin kendisiyle dikme-örme mensucat (56.02); ağ ve fileler (56.08); örgü işi halılar (57.05); ağ mensucat ve kroşe danteller (58.04); kenarı bastırılmış, kullanıma hazır imal edilmiş veya şekil verilerek örülmüş mensucat (Fasıl 61, 62, 63)."],
        ["60.01 Açıklama Notu", "Tüylü örme mensucat dört yolla elde edilir: ilave ipliklerle çıkarılıp kesilen ilmekler, yüz yüze örülüp kesilerek ayrılan iki mensucat, ilmek oluşurken zemine sokulan tarak lifleri (uzun tüylü), ilmekli iplikler (taklit havlu; arkada zincir dikiş sıraları). Hariç: suni kürk 43.04, dokunmuş havlı mensucat 58.01, tufte örme mensucat 58.02."],
        ["60.05 Açıklama Notu", "Raschel tipi çözgülü makinelerde yapılan, ağ veya dantelaya benzeyen örme mensucat buradadır; belirsiz uzunluktaki taklit dantela şeritleri, kenarları muntazam ve paralel ve eni 30 cm’yi geçmek şartıyla 60.05’te yer alır."],
        ["60.02–60.06 Açıklama Notları", "Hariç: tıbbi, perakende ambalajlı örme sargılar (30.05); şenet iplikler (56.06); örme etiket ve armalar (58.07); işlemeli mensucat (58.10); Fasıl 59 türü örme mensucat (59.03, 59.06, 59.07; fitil ve lamba gömleği 59.08); hazır eşya."],
    ],
    "sinir_komsulari": [
        ["Dokunmuş kadife, peluş", "58.01", "Dokuma; 60.01 Açıklama Notu"],
        ["Tufte edilmiş örme mensucat", "58.02", "60.01 Açıklama Notu"],
        ["Suni kürk", "43.04", "60.01 Açıklama Notu"],
        ["Tığ işi dantela, ağ mensucat", "58.04", "Fasıl 60 Not 1(a)"],
        ["Örme etiket, arma", "58.07", "Fasıl 60 Not 1(b)"],
        ["İşlemeli örme mensucat", "58.10", "60.02–60.06 Açıklama Notları"],
        ["Kaplanmış tüysüz örme mensucat", "59.03 / 59.06 / 59.07", "Fasıl 60 Not 1(c)"],
        ["Lamba gömleği için boru şeklinde örme mensucat; fitil", "59.08", "60.03, 60.05, 60.06 Açıklama Notları"],
        ["Liflerin kendisiyle tülbentten dikme-örme mensucat", "56.02", "Genel Açıklamalar"],
        ["Ağ ve fileler", "56.08", "Genel Açıklamalar"],
        ["Örgü işi halı", "57.05", "Genel Açıklamalar"],
        ["Şenet iplik", "56.06", "60.02–60.03 Açıklama Notları"],
        ["Tıbbi, perakende ambalajlı örme sargı", "30.05", "60.02–60.06 Açıklama Notları"],
        ["Kenarı bastırılmış örme boyun atkısı; şekilli örülmüş giysi parçaları", "Fasıl 61", "Hazır eşya; Bölüm XI Not 7–8"],
        ["Örme battaniye, perde, masa örtüsü (hazır)", "Fasıl 63", "Hazır eşya"],
    ],
    "tuzaklar": [
        "<b>Kaplanmış örme 59’a, kaplanmış tüylü örme 60.01’e.</b> Not 1(c) kaplanmış örme mensucatı Fasıl 59’a gönderir; tüylü olanı istisna olarak 60.01’de bırakır.",
        "<b>Tüy önce gelir.</b> 60.01’de en ve elastomer oranı aranmaz; 60.02–60.05 metinleri 60.01’dekileri açıkça hariç tutar.",
        "<b>30 cm sınırı dahil edicidir.</b> “Eni 30 cm’yi geçmeyen” ifadesi tam 30 cm’yi de kapsar: 30 cm → 60.02/60.03; 31 cm → 60.04–60.06.",
        "<b>%5 eşiği de dahil edicidir.</b> Ağırlıkça %5 veya daha fazla elastomerik ya da kauçuk iplik → 60.02 (dar) / 60.04 (geniş); ölçüt hacim değil ağırlıktır.",
        "<b>Çözgülü örme her zaman 60.05 değildir.</b> Eni 30 cm’yi geçen ve elastomeri %5 veya daha fazla olan çözgülü örme 60.04’e gider; 60.05, 60.01–60.04’tekileri hariç tutar.",
        "<b>Taklit havlu ≠ tufte.</b> Arkasında zincir dikiş sıraları bulunan örme bukleli mensucat 60.01; tufte edilmiş örme mensucat 58.02.",
        "<b>Raschel taklit dantelası dantela değildir.</b> Çözgülü makinede örülüp dantelaya benzeyen mensucat 60.05; tığ işi dantela 58.04.",
        "<b>Dikiş-trikotaj örmedir, lif dikme-örme keçedir.</b> İlmikler iplikten → Fasıl 60 (çözgü örgüsü); ilmikler tülbendin kendi liflerinden → 56.02.",
        "<b>Basit kesim fasıl değiştirmez, ileri işlem değiştirir.</b> Kare/dikdörtgen kesilmiş örme parça Fasıl 60’ta; kenarı bastırılmış veya şekil verilerek örülmüş parça hazır eşyadır (Fasıl 61–63).",
    ],
    "hafiza": {
        "kanca": "TÜY – DAR ELASTİK – DAR – GENİŞ ELASTİK – ÇÖZGÜ – DİĞER",
        "aciklama": "60.01 <b>tüy</b>lü; 60.02 <b>dar</b> (≤ 30 cm) ve <b>elastik</b> (≥ %5); 60.03 <b>dar</b> diğer; 60.04 <b>geniş elastik</b>; 60.05 geniş <b>çözgü</b> örgüsü; 60.06 geniş <b>diğer</b> (atkılı, kroşe). Sorma sırası hep aynıdır: önce tüy, sonra en, sonra elastik, en son örgü tipi.",
    },
    "sinav_odagi": [
        "Bu fasıl çıkmış sorularda yalnızca seçeneklerde ve çeldirici olarak yer almıştır; doğrudan Fasıl 60 eşyası sorulmamıştır.",
        "Seyahat battaniyeleri sorusunda 60.05 çeldirici olarak verilmiştir: kullanıma hazır battaniye, örme olsa bile parça halindeki mensucat pozisyonuna değil 63.01’e girer.",
        "Bölüm XI genel sorusunda dokumaya elverişli maddelerin 50–63. fasıllarda yer aldığı sorulmuştur; Fasıl 60 bu aralıkta parça halindeki örme mensucatın yeridir, hazır örme eşya 61–63’e gider.",
        "Eldiven ve fular sorularında örme / örülmemiş ayrımı belirleyici olmuştur: örme eşya Fasıl 61, örülmemiş eşya Fasıl 62.",
    ],
    "cikmis_ornekler": [
        {
            "soru": "Seyahat battaniyeleri hangi tarife pozisyonunda sınıflandırılır?",
            "secenekler": ["60.05", "61.17", "62.05", "63.01", "96.05"],
            "cevap": "D",
            "aciklama": "Battaniye, kullanıma hazır üretilen hazır eşyadır (Bölüm XI Not 7); Fasıl 60 yalnız parça halindeki örme mensucatı kapsadığından örme olsa bile 60.05’e girmez. Battaniyeler ve seyahat battaniyeleri 63.01’dedir.",
        },
    ],
    "ozet": [
        "Fasıl 60 = parça halindeki örme veya kroşe mensucat; hazır eşya Fasıl 61–63’tedir.",
        "Sıra: tüylü mü (60.01) → en ≤ 30 cm mi → elastomer/kauçuk iplik ≥ %5 mi → çözgü mü (60.05) → diğer (60.06).",
        "Kaplanmış örme mensucat Fasıl 59; kaplanmış tüylü örme mensucat 60.01.",
        "Dikiş-trikotaj örmedir (Not 3); liflerin kendisiyle dikme-örme mensucat 56.02.",
        "Tığ işi dantela 58.04, örme etiket 58.07, tufte örme 58.02, suni kürk 43.04.",
        "Metal iplikten giyim ve döşemecilik türü örme eşya da Fasıl 60’tadır.",
    ],
    "sorular": kur(sorular, 6002),
}

yaz(d, 60)
